### PR TITLE
fix to_json for numbers larger than sys.maxsize

### LINKED ISSUE #34395: BUG: OverflowError on to_json with numbers larger than sys.maxsize
- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the latest version of pandas.
- [ ] (optional) I have confirmed this bug exists on the master branch of pandas.

---

**Note**: Please read [this guide](https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) detailing how to provide the necessary information for us to reproduce your bug.

#### Code Sample, a copy-pastable example

```python
import sys
from pandas.io.json import dumps

dumps(sys.maxsize)
dumps(sys.maxsize + 1)
```

#### Problem description

The Pandas JSON dumper doesn't seem to handle number values larger than `sys.maxsize` (a word). I have a dataframe that I'm trying to write to_json, but it's failing with `OverflowError: int too big to convert`. There are some numbers larger than `9223372036854775807` in it.

Passing a `default_handler` doesn't help. It doesn't get called for the error.

```python
>>> dumps(sys.maxsize)
'9223372036854775807'
>>> dumps(sys.maxsize + 1, default_handler=str)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
OverflowError: int too big to convert
```

#### Expected Output

Python's built-in json module handles large numbers without issues.

```python
>>> import json
>>> json.dumps(sys.maxsize)
'9223372036854775807'
>>> json.dumps(sys.maxsize+1)
'9223372036854775808'
```

I expect Pandas to be able to output large numbers to JSON. An option to use the built-in `json` module instead of `ujson` would be fine.

#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit           : None
python           : 3.8.3.final.0
python-bits      : 64
OS               : Linux
OS-release       : 4.19.76-linuxkit
machine          : x86_64
processor        :
byteorder        : little
LC_ALL           : None
LANG             : C.UTF-8
LOCALE           : en_US.UTF-8

pandas           : 1.0.3
numpy            : 1.18.2
pytz             : 2019.3
dateutil         : 2.8.1
pip              : 20.1.1
setuptools       : 46.4.0
Cython           : None
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : 2.11.2
IPython          : None
pandas_datareader: None
bs4              : None
bottleneck       : None
fastparquet      : None
gcsfs            : None
lxml.etree       : None
matplotlib       : None
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : 0.16.0
pytables         : None
pytest           : None
pyxlsb           : None
s3fs             : 0.4.2
scipy            : None
sqlalchemy       : None
tables           : None
tabulate         : None
xarray           : None
xlrd             : None
xlwt             : None
xlsxwriter       : None
numba            : None

</details>

### PR DESCRIPTION
**Pull request by arw2019**
- [x] closes #34395 
- [x] tests added / passed
- [x] passes `black pandas`
- [x] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [x] passes performance benchmarks
- [x] whatsnew entry

Currently this patch causes a significant reduction for a number of the JSON performance benchmarks. A printout of my results is included below.

[json_benchmarks_results.txt](https://github.com/pandas-dev/pandas/files/4704831/json_benchmarks_results.txt)

I'd love to keep working on this if anybody has ideas for making the solution more efficient!

### CODE REVIEW

**Review by jreback — CHANGES_REQUESTED** [review]
this needs to be handled in the ujson impl

**Comment by WillAyd** [comment]
If we do it in ujson would be around here:

https://github.com/pandas-dev/pandas/blob/1cad9e52ee1028db3bb4b9e86998104eb4d6b0ee/pandas/_libs/src/ujson/python/objToJSON.c#L1636

So instead of raising I think would convert to a buffer or string object and write that out. Would probably need to do something else on top of that to not add quotes in the output

**Comment by arw2019** [comment]
@WillAyd Thanks for this! I'm some of the way along the solution. 

Inside the if statement that starts on line
 https://github.com/pandas-dev/pandas/blob/1cad9e52ee1028db3bb4b9e86998104eb4d6b0ee/pandas/_libs/src/ujson/python/objToJSON.c#L1636
I convert `obj` into a string. This then needs be passed along for encoding. 

Scrolling down `objToJSON.c` I understand that in this line
https://github.com/pandas-dev/pandas/blob/1cad9e52ee1028db3bb4b9e86998104eb4d6b0ee/pandas/_libs/src/ujson/python/objToJSON.c#L2285
the `objToJSON` function has created an encoded string using the `encoder` and `buffer` objects. I feel like I'm not quite clear on how those work here... If I'm understanding correctly, the `encoder` is a `struct` with information about formatting and the `buffer` is where the output is actually stored. In that case I would want to figure out how to set the parameters of the encoder and how to dump my string into the buffer?

Thanks so much for the help with this!

**Comment by WillAyd** [comment]
You typically don't need to touch the buffer. At a high level the way it works is you set the type of object being serialized and there is a context associated with that type which the serializer will use to determine whether to continue recursion further (i.e. to keep nesting say a dictionary) or to simply write the object.

You can take any example, but if you look at the float code:

https://github.com/pandas-dev/pandas/blob/d5e8edcdfa0eaf6847faf95e15a607e03068eb4c/pandas/_libs/src/ujson/python/objToJSON.c#L1642

We are introspecting the object, setting the appropriate `doubleValue` member (for the non null case) and telling the serializer that the type of the object is `JT_DOUBLE`. If you then look here you'll see ujson writing that value out to the buffer:

https://github.com/pandas-dev/pandas/blob/d5e8edcdfa0eaf6847faf95e15a607e03068eb4c/pandas/_libs/src/ujson/lib/ultrajsonenc.c#L1072

So for this, would need to figure out a way to write out a numeric value that exceeds C's storage limits for integers. 

One possible way is to store the Python str representation of the value into the `cStr` member of the `TypeContext` struct much like we do for JT_UTF8 types, but instead of using UTF8 as the type (which will add quoting) create a new enum entry here that allows that wouldn't quote the output and add the appropriate code to the serializer for that type

https://github.com/pandas-dev/pandas/blob/d5e8edcdfa0eaf6847faf95e15a607e03068eb4c/pandas/_libs/src/ujson/lib/ultrajson.h#L146

File: pandas/_libs/src/ujson/lib/ultrajsonenc.c [hunk 1]
```diff
@@ -1080,6 +1087,39 @@ void encode(JSOBJ obj, JSONObjectEncoder *enc, const char *name,
...
+                    enc->level--;
+                    return;
+                }
+            }
+
+            Buffer_AppendCharUnchecked(enc, '\"');
+            break;
+        }
+
+        case JT_BIGNUM: {
```
Comment (WillAyd) [inline pandas/_libs/src/ujson/lib/ultrajsonenc.c:1111]: The implementation here should be pretty similar to the UTF8 case but remove the `Buffer_AppendCharUnchecked(enc, '\"');` lines. You also don't need the `enc->forceASCII` check and can just do `1Buffer_EscapeStringUnvalidated`

File: pandas/_libs/src/ujson/python/objToJSON.c [hunk 2]
```diff
@@ -106,6 +106,8 @@ typedef struct __TypeContext {
     double doubleValue;
     JSINT64 longValue;
 
+    char bigNum;
```
Comment (WillAyd) [inline pandas/_libs/src/ujson/python/objToJSON.c:109]: You would want a pointer to a char here, but it's probably easiest to not add another struct member and just write to `cStr` for now

**Comment by WillAyd** [comment]
Can you add a test for this? Will help guide the implementation and feedback

File: pandas/_libs/src/ujson/lib/ultrajsonenc.c (hunk 1 above)
Comment (WillAyd) [reply pandas/_libs/src/ujson/lib/ultrajsonenc.c:1111]: I think you will also need to define a function pointer for a callback that converts the object to a string representation

See:

https://github.com/pandas-dev/pandas/blob/e79487d8e50a03be87188608cd1379330a4fd224/pandas/_libs/src/ujson/python/objToJSON.c#L2116

And 

https://github.com/pandas-dev/pandas/blob/e79487d8e50a03be87188608cd1379330a4fd224/pandas/_libs/src/ujson/python/objToJSON.c#L1659

As examples

File: pandas/_libs/src/ujson/python/objToJSON.c (hunk 2 above)
Comment (arw2019) [reply pandas/_libs/src/ujson/python/objToJSON.c:109]: Ok! Got rid of this

**Comment by arw2019** [comment]
> Can you add a test for this? Will help guide the implementation and feedback

I added one in  `pandas/tests/io/json/test_ujson.py`. I'm testing encoding and decoding against the in-built `json` library:

```python
big_num = sys.maxsize + 1
encoding = ujson.dumps(big_num)

assert encoding == json.dumps(big_num)
assert ujson.loads(encoding) == big_num
```

File: pandas/tests/io/json/test_ujson.py [hunk 3]
```diff
@@ -559,6 +560,14 @@ def test_encode_long_conversion(self):
         assert output == json.dumps(long_input)
         assert long_input == ujson.decode(output)
 
+    def test_dumps_ints_larger_than_maxsize(self):
+        # GH34395
+        big_num = sys.maxsize + 1
+        encoding = ujson.dumps(big_num)
+
+        assert encoding == json.dumps(big_num)
+        assert ujson.loads(encoding) == big_num
```
Comment (WillAyd) [inline pandas/tests/io/json/test_ujson.py:569]: This would require fixing both to_json and read_json which could be a rather large PR. I think OK to just compare the output of to_json to the expected string for now

File: pandas/_libs/src/ujson/python/objToJSON.c [hunk 4]
```diff
@@ -2126,6 +2128,12 @@ double Object_getDoubleValue(JSOBJ Py_UNUSED(obj), JSONTypeContext *tc) {
     return GET_TC(tc)->doubleValue;
 }
 
+const char *Object_getBigNumStringValue(JSOBJ obj, JSONTypeContext *tc) {
+    // Question (arw2019): is this function right? 
+    // Do I need the outLen argument for example?
```
Comment (WillAyd) [inline pandas/_libs/src/ujson/python/objToJSON.c:2133]: Yea you need to modify the outLen pointer to let the serializer know how many bytes it should write out

File: pandas/_libs/src/ujson/python/objToJSON.c [hunk 5]
```diff
@@ -1635,7 +1635,9 @@ void Object_beginTypeContext(JSOBJ _obj, JSONTypeContext *tc) {
 
         if (exc && PyErr_ExceptionMatches(PyExc_OverflowError)) {
             PRINTMARK();
-            goto INVALID;
+            tc->type = JT_BIGNUM;
+            /* Question (arw2019): is this where I convert obj into a string
```
Comment (WillAyd) [inline pandas/_libs/src/ujson/python/objToJSON.c:1639]: Do this in the `Object_getBigNumStringValue` function you have defined

File: pandas/tests/io/json/test_ujson.py [hunk 6]
```diff
@@ -559,6 +560,15 @@ def test_encode_long_conversion(self):
         assert output == json.dumps(long_input)
         assert long_input == ujson.decode(output)
 
+    def test_dumps_ints_larger_than_maxsize(self):
+        # GH34395
+        big_num = sys.maxsize + 1
+        encoding = ujson.dumps(big_num)
+
+        assert encoding == json.dumps(big_num)
```
Comment (WillAyd) [inline pandas/tests/io/json/test_ujson.py:568]:
```suggestion
        assert str(encoding) == json.dumps(big_num)
```

File: pandas/_libs/src/ujson/python/objToJSON.c [hunk 7]
```diff
@@ -2126,6 +2126,15 @@ double Object_getDoubleValue(JSOBJ Py_UNUSED(obj), JSONTypeContext *tc) {
     return GET_TC(tc)->doubleValue;
 }
 
+// /*
+const char *Object_getBigNumStringValue(JSOBJ obj, JSONTypeContext *tc) {
+    // char wstr[100];
+    int sign = (obj<0) ? -1 : 1;
```
Comment (WillAyd) [inline pandas/_libs/src/ujson/python/objToJSON.c:2132]: just FYI `obj` is a pointer to a PyObject

File: pandas/_libs/src/ujson/python/objToJSON.c [hunk 8]
```diff
@@ -2127,10 +2130,36 @@ double Object_getDoubleValue(JSOBJ Py_UNUSED(obj), JSONTypeContext *tc) {
...
 
 // /*
-const char *Object_getBigNumStringValue(JSOBJ obj, JSONTypeContext *tc) {
-    // char wstr[100];
-    int sign = (obj<0) ? -1 : 1;
-    printf("sign %d\n", sign);
+const char *Object_getBigNumStringValue(JSOBJ obj, JSONTypeContext *tc, 
+                                    size_t *_outLen) {
+    /* here goes the code that converts obj into a string
+    char *wstr;
```
Comment (WillAyd) [inline pandas/_libs/src/ujson/python/objToJSON.c:2136]: Just use PyObject_Str

File: pandas/_libs/src/ujson/python/objToJSON.c [hunk 9]
```diff
@@ -2126,6 +2126,18 @@ double Object_getDoubleValue(JSOBJ Py_UNUSED(obj), JSONTypeContext *tc) {
     return GET_TC(tc)->doubleValue;
 }
 
+const char *Object_getBigNumStringValue(JSOBJ obj, JSONTypeContext *tc, 
+                                    size_t *_outLen) {
+    PyObject* repr = PyObject_Repr(obj);
+    PyObject* str = PyUnicode_AsEncodedString(repr, "utf-8", "~E~");
+    char *bytes = PyBytes_AS_STRING(str);
+
+    PyObject_Free(GET_TC(tc)->cStr);
```
Comment (arw2019) [inline pandas/_libs/src/ujson/python/objToJSON.c:2135]: Not sure if need this?

File: pandas/_libs/src/ujson/python/objToJSON.c [hunk 10]
```diff
@@ -2179,6 +2191,7 @@ PyObject *objToJSON(PyObject *Py_UNUSED(self), PyObject *args,
         Object_endTypeContext,
         Object_getStringValue,
         Object_getLongValue,
+        Object_getBigNumStringValue,
```
Comment (arw2019) [inline pandas/_libs/src/ujson/python/objToJSON.c:2194]: This line throws a compiler error:
```
pandas/_libs/src/ujson/python/objToJSON.c:2194:9: error: initialization of ‘JSINT32 (*)(void *, JSONTypeContext *)’ {aka ‘int (*)(void *, struct __JSONTypeContext *)’} from incompatible pointer type ‘const char * (*)(void *, JSONTypeContext *, size_t *)’ {aka ‘const char * (*)(void *, struct __JSONTypeContext *, long unsigned int *)’} [-Werror=incompatible-pointer-types]
```

File: pandas/_libs/src/ujson/python/objToJSON.c [hunk 11]
```diff
@@ -2126,6 +2126,18 @@ double Object_getDoubleValue(JSOBJ Py_UNUSED(obj), JSONTypeContext *tc) {
     return GET_TC(tc)->doubleValue;
 }
 
+const char *Object_getBigNumStringValue(JSOBJ obj, JSONTypeContext *tc, 
+                                    size_t *_outLen) {
+    PyObject* repr = PyObject_Repr(obj);
+    PyObject* str = PyUnicode_AsEncodedString(repr, "utf-8", "~E~");
+    char *bytes = PyBytes_AS_STRING(str);
```
Comment (WillAyd) [inline pandas/_libs/src/ujson/python/objToJSON.c:2133]: You will want PyUnicode_AsUTF8AndSize here. You can pass outLen as the second argument

File: pandas/_libs/src/ujson/python/objToJSON.c (hunk 9 above)
Comment (WillAyd) [reply pandas/_libs/src/ujson/python/objToJSON.c:2135]: Nothing has been allocated yet so shouldn’t be freeing here. I think this is undefined behavior and most likely would segfault

File: pandas/_libs/src/ujson/python/objToJSON.c [hunk 12]
```diff
@@ -2126,6 +2126,18 @@ double Object_getDoubleValue(JSOBJ Py_UNUSED(obj), JSONTypeContext *tc) {
     return GET_TC(tc)->doubleValue;
 }
 
+const char *Object_getBigNumStringValue(JSOBJ obj, JSONTypeContext *tc, 
+                                    size_t *_outLen) {
+    PyObject* repr = PyObject_Repr(obj);
```
Comment (WillAyd) [inline pandas/_libs/src/ujson/python/objToJSON.c:2131]: I think should use Str instead of Repr here

File: pandas/_libs/src/ujson/python/objToJSON.c [hunk 13]
```diff
@@ -2126,6 +2126,18 @@ double Object_getDoubleValue(JSOBJ Py_UNUSED(obj), JSONTypeContext *tc) {
...
+    PyObject* str = PyUnicode_AsEncodedString(repr, "utf-8", "~E~");
+    char *bytes = PyBytes_AS_STRING(str);
+
+    PyObject_Free(GET_TC(tc)->cStr);
+    GET_TC(tc)->cStr = bytes;
```
Comment (WillAyd) [inline pandas/_libs/src/ujson/python/objToJSON.c:2136]: So to manage the state properly you should allocate storage for bytes and memcpy whatever PyUnicode_AsUTF8AndSize returns to it. You will need to then free that memory in the callback function for ObjectEnd

File: pandas/_libs/src/ujson/python/objToJSON.c [hunk 14]
```diff
@@ -2126,6 +2126,18 @@ double Object_getDoubleValue(JSOBJ Py_UNUSED(obj), JSONTypeContext *tc) {
     return GET_TC(tc)->doubleValue;
 }
 
+const char *Object_getBigNumStringValue(JSOBJ obj, JSONTypeContext *tc, 
+                                    size_t *_outLen) {
+    PyObject* repr = PyObject_Repr(obj);
+    PyObject* str = PyUnicode_AsEncodedString(repr, "utf-8", "~E~");
```
Comment (WillAyd) [inline pandas/_libs/src/ujson/python/objToJSON.c:2132]: Make sure you Py_DECREF these objects when they are no longer needed or else this will leak memory

File: pandas/_libs/src/ujson/python/objToJSON.c (hunk 10 above)
Comment (WillAyd) [reply pandas/_libs/src/ujson/python/objToJSON.c:2194]: You will need to update the PyEncoder struct to have the appropriate member definitions

File: pandas/_libs/src/ujson/python/objToJSON.c (hunk 9 above)
Comment (arw2019) [reply pandas/_libs/src/ujson/python/objToJSON.c:2135]: Got rid of it

File: pandas/_libs/src/ujson/python/objToJSON.c [hunk 15]
```diff
@@ -2126,6 +2126,20 @@ double Object_getDoubleValue(JSOBJ Py_UNUSED(obj), JSONTypeContext *tc) {
     return GET_TC(tc)->doubleValue;
 }
 
+const char *Object_getBigNumStringValue(JSOBJ obj, JSONTypeContext *tc, 
+                                    size_t *_outLen) {
+    PyObject* repr = PyObject_Str(obj);
+    PyObject* str = PyUnicode_AsEncodedString(repr, "utf-8", "~E~");
+    char *bytes = PyBytes_AS_STRING(str);
+
+    Py_XDECREF(repr);
```
Comment (WillAyd) [inline pandas/_libs/src/ujson/python/objToJSON.c:2135]: If this object gets released would also free bytes, so need to memcpy first. 

Also just use Py_DECREF for these as simple enough to see lifecycle

Comment (arw2019) [reply pandas/_libs/src/ujson/python/objToJSON.c:2137]: Ok! Now I memcpy bytes into `tc->cStr` before freeing up `repr`, `str` and `bytes`.

Looking at `tc->cStr` I think it  gets freed-up in `Object_endTypeContext`:
https://github.com/pandas-dev/pandas/blob/c45e92c3956fd2638980ac46e6e93ec3b6cc7c52/pandas/_libs/src/ujson/python/objToJSON.c#L2109

File: pandas/_libs/src/ujson/python/objToJSON.c [hunk 16]
```diff
@@ -2126,6 +2126,21 @@ double Object_getDoubleValue(JSOBJ Py_UNUSED(obj), JSONTypeContext *tc) {
     return GET_TC(tc)->doubleValue;
 }
 
+const char *Object_getBigNumStringValue(JSOBJ obj, JSONTypeContext *tc, 
+                                    size_t *_outLen) {
+    PyObject* repr = PyObject_Str(obj);
+    PyObject* str = PyUnicode_AsUTF8AndSize(repr, _outLen);
+    char bytes[_outlen];
```
Comment (WillAyd) [inline pandas/_libs/src/ujson/python/objToJSON.c:2133]: This array is managed on the stack, so it automatically gets cleaned up when it goes out of scope, which isn’t what you want (and the reason for multiple memcpy calls)

Instead just malloc _outLen bytes and then memcpy to that, before assign that to cStr

Comment (arw2019) [reply pandas/_libs/src/ujson/python/objToJSON.c]: > Instead just malloc _outLen bytes and then memcpy to that, before assign that to cStr

Ok, great! I fixed that.

One thing I'm stuck on is converting from the argument of `PyUnicode_AsUTF8AndSize` (which has to be a `Py_ssize_t`) to `_outLen` (which is C `size_t`)...

Also, just to check: I do need dereference `_outLen` in the calls to `memcpy` and `malloc`?

**Review by WillAyd — CHANGES_REQUESTED** [review]
Getting closer

**Review by WillAyd — CHANGES_REQUESTED** [review]

**Comment by WillAyd** [comment]
Just use parentheses not angled brackets so (Py_ssize_t) *_outLen

**Comment by arw2019** [comment]
> Just use parentheses not angled brackets so (Py_ssize_t) *_outLen

Still getting this:
```
pandas/_libs/src/ujson/python/objToJSON.c:2133:53: error: passing argument 2 of ‘PyUnicode_AsUTF8AndSize’ makes pointer from integer without a cast [-Werror=int-conversion]
     const char *str = PyUnicode_AsUTF8AndSize(repr, (Py_ssize_t) *_outLen);
                                                     ^~~~~~~~~~~~~~~~~~~~~
```

**Comment by WillAyd** [comment]
Oh sorry got mixed up on comments. You need to pass the pointer and can cast that if needed, so `PyUnicode_AsUTF8AndSize(repr, (Py_ssize_t *) _outLen)`

**Comment by arw2019** [comment]
> You need to pass the pointer and can cast that if needed, so `PyUnicode_AsUTF8AndSize(repr, (Py_ssize_t *) _outLen)`

@WillAyd This works - thanks so much for the help on this!

As you said what's left, modulo memory leaks, is to fix up `pyEncoder`.  I added `Object_getBigNumAsString` to the definition here:
https://github.com/pandas-dev/pandas/blob/5fdd6f50ac5ac2de939ef5b849e4c41e27e623a3/pandas/_libs/src/ujson/python/objToJSON.c#L2177
which however throws an error:
```
pandas/_libs/src/ujson/python/objToJSON.c:2197:9: error: initialization of ‘JSINT32 (*)(void *, JSONTypeContext *)’ {aka ‘int (*)(void *, struct __JSONTypeContext *)’} from incompatible pointer type ‘const char * (*)(void *, JSONTypeContext *, size_t *)’ {aka ‘const char * (*)(void *, struct __JSONTypeContext *, long unsigned int *)’} [-Werror=incompatible-pointer-types]
         Object_getBigNumStringValue,
```
I feel like the issue is that the compiler treats `Object_getBigNumAsStringValue` as undeclared back in line 1638-9 where I do:
```
tc->type = JT_BIGNUM;
pc->PyTypeToUTF8 = Object_getBigNumStringValue;
```
because that's the other compiler error:
```
pandas/_libs/src/ujson/python/objToJSON.c:1639:32: error: ‘Object_getBigNumStringValue’ undeclared (first use in this function)
             pc->PyTypeToUTF8 = Object_getBigNumStringValue;
```
but this doesn't make sense to me because I declare `Object_getBigNumStringValue` in the `ultrajson.h` so in effect there should be a declaration at the top of the file...

**Comment by WillAyd** [comment]
IIUC your problem is probably that you aren't updating the struct declaration here:

https://github.com/pandas-dev/pandas/blob/5fdd6f50ac5ac2de939ef5b849e4c41e27e623a3/pandas/_libs/src/ujson/python/objToJSON.c#L119

You can declare that pointer at the end of the struct that way everything between that and the definition you are updating above will know appropriately how to handle `PyObjectEncoder`

File: pandas/_libs/src/ujson/python/objToJSON.c [hunk 17]
```diff
@@ -136,6 +136,8 @@ typedef struct __PyObjectEncoder {
     int outputFormat;
     int originalOutputFormat;
 
+    const char *Object_getBigNumStringValue;
```
Comment (WillAyd) [inline pandas/_libs/src/ujson/python/objToJSON.c:139]: Wherever you declare this object to be in this struct needs to match the subsequent definition. So if you place this here then down on L2199 need to make sure it appears in the same position when

File: pandas/tests/io/json/test_ujson.py [hunk 18]
```diff
@@ -559,6 +560,15 @@ def test_encode_long_conversion(self):
         assert output == json.dumps(long_input)
         assert long_input == ujson.decode(output)
 
+    def test_dumps_ints_larger_than_maxsize(self):
```
Comment (jreback) [inline pandas/tests/io/json/test_ujson.py:563]: can you also add a full integration test in json/test_pandas.py

File: doc/source/whatsnew/v1.1.0.rst [hunk 19]
```diff
@@ -901,6 +901,7 @@ I/O
 - Bug in :meth:`~DataFrame.read_feather` was raising an `ArrowIOError` when reading an s3 or http file path (:issue:`29055`)
 - Bug in :meth:`~DataFrame.to_excel` could not handle the column name `render` and was raising an ``KeyError`` (:issue:`34331`)
 - Bug in :meth:`~SQLDatabase.execute` was raising a ``ProgrammingError`` for some DB-API drivers when the SQL statement contained the `%` character and no parameters were present (:issue:`34211`)
+- Bug in :meth:`json.dumps` was raising an `OverflowError` with numbers larger than sys.maxsize (:issue: `34395`)
```
Comment (jreback) [inline doc/source/whatsnew/v1.1.0.rst:904]: this is not a public method

**Review by jreback — CHANGES_REQUESTED** [review]

File: pandas/_libs/src/ujson/lib/ultrajsonenc.c (hunk 1 above)
Comment (arw2019) [reply pandas/_libs/src/ujson/lib/ultrajsonenc.c:1111]: So this works up to line 1112, in that
``` C++
 value = enc->getBigNumStringValue(obj, &tc, &szlen);
```
gets the correct string (I checked with a print statement). But there's still a problem because we exit with an `OverflowError` via this line (checked with a print statement)
https://github.com/pandas-dev/pandas/blob/5d69786af46291abe727b290a84aa9d2663cd50c/pandas/_libs/src/ujson/python/objToJSON.c#L2289
I feel like this something to do with the buffer and the length of the string we're printing out somehow not being right...?

Comment (WillAyd) [reply pandas/_libs/src/ujson/lib/ultrajsonenc.c:1111]: This goes back to L1636. CPython manages a global error and we never explicitly clear it on that line. You could all `PyErr_Clear()` but it actually would be better if you used `PyLong_AsLongLongAndOverflow` and checked for a non-zero overflow

https://docs.python.org/3/c-api/long.html#c.PyLong_AsLongLongAndOverflow

Comment (arw2019) [reply pandas/_libs/src/ujson/lib/ultrajsonenc.c:1111]: Ok! I'll go with `PyLong_AsLongLongAndOverflow`.

Quick question, though: when I do
``` C++
        int *_overflow = 0;
        GET_TC(tc)->longValue = PyLong_AsLongLongAndOverflow(obj, _overflow);
```
I'm making a mistake (there's a segfault) - but not sure why

Comment (WillAyd) [reply pandas/_libs/src/ujson/lib/ultrajsonenc.c:1111]: The way it is written you are telling the program to write the overflow result to memory location 0, which the program almost assuredly doesn't have access to (hence segfault)

Just declare the int and use the address of operator

```c
int overflow;
GET_TC(tc)->longValue = PyLong_AsLongLongAndOverflow(obj, &overflow);
```

File: pandas/_libs/src/ujson/python/objToJSON.c [hunk 20]
```diff
@@ -1629,14 +1629,20 @@ void Object_beginTypeContext(JSOBJ _obj, JSONTypeContext *tc) {
     if (PyLong_Check(obj)) {
         PRINTMARK();
         tc->type = JT_LONG;
-        GET_TC(tc)->longValue = PyLong_AsLongLong(obj);
-
+        int _overflow = 0;
+        GET_TC(tc)->longValue = PyLong_AsLongLongAndOverflow(obj, &_overflow);
         exc = PyErr_Occurred();
 
+        if (!exc && (_overflow!=0)){
```
Comment (WillAyd) [inline pandas/_libs/src/ujson/python/objToJSON.c:1636]: I could be wrong but I don’t think you need the error check here

Comment (WillAyd) [reply pandas/_libs/src/ujson/python/objToJSON.c:1636]: Nevermind i think this is ok. 

For performance though I think should check that the return value is -1 first before checking for an error, as the latter can be expensive so good to short circuit

Comment (arw2019) [reply pandas/_libs/src/ujson/python/objToJSON.c]: Ok! Added that. Does seem to work without the error check also though

File: pandas/tests/io/json/test_ujson.py [hunk 21]
```diff
@@ -559,6 +560,15 @@ def test_encode_long_conversion(self):
...
+        # GH34395
+        big_num = sys.maxsize + 1
+        encoding = ujson.dumps(big_num)
+
+        assert str(encoding) == json.dumps(big_num)
```
Comment (WillAyd) [inline pandas/tests/io/json/test_ujson.py:568]:
```suggestion
        assert str(big_num) == json.dumps(big_num)
```

File: pandas/_libs/src/ujson/python/objToJSON.c [hunk 22]
```diff
@@ -1629,14 +1629,20 @@ void Object_beginTypeContext(JSOBJ _obj, JSONTypeContext *tc) {
...
+        int _overflow = 0;
+        GET_TC(tc)->longValue = PyLong_AsLongLongAndOverflow(obj, &_overflow);
         exc = PyErr_Occurred();
 
+        if ((GET_TC(tc)->longValue == -1) && _overflow && !exc){
+            PRINTMARK();
+            tc->type = JT_BIGNUM;
+        }
+
         if (exc && PyErr_ExceptionMatches(PyExc_OverflowError)) {
```
Comment (WillAyd) [inline pandas/_libs/src/ujson/python/objToJSON.c:1641]: You can delete this condition now

File: pandas/_libs/src/ujson/python/objToJSON.c [hunk 23]
```diff
@@ -1629,14 +1629,20 @@ void Object_beginTypeContext(JSOBJ _obj, JSONTypeContext *tc) {
     if (PyLong_Check(obj)) {
         PRINTMARK();
         tc->type = JT_LONG;
-        GET_TC(tc)->longValue = PyLong_AsLongLong(obj);
-
+        int _overflow = 0;
+        GET_TC(tc)->longValue = PyLong_AsLongLongAndOverflow(obj, &_overflow);
         exc = PyErr_Occurred();
```
Comment (WillAyd) [inline pandas/_libs/src/ujson/python/objToJSON.c:1634]:
```suggestion
        exc = GET_TC(tc)->LongValue == -1 && PyErr_Occurred();
```

Then can simplify condition on next line to just if `(_overflow && !exc)`

File: pandas/_libs/src/ujson/python/objToJSON.c [hunk 24]
```diff
@@ -1629,14 +1629,20 @@ void Object_beginTypeContext(JSOBJ _obj, JSONTypeContext *tc) {
     if (PyLong_Check(obj)) {
         PRINTMARK();
         tc->type = JT_LONG;
-        GET_TC(tc)->longValue = PyLong_AsLongLong(obj);
-
+        int _overflow = 0;
```
Comment (WillAyd) [inline pandas/_libs/src/ujson/python/objToJSON.c:1632]:
```suggestion
        int overflow = 0;
```

No need to prepend an underscore here; may be confusing to authors who expect that to mean something

**Review by WillAyd — CHANGES_REQUESTED** [review]

File: pandas/_libs/src/ujson/python/objToJSON.c [hunk 25]
```diff
@@ -1629,14 +1629,21 @@ void Object_beginTypeContext(JSOBJ _obj, JSONTypeContext *tc) {
...
+        err = (GET_TC(tc)->longValue == -1) && PyErr_Occurred();
 
-        exc = PyErr_Occurred();
+        if (overflow && !err){
+            PRINTMARK();
+            tc->type = JT_BIGNUM;
+        }
 
-        if (exc && PyErr_ExceptionMatches(PyExc_OverflowError)) {
+        if (err && PyErr_ExceptionMatches(PyExc_OverflowError)) {
```
Comment (WillAyd) [inline pandas/_libs/src/ujson/python/objToJSON.c:1642]:
```suggestion
        if (err) {
```

File: pandas/_libs/src/ujson/python/objToJSON.c [hunk 26]
```diff
@@ -1629,14 +1629,21 @@ void Object_beginTypeContext(JSOBJ _obj, JSONTypeContext *tc) {
...
         PRINTMARK();
         tc->type = JT_LONG;
-        GET_TC(tc)->longValue = PyLong_AsLongLong(obj);
+        int overflow = 0;
+        GET_TC(tc)->longValue = PyLong_AsLongLongAndOverflow(obj, &overflow);
+        _Bool err;
+        err = (GET_TC(tc)->longValue == -1) && PyErr_Occurred();
 
-        exc = PyErr_Occurred();
+        if (overflow && !err){
```
Comment (WillAyd) [inline pandas/_libs/src/ujson/python/objToJSON.c:1637]:
```suggestion
        if (overflow){
```

I think from the doctoring overflow would only get set when there is no error, so don't need both

File: pandas/_libs/src/ujson/python/objToJSON.c [hunk 27]
```diff
@@ -1629,14 +1629,21 @@ void Object_beginTypeContext(JSOBJ _obj, JSONTypeContext *tc) {
     if (PyLong_Check(obj)) {
         PRINTMARK();
         tc->type = JT_LONG;
-        GET_TC(tc)->longValue = PyLong_AsLongLong(obj);
+        int overflow = 0;
+        GET_TC(tc)->longValue = PyLong_AsLongLongAndOverflow(obj, &overflow);
+        _Bool err;
```
Comment (WillAyd) [inline pandas/_libs/src/ujson/python/objToJSON.c:1634]:
```suggestion
        int err;
```

Should just stick with int for now; would need a larger discussion around using C99 types (probably OK but not sure what Windows platforms support)

Comment (WillAyd) [reply pandas/_libs/src/ujson/python/objToJSON.c:1634]: Though you can also just use `exc`? I don't think need a new variable here

File: pandas/tests/io/json/test_ujson.py [hunk 28]
```diff
@@ -579,8 +588,7 @@ class Nested:
             x = 12839128391289382193812939
 
         for _ in range(0, 100):
-            with pytest.raises(OverflowError):
-                ujson.encode(Nested())
+            ujson.encode(Nested())
```
Comment (WillAyd) [inline pandas/tests/io/json/test_ujson.py:591]: You can just delete this test

File: pandas/tests/io/json/test_ujson.py [hunk 29]
```diff
@@ -559,6 +560,14 @@ def test_encode_long_conversion(self):
         assert output == json.dumps(long_input)
         assert long_input == ujson.decode(output)
 
+    def test_dumps_ints_larger_than_maxsize(self):
+        # GH34395
+        big_num = sys.maxsize + 1
+
+        assert str(big_num) == ujson.dumps(big_num)
```
Comment (arw2019) [inline pandas/tests/io/json/test_ujson.py:567]: @WillAyd Seeing an error when I run pytest on this:
```
================================================================================== short test summary info ==================================================================================
FAILED pandas/tests/io/json/test_ujson.py::TestUltraJSONTests::test_encode_numeric_overflow_nested - OverflowError: Unterminated UTF-8 sequence when encoding string
1 failed, 993 passed, 10 skipped, 37 xfailed, 27 warnings in 58.32s
```

File: pandas/tests/io/json/test_ujson.py (hunk 28 above)
Comment (arw2019) [reply pandas/tests/io/json/test_ujson.py:591]: Ok!

File: pandas/_libs/src/ujson/python/objToJSON.c (hunk 27 above)
Comment (arw2019) [reply pandas/_libs/src/ujson/python/objToJSON.c:1634]: I changed it because using `exc` was throwing an error:
```
pandas/_libs/src/ujson/python/objToJSON.c:1634:13: error: assignment to ‘PyObject *’ {aka ‘struct _object *’} from ‘int’ makes pointer from integer without a cast [-Werror=int-conversion]
         exc = (GET_TC(tc)->longValue == -1) && PyErr_Occurred();
             ^
```

Comment (WillAyd) [reply pandas/_libs/src/ujson/python/objToJSON.c]: I think you need `&& (PyErr_Occurred() != NULL)` as that function returns a PyObject pointer

File: pandas/_libs/src/ujson/python/objToJSON.c [hunk 30]
```diff
@@ -2126,6 +2133,20 @@ double Object_getDoubleValue(JSOBJ Py_UNUSED(obj), JSONTypeContext *tc) {
...
+const char *Object_getBigNumStringValue(JSOBJ obj, JSONTypeContext *tc, 
+                                    size_t *_outLen) {
+    PyObject* repr = PyObject_Str(obj);
+    const char *str = PyUnicode_AsUTF8AndSize(repr, (Py_ssize_t *) _outLen);
+    char* bytes = malloc(*_outLen);
+    memcpy(bytes, str, *_outLen);
+    GET_TC(tc)->cStr = bytes;
+
+    Py_DECREF(repr);
+    Py_DECREF(str);
```
Comment (WillAyd) [inline pandas/_libs/src/ujson/python/objToJSON.c:2145]:
```suggestion
```

This could cause strange behavior  (Py_DECREF is only for Python objects)

File: pandas/_libs/src/ujson/lib/ultrajsonenc.c [hunk 31]
```diff
@@ -1107,6 +1107,35 @@ void encode(JSOBJ obj, JSONObjectEncoder *enc, const char *name,
             Buffer_AppendCharUnchecked(enc, '\"');
             break;
         }
+
+        case JT_BIGNUM: {
+            value = enc->getBigNumStringValue(obj, &tc, &szlen);
+
+            Buffer_Reserve(enc, RESERVE_STRING(szlen));
```
Comment (WillAyd) [inline pandas/_libs/src/ujson/lib/ultrajsonenc.c:1114]:
```suggestion
            Buffer_Reserve(enc, szlen);
```

This might be your outstanding issue. This macro reserves a much larger buffer than we know we need here

File: pandas/tests/io/json/test_ujson.py (hunk 18 above)
Comment (WillAyd) [reply pandas/tests/io/json/test_ujson.py:563]: Should also parametrize this to exceed the minimum supported native size

File: pandas/_libs/src/ujson/python/objToJSON.c [hunk 32]
```diff
@@ -1629,14 +1629,21 @@ void Object_beginTypeContext(JSOBJ _obj, JSONTypeContext *tc) {
...
         tc->type = JT_LONG;
-        GET_TC(tc)->longValue = PyLong_AsLongLong(obj);
+        int overflow = 0;
+        GET_TC(tc)->longValue = PyLong_AsLongLongAndOverflow(obj, &overflow);
+        int err;
+        err = (GET_TC(tc)->longValue == -1) && PyErr_Occurred();
 
-        exc = PyErr_Occurred();
+        if (overflow){
+            PRINTMARK();
```
Comment (WillAyd) [inline pandas/_libs/src/ujson/python/objToJSON.c:1638]: I think we do need to add a `PyErr_Clear();` within this branch to prevent this from incorrectly propogating an OverflowError (sorry think I mistakenly asked you to remove before)

File: pandas/_libs/src/ujson/python/objToJSON.c [hunk 33]
```diff
@@ -2126,6 +2133,19 @@ double Object_getDoubleValue(JSOBJ Py_UNUSED(obj), JSONTypeContext *tc) {
     return GET_TC(tc)->doubleValue;
 }
 
+const char *Object_getBigNumStringValue(JSOBJ obj, JSONTypeContext *tc, 
+                                    size_t *_outLen) {
+    PyObject* repr = PyObject_Str(obj);
+    const char *str = PyUnicode_AsUTF8AndSize(repr, (Py_ssize_t *) _outLen);
+    char* bytes = malloc(*_outLen);
```
Comment (WillAyd) [inline pandas/_libs/src/ujson/python/objToJSON.c:2140]: Knowing there's some strange results still outstanding, you *may* need to allocate one extra byte here for a null terminator

Comment (WillAyd) [inline pandas/_libs/src/ujson/python/objToJSON.c:2140]:
```suggestion
    char* bytes = malloc(*_outLen + 1);
```

File: pandas/_libs/src/ujson/python/objToJSON.c [hunk 34]
```diff
@@ -2126,6 +2133,19 @@ double Object_getDoubleValue(JSOBJ Py_UNUSED(obj), JSONTypeContext *tc) {
...
+    memcpy(bytes, str, *_outLen);
```
Comment (WillAyd) [inline pandas/_libs/src/ujson/python/objToJSON.c:2141]:
```suggestion
    memcpy(bytes, str, *_outLen + 1);
```

**Review by WillAyd — COMMENTED** [review]
OK I think we need to allocate one extra byte for the new buffer to make it a real C string

File: pandas/_libs/src/ujson/python/objToJSON.c (hunk 32 above)
Comment (arw2019) [reply pandas/_libs/src/ujson/python/objToJSON.c:1638]: I think that - if I understand the docstring correctly - `PyLong_AsLongLongAndOverflow` doesn't raise an OverflowError (but will raise an error if there's a problem other than Overflow)

One thing I know is this runs ok (including tests) without the `PyErr_Clear()` though I guess it doesn't hurt to add that in?

File: pandas/_libs/src/ujson/python/objToJSON.c [hunk 35]
```diff
@@ -2107,6 +2114,7 @@ void Object_endTypeContext(JSOBJ Py_UNUSED(obj), JSONTypeContext *tc) {
         GET_TC(tc)->columnLabels = NULL;
 
         PyObject_Free(GET_TC(tc)->cStr);
+        free(bytes);
```
Comment (arw2019) [inline pandas/_libs/src/ujson/python/objToJSON.c:2117]: @WillAyd Reallocating `bytes` is an outstanding issue like we discussed a while back. I know we need to free it up after we're done writing the output - but within this function bytes is undeclared, I think

File: pandas/_libs/src/ujson/python/objToJSON.c (hunk 32 above)
Comment (WillAyd) [reply pandas/_libs/src/ujson/python/objToJSON.c:1638]: Yea I think you are right. Let’s keep this as is

File: pandas/_libs/src/ujson/python/objToJSON.c [hunk 36]
```diff
@@ -1629,14 +1629,21 @@ void Object_beginTypeContext(JSOBJ _obj, JSONTypeContext *tc) {
...
+        err = (GET_TC(tc)->longValue == -1) && PyErr_Occurred();
 
-        exc = PyErr_Occurred();
+        if (overflow){
+            PRINTMARK();
+            tc->type = JT_BIGNUM;
+        }
 
-        if (exc && PyErr_ExceptionMatches(PyExc_OverflowError)) {
+        if (err) {
```
Comment (WillAyd) [inline pandas/_libs/src/ujson/python/objToJSON.c:1642]: Can you make this an `else if`

File: pandas/_libs/src/ujson/python/objToJSON.c (hunk 35 above)
Comment (WillAyd) [reply pandas/_libs/src/ujson/python/objToJSON.c:2117]: Bytes is assigned to cStr but you won’t free it in this branch. We need an extra branch that checks for the JT_BIGNUM type and frees cStr in that case

File: pandas/_libs/src/ujson/python/objToJSON.c (hunk 36 above)
Comment (arw2019) [reply pandas/_libs/src/ujson/python/objToJSON.c]: Done!

File: pandas/_libs/src/ujson/python/objToJSON.c [hunk 37]
```diff
@@ -2111,7 +2114,7 @@ void Object_endTypeContext(JSOBJ Py_UNUSED(obj), JSONTypeContext *tc) {
         NpyArr_freeLabels(GET_TC(tc)->columnLabels,
                           GET_TC(tc)->columnLabelsLen);
         GET_TC(tc)->columnLabels = NULL;
-
+        if (tc->type == JT_BIGNUM) free(GET_TC(tc)->bigNum_bytes);
```
Comment (arw2019) [inline pandas/_libs/src/ujson/python/objToJSON.c:2117]: @WillAyd I know this isn't right (as is `ujson.encode` core dumps) but is it the right idea? If yes what should I look to fix

Comment (WillAyd) [reply pandas/_libs/src/ujson/python/objToJSON.c:2117]: Just clear cStr - you don't need bigNum_bytes

File: pandas/_libs/src/ujson/python/objToJSON.c [hunk 38]
```diff
@@ -2114,7 +2112,6 @@ void Object_endTypeContext(JSOBJ Py_UNUSED(obj), JSONTypeContext *tc) {
         NpyArr_freeLabels(GET_TC(tc)->columnLabels,
                           GET_TC(tc)->columnLabelsLen);
         GET_TC(tc)->columnLabels = NULL;
-        if (tc->type == JT_BIGNUM) free(GET_TC(tc)->bigNum_bytes);
         PyObject_Free(GET_TC(tc)->cStr);
```
Comment (arw2019) [inline pandas/_libs/src/ujson/python/objToJSON.c:2115]: @WillAyd This looks like it frees up `cStr`

Comment (WillAyd) [reply pandas/_libs/src/ujson/python/objToJSON.c:2115]: I don't think that is getting hit here. If it would then you would be double freeing those bytes and get a segfault anyway

Comment (arw2019) [reply pandas/_libs/src/ujson/python/objToJSON.c:2115]: Sorry I meant 
``` C
PyObject_Free(GET_TC(tc)->cStr);
```
I think `Object_endTypeContext` gets executed in 
https://github.com/pandas-dev/pandas/blob/e6e08890cc8bd1b162b920cf5a526a433bab8b30/pandas/_libs/src/ujson/lib/ultrajsonenc.c#L1112

Comment (WillAyd) [reply pandas/_libs/src/ujson/python/objToJSON.c:2115]: Can you check that the free on cStr gets hit there? If so then good to go

Comment (arw2019) [reply pandas/_libs/src/ujson/python/objToJSON.c:2115]: Checked just now - it does!

File: pandas/_libs/src/ujson/python/objToJSON.c [hunk 39]
```diff
@@ -2126,6 +2132,19 @@ double Object_getDoubleValue(JSOBJ Py_UNUSED(obj), JSONTypeContext *tc) {
     return GET_TC(tc)->doubleValue;
 }
 
+const char *Object_getBigNumStringValue(JSOBJ obj, JSONTypeContext *tc, 
+                                    size_t *_outLen) {
+    PyObject* repr = PyObject_Str(obj);
+    const char *str = PyUnicode_AsUTF8AndSize(repr, (Py_ssize_t *) _outLen);
+    char* bytes = malloc(*_outLen + 1);
```
Comment (WillAyd) [inline pandas/_libs/src/ujson/python/objToJSON.c:2139]:
```suggestion
    char* bytes = PyObject_Malloc(*_outLen + 1);
```
Since you noticed this is already getting freed in the context end, we should use the equivalent python malloc to match that

**Review by WillAyd — COMMENTED** [review]
looks good. can you fix the merge conflict in the whatsnew so CI runs?

File: pandas/tests/io/json/test_pandas.py [hunk 40]
```diff
@@ -1242,6 +1243,25 @@ def test_read_jsonl_unicode_chars(self):
...
+        originalSeries = Series(bigNum, dtype=object, index=["articleId"])
+        originalSeries.to_json()
+        # json = StringIO(json)
+        # newSeries = read_json(json, typ="series")
+        # tm.assert_series_equal(originalSeries, newSeries)
+
+        originalDataFrame = DataFrame(
+            bigNum, dtype=object, index=["articleId"], columns=[0]
+        )
+        originalDataFrame.to_json()
```
Comment (WillAyd) [inline pandas/tests/io/json/test_pandas.py:1259]: It's a little tedious now since we can't roundtrip these but can you manually construct the expected JSON string and compare the result to that?

Comment (arw2019) [reply pandas/tests/io/json/test_pandas.py:1259]: For sure!

File: pandas/tests/io/json/test_pandas.py [hunk 41]
```diff
@@ -1242,6 +1243,22 @@ def test_read_jsonl_unicode_chars(self):
         expected = DataFrame([["foo\u201d", "bar"], ["foo", "bar"]], columns=["a", "b"])
         tm.assert_frame_equal(result, expected)
 
+    def test_to_json_large_numbers(self):
```
Comment (arw2019) [inline pandas/tests/io/json/test_pandas.py:1246]: @jreback This is the full integration test you asked for

**Comment by arw2019** [comment]
@WillAyd Is it worth opening another issue/PR to address the errors raised by `ujson.loads(sys.maxsize+1)`? I'm down to work on that if yes!

**Comment by WillAyd** [comment]
There should already be one if you search the issue tracker. But for sure would take a PR for that as well

**Comment by arw2019** [comment]
I ran the json benchmarks for this branch. Here is the summary:
```
       before           after         ratio
     [208a6ecf]       [44b79f10]
     <master>         <json-Overflow-long-int>
+            175M             202M     1.16  io.json.ReadJSONLines.peakmem_read_json_lines_concat('int')
+            175M             202M     1.16  io.json.ReadJSONLines.peakmem_read_json_lines_concat('datetime')
-         559±8ms         505±10ms     0.90  io.json.ToJSONISO.time_iso_format('index')
-        491±10ms         436±10ms     0.89  io.json.ToJSONISO.time_iso_format('records')

SOME BENCHMARKS HAVE CHANGED SIGNIFICANTLY.
PERFORMANCE DECREASED.
```

File: pandas/_libs/src/ujson/python/objToJSON.c [hunk 42]
```diff
@@ -119,6 +119,7 @@ typedef struct __TypeContext {
 typedef struct __PyObjectEncoder {
     JSONObjectEncoder enc;
 
+
```
Comment (WillAyd) [inline pandas/_libs/src/ujson/python/objToJSON.c:122]: minor nit but can you revert any added / removed blank lines in the PR? Should minimize the diff a bit more

File: pandas/io/json/_json.py [hunk 43]
```diff
@@ -27,6 +27,7 @@
 loads = json.loads
 dumps = json.dumps
 
+
```
Comment (WillAyd) [inline pandas/io/json/_json.py:30]: revert this

File: pandas/_libs/src/ujson/python/objToJSON.c [hunk 44]
```diff
@@ -2105,7 +2112,6 @@ void Object_endTypeContext(JSOBJ Py_UNUSED(obj), JSONTypeContext *tc) {
         NpyArr_freeLabels(GET_TC(tc)->columnLabels,
                           GET_TC(tc)->columnLabelsLen);
         GET_TC(tc)->columnLabels = NULL;
-
```
Comment (WillAyd) [inline pandas/_libs/src/ujson/python/objToJSON.c:2108]: revert this

File: pandas/_libs/src/ujson/python/objToJSON.c [hunk 45]
```diff
@@ -1629,14 +1630,20 @@ void Object_beginTypeContext(JSOBJ _obj, JSONTypeContext *tc) {
...
-        if (exc && PyErr_ExceptionMatches(PyExc_OverflowError)) {
+        if (overflow){
+            PRINTMARK();
+            tc->type = JT_BIGNUM;
+        }
+        else if (err) {
             PRINTMARK();
             goto INVALID;
         }
+
```
Comment (WillAyd) [inline pandas/_libs/src/ujson/python/objToJSON.c:1646]: this too

File: pandas/tests/io/json/test_ujson.py (hunk 18 above)
Comment (WillAyd) [reply pandas/tests/io/json/test_ujson.py:563]: Can you do the parametrization of a large negative value here too?

**Review by WillAyd — COMMENTED** [review]
Minor comments otherwise lgtm. @jreback

File: pandas/io/json/_json.py [hunk 46]
```diff
@@ -737,17 +722,11 @@ def read(self):
...
-                obj = concat(self)
-            elif self.nrows:
-                lines = list(islice(self.data, self.nrows))
-                lines_json = self._combine_lines(lines)
-                obj = self._get_object_parser(lines_json)
-            else:
-                data = ensure_str(self.data)
-                data = data.split("\n")
-                obj = self._get_object_parser(self._combine_lines(data))
+        if self.lines and self.chunksize:
```
Comment (WillAyd) [inline pandas/io/json/_json.py:725]: I think you might have an issue merging master - none of this should have changed

Comment (arw2019) [reply pandas/io/json/_json.py]: Yeah. Fixed now

File: pandas/tests/io/json/test_ujson.py [hunk 47]
```diff
@@ -559,6 +560,16 @@ def test_encode_long_conversion(self):
         assert output == json.dumps(long_input)
         assert long_input == ujson.decode(output)
 
+    @pytest.mark.parametrize("bigNum", [sys.maxsize + 1, -(sys.maxsize + 1)])
```
Comment (WillAyd) [inline pandas/tests/io/json/test_ujson.py:563]:
```suggestion
    @pytest.mark.parametrize("bigNum", [sys.maxsize + 1, -(sys.maxsize + 2)])
```

To exceed the negative range would have to add 2

File: pandas/tests/io/json/test_pandas.py [hunk 48]
```diff
@@ -1242,6 +1243,21 @@ def test_read_jsonl_unicode_chars(self):
         expected = DataFrame([["foo\u201d", "bar"], ["foo", "bar"]], columns=["a", "b"])
         tm.assert_frame_equal(result, expected)
 
+    @pytest.mark.parametrize("bigNum", [sys.maxsize + 1, -(sys.maxsize + 1)])
```
Comment (WillAyd) [inline pandas/tests/io/json/test_pandas.py:1246]: same here

Comment (arw2019) [reply pandas/tests/io/json/test_pandas.py]: OK, fixed!

**Comment by arw2019** [comment]
So the CI build is failing, with this message:
```
1.07s$ ci/run_tests.sh
xvfb-run pytest -m "(not slow and not network and not clipboard)" -n auto --dist=loadfile -s --strict --durations=30 --junitxml=test-data.xml pandas
ImportError while loading conftest '/home/travis/build/pandas-dev/pandas/pandas/conftest.py'.
pandas/__init__.py:34: in <module>
    raise ImportError(
E   ImportError: C extension: 'dtypes' from partially initialized module 'pandas._libs.tslibs' (most likely due to a circular import) (/home/travis/build/pandas-dev/pandas/pandas/_libs/tslibs/__init__.py) not built. If you want to import pandas from the source directory, you may need to run 'python setup.py build_ext --inplace --force' to build the C extensions first.
The command "ci/run_tests.sh" exited with 4.
```
I feel like the problem could be these lines in `pandas/tests/io/json/test_pandas.py`:
```
        originalSeries = Series(bigNum, dtype=object, index=["articleId"])
```
```
        originalDataFrame = DataFrame(
            bigNum, dtype=object, index=["articleId"], columns=[0]
        )
```
since Travis is complaining about the `dtypes` extension...?

**Comment by WillAyd** [comment]
Can you merge master and repush? I don’t think that error is related to changes made here

File: pandas/tests/io/json/test_pandas.py [hunk 49]
```diff
@@ -1242,6 +1243,21 @@ def test_read_jsonl_unicode_chars(self):
         expected = DataFrame([["foo\u201d", "bar"], ["foo", "bar"]], columns=["a", "b"])
         tm.assert_frame_equal(result, expected)
 
+    @pytest.mark.parametrize("bigNum", [sys.maxsize + 1, -(sys.maxsize + 2)])
+    def test_to_json_large_numbers(self, bigNum):
+        # GH34473
+        originalSeries = Series(bigNum, dtype=object, index=["articleId"])
```
Comment (jreback) [inline pandas/tests/io/json/test_pandas.py:1249]: can you use series here (and just df below)

File: pandas/tests/io/json/test_ujson.py [hunk 50]
```diff
@@ -559,6 +560,16 @@ def test_encode_long_conversion(self):
...
         assert long_input == ujson.decode(output)
 
+    @pytest.mark.parametrize("bigNum", [sys.maxsize + 1, -(sys.maxsize + 2)])
+    def test_dumps_ints_larger_than_maxsize(self, bigNum):
+        # GH34395
+        bigNum = sys.maxsize + 1
+        encoding = ujson.encode(bigNum)
+
+        assert str(bigNum) == encoding
+        # ujson.loads to be fixed in the future
```
Comment (jreback) [inline pandas/tests/io/json/test_ujson.py:570]: is there an issue for this? don't leave in commented code, rather add an xfail test

**Review by jreback — CHANGES_REQUESTED** [review]
can you run the json perf tests to see if anything is affected. you may need to add some long ints there as well.

File: pandas/tests/io/json/test_pandas.py (hunk 49 above)
Comment (arw2019) [reply pandas/tests/io/json/test_pandas.py:1249]: sure!

File: pandas/tests/io/json/test_ujson.py (hunk 50 above)
Comment (arw2019) [reply pandas/tests/io/json/test_ujson.py]: added the test. Also added xfail tests for this in `test_pandas.py`.

**Comment by arw2019** [comment]
@jreback Benchmark results are attached.
[json_performance_benchmarks.txt](https://github.com/pandas-dev/pandas/files/4812015/json_performance_benchmarks.txt)

The ones which changed significantly are:
```
       before           after         ratio
     [7d0ee96f]       [9e1b95f7]
     <master>         <json-Overflow-long-int>
+         268±4ms         315±40ms     1.17  io.json.ToJSON.time_to_json('index', 'df_int_floats')
+         242±3ms          278±3ms     1.15  io.json.ToJSON.time_to_json('index', 'df_td_int_ts')
+        364±20ms         407±20ms     1.12  io.json.ToJSON.time_to_json_wide('split', 'df_int_floats')
-        706±30ms         606±10ms     0.86  io.json.ReadJSONLines.time_read_json_lines('int')

SOME BENCHMARKS HAVE CHANGED SIGNIFICANTLY.
```
I'm working on adding long int benchmarks.

File: asv_bench/benchmarks/io/json.py [hunk 51]
```diff
@@ -82,6 +84,7 @@ def setup(self, orient, frame):
         timedeltas = timedelta_range(start=1, periods=N, freq="s")
         datetimes = date_range(start=1, periods=N, freq="s")
         ints = np.random.randint(100000000, size=N)
+        longints = sys.maxsize * np.random.randint(100000000, size=N)
```
Comment (arw2019) [inline asv_bench/benchmarks/io/json.py:87]: @jreback Not sure where we want the `longints` to go - whether into `ints` or separately. I would think we also want to make sure we have both positive and negative long ints in there?

Comment (jreback) [reply asv_bench/benchmarks/io/json.py:87]: this prob fine

**Review by jreback — APPROVED** [review]

**Comment by jreback** [comment]
looks ok to me. @WillAyd when you are happy.

**Comment by WillAyd** [comment]
Thanks @arw2019 very nice PR

**Comment by arw2019** [comment]
Had a lot of fun doing this. @WillAyd @jreback  thanks so much for all the help!

#34984 is a follow-up PR to deal with the correspondent problem in `json.decode`
