### PR TITLE
BUG: handle negative overflow in Period conversion from timestamp

### LINKED ISSUE #63278: BUG: Period(distant_past_timestamp, freq="us")
### Reproducible Example

```python
ts = pd.Timestamp(pd.Timestamp.min.value, unit="us")

# i.e. Timestamp('-290308-12-21 19:59:05.224193')

per = pd.Period(ts, freq="us")

OverflowError: Overflow occurred at ../../pandas/_libs/src/vendored/numpy/datetime/np_datetime.c:458
Exception ignored in: 'pandas._libs.tslibs.period.get_period_ordinal'

>>> per
Period('1970-01-01 00:00:00.000000', 'us')
```

### PR DESCRIPTION
**Pull request by Alvaro-Kothe**
- [x] closes #63278 (Replace xxxx with the GitHub issue number)
- [x] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature
- [x] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).
- [ ] Added [type annotations](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#type-hints) to new arguments/methods/functions.
- [x] Added an entry in the latest `doc/source/whatsnew/vX.X.X.rst` file if fixing a bug or adding a new feature.
- [ ] If I used AI to develop this pull request, I prompted it to follow `AGENTS.md`.

### CODE REVIEW

File: pandas/_libs/src/vendored/numpy/datetime/np_datetime.c [hunk 1]
```diff
@@ -455,8 +455,20 @@ npy_datetime npy_datetimestruct_to_datetime(NPY_DATETIMEUNIT base,
...
+  const int64_t us_per_second = 1000000L;
+  const int64_t min_scalable_seconds = NPY_MIN_INT64 / us_per_second;
+  if (seconds < min_scalable_seconds) {
+    const int64_t seconds_below_threshold = seconds - min_scalable_seconds;
+    // split y = a * x + b, where a * x underflows into two parts.
+    // y = a * (x + k - k) + b = a * (x + k) + (b - a * k), where k > 0.
+    int64_t scaled_us = us_per_second * (seconds - seconds_below_threshold);
+    PD_CHECK_OVERFLOW(checked_add(us_per_second * seconds_below_threshold,
+                                  dts->us, &microseconds));
+    PD_CHECK_OVERFLOW(checked_add(scaled_us, microseconds, &microseconds));
```
Comment (mroeschke) [inline pandas/_libs/src/vendored/numpy/datetime/np_datetime.c:467]: Is there a test that can hit either of these overflow checks?

Comment (Alvaro-Kothe) [reply pandas/_libs/src/vendored/numpy/datetime/np_datetime.c:467]: The test that I created hits this branch, with `seconds_below_threshold = -1`. It uses the minimum possible timestamp built with microseconds resolution. One value below it is `NaT`, and above can't enter this branch.

I don't know, on the top of my head, how would I create a valid `datetimestruct` that provokes an overflow in this branch.

**Review by mroeschke — APPROVED** [review]

**Comment by mroeschke** [comment]
Thanks @Alvaro-Kothe

**Comment by jbrockmendel** [comment]
The microsecond case looks fixed, but im still getting errors in the millisecond case:

```
ts = Timestamp(Timestamp.min.value, unit="ms")

>>> pd.Period(ts, freq="ms")
  File "<stdin>", line 1, in <module>
OverflowError: Overflow occurred at ../../pandas/_libs/src/vendored/numpy/datetime/np_datetime.c:451
Period('1970-01-01 00:00:00.000', 'ms')
```

**Comment by Alvaro-Kothe** [comment]
@jbrockmendel Thanks for pointing that out. I created a patch for the millisecond case in #63609.
