### PR TITLE
BUG: handle overflow during exponent parsing in `read_csv`

### LINKED ISSUE #38794: BUG: read_csv (c engine, round_trip precision) platform inconsistency with large exponents
On OS X

```python
data = io.StringIO("data\n10E999")
pd.read_csv(data, engine="c", float_precision="round_trip")
```
gives
```
   data
0   inf
```
But on Linux this gives
```
     data
0  10E999
```
Is this expected for any reason?

### LINKED ISSUE #62617: BUG: incorrect string parsing leads to segfault
### Pandas version checks

- [x] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [ ] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.

### Reproducible Example

```python
import io
import pandas as pd
pd.read_csv(
    io.StringIO("data1,81e3104049863b72,data3"),
    names=["header1", "header2", "header3"]
)
```

### Issue Description

I tracked down a segfault to the provided snippet when parsing big raw CSVs. One of the values (here under "header2") is a hexadecimal 16-character string, and under some conditions, it cannot be parsed by the C engine, yielding a segfault. Pyarrow fails as well, but the Python engine succeeds.

I tested multiple variations of the issue (as illustrated by the examples below). My hypothesis is that the C engine tries to cast it as an integer written in scientific notation, but fails. I have not been able to pinpoint exactly the conditions in the time I spent debugging, and this is the only line that failed in the 35M lines that I parsed for this project.

The issue appears in the latest pandas version, but **not** in the main branch.

```python
import io

import pandas as pd

print("works (only 0-9 after e)")
pd.read_csv(
    io.StringIO("data1,81e310404986372,data3"),
    names=[
        "header1",
        "header2",
        "header3",
    ],
)

print("works (only 9 chars between e and b)")
pd.read_csv(
    io.StringIO("data1,81e310404986b72,data3"),
    names=[
        "header1",
        "header2",
        "header3",
    ],
)

print("works (casted to string)")
pd.read_csv(
    io.StringIO("data1,81e3104049863b72,data3"),
    names=[
        "header1",
        "header2",
        "header3",
    ],
    dtype={"header2": str},
)

print("segfault")
pd.read_csv(
    io.StringIO("data1,81e3104049863b72,data3"),
    names=[
        "header1",
        "header2",
        "header3",
    ],
)
```

### Expected Behavior

No segfault :)

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit                : 9c8bc3e55188c8aff37207a74f1dd144980b8874
python                : 3.12.10
python-bits           : 64
OS                    : Linux
OS-release            : 6.14.0-33-generic
Version               : #33~24.04.1-Ubuntu SMP PREEMPT_DYNAMIC Fri Sep 19 17:02:30 UTC 2
machine               : x86_64
processor             : 
byteorder             : little
LC_ALL                : None
LANG                  : en_US.UTF-8
LOCALE                : en_US.UTF-8

pandas                : 2.3.3
numpy                 : 1.26.4
pytz                  : 2025.2
dateutil              : 2.9.0.post0
pip                   : None
Cython                : None
sphinx                : None
IPython               : 9.6.0
adbc-driver-postgresql: None
adbc-driver-sqlite    : None
bs4                   : None
blosc                 : None
bottleneck            : None
dataframe-api-compat  : None
fastparquet           : None
fsspec                : 2025.9.0
html5lib              : None
hypothesis            : None
gcsfs                 : None
jinja2                : 3.1.6
lxml.etree            : None
matplotlib            : 3.10.6
numba                 : 0.62.1
numexpr               : None
odfpy                 : None
openpyxl              : 3.1.5
pandas_gbq            : None
psycopg2              : None
pymysql               : None
pyarrow               : 21.0.0
pyreadstat            : None
pytest                : 8.4.2
python-calamine       : None
pyxlsb                : None
s3fs                  : 2025.9.0
scipy                 : 1.16.2
sqlalchemy            : None
tables                : None
tabulate              : 0.9.0
xarray                : 2025.9.1
xlrd                  : None
xlsxwriter            : None
zstandard             : None
tzdata                : 2025.2
qtpy                  : None
pyqt5                 : None

</details>

### PR DESCRIPTION
**Pull request by Alvaro-Kothe**
- [x] closes #62617
- [x] closes #38794
- [x] closes #62740
- [x] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature
- [x] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).
- [ ] Added [type annotations](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#type-hints) to new arguments/methods/functions.
- [x] Added an entry in the latest `doc/source/whatsnew/vX.X.X.rst` file if fixing a bug or adding a new feature.

---

This patch uses `strtol` to compute the exponent and checks overflow by the `errno` assigned on `strtol` and with `checked_add`.

I deleted the previous tests regarding large exponents because they were validating the undefined behavior caused by the overflow, where in one test asserts that `10E-99999999999999999` is parsed as `0.0`, while on the other `10E-999999999999999999` (contains 1 digit more) is parsed as a string.

Now, the float parsing on overflow follows the results from `pyarrow`.

### CODE REVIEW

File: pandas/_libs/src/parser/tokenizer.c [hunk 1]
```diff
@@ -1671,39 +1671,26 @@ double precise_xstrtod(const char *str, char **endptr, char decimal, char sci,
...
 
-    // Process string of digits.
-    num_digits = 0;
-    int n = 0;
-    while (num_digits < max_digits && isdigit_ascii(*p)) {
-      n = n * 10 + (*p - '0');
-      num_digits++;
-      p++;
-    }
+    char *tmp_ptr;
```
Comment (WillAyd) [inline pandas/_libs/src/parser/tokenizer.c:1677]: I think this is an address violation. Declaring a `char *` doesn't necessarily provide you with any storage to write into

**Review by WillAyd — CHANGES_REQUESTED** [review]

File: pandas/_libs/src/parser/tokenizer.c (hunk 1 above)
Comment (Alvaro-Kothe) [reply pandas/_libs/src/parser/tokenizer.c:1677]: But I don't write into it. I created this variable just to know how much the pointer moved in relation to `p`. Basically to get an equivalent of

```c
num_digits++;
p++;
```

Comment (WillAyd) [reply pandas/_libs/src/parser/tokenizer.c:1677]: Ah my mistake - I misread that. Thanks for clarifying

**Review by WillAyd — APPROVED** [review]

**Comment by WillAyd** [comment]
Great thanks @Alvaro-Kothe
