### PR TITLE
CI: Check ASV for failed benchmarks

### LINKED ISSUE #19518: asv ImportError
#### Code Sample, a copy-pastable example if possible
Clone and build pandas-dev, then from `pandas/asv_bench` do
```
asv continuous -f 1.1  upstream/master
```

#### Problem description

This yields an `ImportError` on my machine:
```
File "/pandas/asv_bench/benchmarks/gil.py", line 3, in <module>
from pandas import (DataFrame, Series, rolling_median, rolling_mean,
ImportError: cannot import name 'rolling_median'
```

Full stacktrace:

```
$ asv continuous -f 1.1  upstream/master 
· Creating environments
· Discovering benchmarks
·· Uninstalling from conda-py3.6-Cython-matplotlib-numexpr-numpy-openpyxl-pytables-pytest-scipy-sqlalchemy-xlrd-xlsxwriter-xlwt.
·· Building 3597de0a for conda-py3.6-Cython-matplotlib-numexpr-numpy-openpyxl-pytables-pytest-scipy-sqlalchemy-xlrd-xlsxwriter-xlwt.....................................................................
·· Installing into conda-py3.6-Cython-matplotlib-numexpr-numpy-openpyxl-pytables-pytest-scipy-sqlalchemy-xlrd-xlsxwriter-xlwt..
·· Error running /Users/joerg/Documents/Github/pandas/asv_bench/env/83b3be1235aa7b08e8a17448e2f70790/bin/python /Users/joerg/anaconda3/lib/python3.5/site-packages/asv/benchmark.py discover /Users/joerg/Documents/Github/pandas/asv_bench/benchmarks /var/folders/27/qrg706z54l76vk7t__l43h140000gn/T/tmp6ldll0ln
             STDOUT -------->

             STDERR -------->
             Traceback (most recent call last):
               File "/Users/joerg/anaconda3/lib/python3.5/site-packages/asv/benchmark.py", line 867, in <module>
                 commands[mode](args)
               File "/Users/joerg/anaconda3/lib/python3.5/site-packages/asv/benchmark.py", line 812, in main_discover
                 list_benchmarks(benchmark_dir, fp)
               File "/Users/joerg/anaconda3/lib/python3.5/site-packages/asv/benchmark.py", line 797, in list_benchmarks
                 for benchmark in disc_benchmarks(root):
               File "/Users/joerg/anaconda3/lib/python3.5/site-packages/asv/benchmark.py", line 696, in disc_benchmarks
                 for module in disc_files(root, os.path.basename(root) + '.'):
               File "/Users/joerg/anaconda3/lib/python3.5/site-packages/asv/benchmark.py", line 648, in disc_files
                 module = import_module(package + filename)
               File "/Users/joerg/Documents/Github/pandas/asv_bench/env/83b3be1235aa7b08e8a17448e2f70790/lib/python3.6/importlib/__init__.py", line 126, in import_module
                 return _bootstrap._gcd_import(name[level:], package, level)
               File "<frozen importlib._bootstrap>", line 994, in _gcd_import
               File "<frozen importlib._bootstrap>", line 971, in _find_and_load
               File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
               File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
               File "<frozen importlib._bootstrap_external>", line 678, in exec_module
               File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
               File "/Users/joerg/Documents/Github/pandas/asv_bench/benchmarks/gil.py", line 3, in <module>
                 from pandas import (DataFrame, Series, rolling_median, rolling_mean,
             ImportError: cannot import name 'rolling_median'
Traceback (most recent call last):
  File "/Users/joerg/anaconda3/bin/asv", line 11, in <module>
    load_entry_point('asv==0.3.dev1214+4112e36d', 'console_scripts', 'asv')()
  File "/Users/joerg/anaconda3/lib/python3.5/site-packages/asv/main.py", line 38, in main
    result = args.func(args)
  File "/Users/joerg/anaconda3/lib/python3.5/site-packages/asv/commands/__init__.py", line 48, in run_from_args
    return cls.run_from_conf_args(conf, args)
  File "/Users/joerg/anaconda3/lib/python3.5/site-packages/asv/commands/continuous.py", line 61, in run_from_conf_args
    quick=args.quick, **kwargs
  File "/Users/joerg/anaconda3/lib/python3.5/site-packages/asv/commands/continuous.py", line 86, in run
    _returns=run_objs, _machine_file=_machine_file)
  File "/Users/joerg/anaconda3/lib/python3.5/site-packages/asv/commands/run.py", line 192, in run
    commit_hashes, regex=bench)
  File "/Users/joerg/anaconda3/lib/python3.5/site-packages/asv/benchmarks.py", line 369, in discover
    benchmarks = cls._disc_benchmarks(conf, repo, environments, commit_hash)
  File "/Users/joerg/anaconda3/lib/python3.5/site-packages/asv/benchmarks.py", line 417, in _disc_benchmarks
    dots=False)
  File "/Users/joerg/anaconda3/lib/python3.5/site-packages/asv/plugins/conda.py", line 169, in run
    return self.run_executable('python', args, **kwargs)
  File "/Users/joerg/anaconda3/lib/python3.5/site-packages/asv/plugins/conda.py", line 175, in run_executable
    return super(Conda, self).run_executable(executable, args, **kwargs)
  File "/Users/joerg/anaconda3/lib/python3.5/site-packages/asv/environment.py", line 573, in run_executable
    return util.check_output([exe] + args, **kwargs)
  File "/Users/joerg/anaconda3/lib/python3.5/site-packages/asv/util.py", line 590, in check_output
    raise ProcessError(args, retcode, stdout, stderr)
asv.util.ProcessError: Command '/Users/joerg/Documents/Github/pandas/asv_bench/env/83b3be1235aa7b08e8a17448e2f70790/bin/python /Users/joerg/anaconda3/lib/python3.5/site-packages/asv/benchmark.py discover /Users/joerg/Documents/Github/pandas/asv_bench/benchmarks /var/folders/27/qrg706z54l76vk7t__l43h140000gn/T/tmp6ldll0ln' returned non-zero exit status 1
```

### PR DESCRIPTION
**Pull request by mroeschke**
closes #19518

xref #19104

Not sure if this should belong in `ci/lint.sh`, but testing the possibility of running the asv benchmarks on ci for failed benchmarks.

### CODE REVIEW

File: ci/lint.sh [hunk 1]
```diff
@@ -125,6 +125,16 @@ if [ "$LINT" ]; then
         RET=1
     fi
     echo "Check for deprecated messages without sphinx directive DONE"
+
```
Comment (jreback) [inline ci/lint.sh]: put this in a separete script (ci/asv.sh)

and we can enable it in (.travis.yml) via an ENV variable (e.g. like we do for coverage).

Then its easy to put it on only 1 build.

also need to install asv (on that build)

**Comment by mroeschke** [comment]
Created `asv.sh`. I'm not too familiar where to enable the script in `travis.yml`.

**Comment by jreback** [comment]
I pushed a commit to add this to travis. let's see what it does.

**Comment by mroeschke** [comment]
Hmm so the builds are returning `/home/travis/.travis/job_stages: line 57: ci/asv.sh: Permission denied`

Do I need to check in the file with execution permissions? https://stackoverflow.com/a/42187039

**Comment by jreback** [comment]
it should be chmod 755

**Comment by mroeschke** [comment]
Looks like travis is all green.

File: ci/asv.sh [hunk 2]
```diff
@@ -0,0 +1,24 @@
...
+    cd asv_bench
+
+    time asv run --quick | grep "failed"
+
+    if [ $? = "0" ]; then
+        RET=1
+    fi
+    echo "Check for failed asv benchmarks DONE"
+fi
+
```
Comment (jreback) [inline ci/asv.sh]: can you add an else like we do in lint. so that we get a message if this is NOT run.

**Comment by jreback** [comment]
I am not convinced this actually did anything. sure it installed but it doesn't say it even ran. 
```
23.33s$ ci/asv.sh
inside ci/asv.sh
Check for failed asv benchmarks
Collecting git+https://github.com/spacetelescope/asv
  Cloning https://github.com/spacetelescope/asv to /tmp/pip-Dzkkcb-build
Requirement already satisfied: six>=1.4 in /home/travis/miniconda3/envs/pandas/lib/python2.7/site-packages (from asv==0.3.dev1207+7edf1903)
Installing collected packages: asv
  Running setup.py install for asv ... done
Successfully installed asv-0.3.dev1207+7edf1903
real	0m0.410s
user	0m0.361s
sys	0m0.048s
Check for failed asv benchmarks DONE
```

File: ci/asv.sh (hunk 2 above)
Comment (jreback) [inline ci/asv.sh]: can you add an else like we do in lint. so that we get a message if this is NOT run.

**Review by jreback — CHANGES_REQUESTED** [review]

File: ci/asv.sh [hunk 3]
```diff
@@ -0,0 +1,24 @@
...
+RET=0
+
+if [ "$ASV" ]; then
+    echo "Check for failed asv benchmarks"
+
+    pip install git+https://github.com/spacetelescope/asv
+
+    cd asv_bench
+
+    time asv run --quick | grep "failed"
```
Comment (jreback) [inline ci/asv.sh]: once we are convinced these run, then can add it back

**Comment by jreback** [comment]
here was a run on my local system
```
real    21m8.666s
user    18m20.882s
sys     2m47.438s
```

so for sure this has to be a separate build.

**Comment by mroeschke** [comment]
Added the else statement. I also _think_ this may not be working because asv wants to know the machine configurations upon install, so I added an `asv machine --yes` statement.

**Comment by mroeschke** [comment]
Here's the latest output:

```
$ ci/asv.sh
inside ci/asv.sh
Check for failed asv benchmarks
Collecting git+https://github.com/spacetelescope/asv
  Cloning https://github.com/spacetelescope/asv to /tmp/pip-eJJWMU-build
Requirement already satisfied: six>=1.4 in /home/travis/miniconda3/envs/pandas/lib/python2.7/site-packages (from asv==0.3.dev1207+7edf1903)
Installing collected packages: asv
  Running setup.py install for asv ... done
Successfully installed asv-0.3.dev1207+7edf1903
· No information stored about machine 'travis-job-pandas-dev-pandas-329321549.travisci.net'. I know about nothing.
            
I will now ask you some questions about this machine to identify it in the benchmarks.
1. machine:  A unique name to identify this machine in the results.
   May be anything, as long as it is unique across all the machines
   used to benchmark this project.  NOTE: If changed from the default,
   it will no longer match the hostname of this machine, and you may
   need to explicitly use the --machine argument to asv.
machine [travis-job-pandas-dev-pandas-329321549.travisci.net]: 2. os:  The OS type and version of this machine.  For example,
   'Macintosh OS-X 10.8'.
os [Linux 4.14.12-041412-generic]: 3. arch:  The generic CPU architecture of this machine.  For example,
   'i386' or 'x86_64'.
arch [x86_64]: 4. cpu:  A specific description of the CPU of this machine, including
   its speed and class.  For example, 'Intel(R) Core(TM) i5-2520M CPU
   @ 2.50GHz (4 cores)'.
cpu [Intel(R) Xeon(R) CPU E5-2680 v2 @ 2.80GHz]: 5. ram:  The amount of physical RAM on this machine.  For example,
   '4GB'.
ram [61815180]: 
No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
Check the details on how to adjust your build configuration on: https://docs.travis-ci.com/user/common-build-problems/#Build-times-out-because-no-output-was-received
The build has been terminated
```

So it appears travis is running the build, but it thinks that there's a build issue because the ASV benchmarks take a while to run.

**Comment by jreback** [comment]
ok I pushed to a separate build. if this works, then we would simply capture the output (as well as output to the screen). then grep it. you have to keep showing output otherwise things will timeout.

**Comment by mroeschke** [comment]
Thanks @jreback 

It looks like the alternative is to prefix the asv script execution with `- travis_wait 30 ci/asv.sh` to tell travis to wait for 30 minutes, or more if needed. 

https://docs.travis-ci.com/user/common-build-problems/#Build-times-out-because-no-output-was-received

**Comment by mroeschke** [comment]
Darn, looks like the build is taking to long. It ran for 49 min 57 sec and output:

`The job exceeded the maximum time limit for jobs, and has been terminated.`

Looks like the max time for travis-ci.org jobs is 50 minutes. 

https://docs.travis-ci.com/user/customizing-the-build#Build-Timeouts

**Comment by jreback** [comment]
i restarted that job again, i think this should complete

**Comment by mroeschke** [comment]
Looks like the job hit the time limit again.

It looks like `ci/install_travis.sh` itself took ~11 minutes. I'm not sure if there anything in this script that can be skipped to allow more time for the asv script

File: ci/asv.sh [hunk 4]
```diff
@@ -9,13 +9,11 @@ RET=0
...
     echo "Check for failed asv benchmarks"
 
-    pip install git+https://github.com/spacetelescope/asv
-
     cd asv_bench
 
     asv machine --yes
 
-    time asv run --quick | grep "failed"
+    time asv run --quick
```
Comment (jorisvandenbossche) [inline ci/asv.sh]: Not directly related to this change (rather to the previous PR that introduced this), but shouldn't this be `asv dev` ? Because I thought `asv run` would create a new env, while everything already has been installed on travis?

File: .travis.yml [hunk 5]
```diff
@@ -76,6 +76,10 @@ matrix:
     - dist: trusty
       env:
         - JOB="3.6_DOC" DOC=true
+    # In allow_failures
+    - dist: trusty
+      env:
+        - JOB="3.6_ASV" ASV=true
```
Comment (jorisvandenbossche) [inline .travis.yml]: Could you put this just before the docs build? (I think I will more refer to the doc build, and then it is easier to say the last build :-))

File: ci/asv.sh (hunk 4 above)
Comment (mroeschke) [reply ci/asv.sh]: The link below mentions about `asv dev`

```
This runs a benchmark suite in a mode that is useful during development. It is
equivalent to ``asv run --quick --show-stderr --python=same``
```
So the command should be essentially the same `asv dev`, but I can still change it to `asv dev` nonetheless.


Ref: https://asv.readthedocs.io/en/latest/commands.html#asv-dev

Comment (jorisvandenbossche) [reply ci/asv.sh]: There is an essential difference between what you quote (`asv run --quick --show-stderr --python=same`) and what is above, namely the `--python=same`.

And I also think `--show-stderr` is useful for on travis, to be able to easier see what is failing.

**Comment by jreback** [comment]
I would not grep for the output yet, this obscure the progress; let's see how far it gets.

**Comment by mroeschke** [comment]
@jreback Looks like the build ran the asv within the time limit:

```
real	36m57.758s
user	32m53.399s
sys	3m42.420s
Check for failed asv benchmarks DONE
```
I will move forward with greping the output if all looks good.

**Comment by jreback** [comment]
what changed to make this work?

**Comment by mroeschke** [comment]
I think the change from `asv run` to `asv dev` made this work before.

**Comment by mroeschke** [comment]
After adding a grep, received

```
No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
Check the details on how to adjust your build configuration on: https://docs.travis-ci.com/user/common-build-problems/#Build-times-out-because-no-output-was-received
```

Will now be adding a travis wait

**Comment by mroeschke** [comment]
So I think it works now? I guess I could also intentionally make one of the benchmarks wrong to see if this fails. Would appreciate a second look @jreback 

From the build:

```
$ travis_wait 40 ci/asv.sh
Still running (33 of 40): ci/asv.sh
The command ci/asv.sh exited with 0.
Log:
inside ci/asv.sh
Check for failed asv benchmarks
· No information stored about machine 'travis-job-pandas-dev-pandas-333531431.travisci.net'. I know about nothing.
            
I will now ask you some questions about this machine to identify it in the benchmarks.
1. machine:  A unique name to identify this machine in the results.
   May be anything, as long as it is unique across all the machines
   used to benchmark this project.  NOTE: If changed from the default,
   it will no longer match the hostname of this machine, and you may
   need to explicitly use the --machine argument to asv.
machine [travis-job-pandas-dev-pandas-333531431.travisci.net]: 2. os:  The OS type and version of this machine.  For example,
   'Macintosh OS-X 10.8'.
os [Linux 4.14.12-041412-generic]: 3. arch:  The generic CPU architecture of this machine.  For example,
   'i386' or 'x86_64'.
arch [x86_64]: 4. cpu:  A specific description of the CPU of this machine, including
   its speed and class.  For example, 'Intel(R) Core(TM) i5-2520M CPU
   @ 2.50GHz (4 cores)'.
cpu [Intel(R) Xeon(R) CPU E5-2680 v2 @ 2.80GHz]: 5. ram:  The amount of physical RAM on this machine.  For example,
   '4GB'.
ram [61815180]: 
real	32m40.209s
user	29m11.933s
sys	3m24.802s
Check for failed asv benchmarks DONE
/home/travis/.travis/job_stages: line 169:  4585 Terminated              travis_jigger $! $timeout $cmd
The command "travis_wait 40 ci/asv.sh" exited with 0.
```

File: .travis.yml [hunk 6]
```diff
@@ -73,6 +73,10 @@ matrix:
       env:
         - JOB="3.6_NUMPY_DEV" TEST_ARGS="--skip-slow --skip-network" PANDAS_TESTING_MODE="deprecate"
     # In allow_failures
+    - dist: trusty
```
Comment (jreback) [inline .travis.yml]: move this after the doc build

File: .travis.yml [hunk 7]
```diff
@@ -93,6 +97,9 @@ matrix:
       - dist: trusty
         env:
           - JOB="3.6_NUMPY_DEV" TEST_ARGS="--skip-slow --skip-network" PANDAS_TESTING_MODE="deprecate"
+      - dist: trusty
```
Comment (jreback) [inline .travis.yml]: same here

File: ci/asv.sh [hunk 8]
```diff
@@ -0,0 +1,27 @@
...
+
+if [ "$ASV" ]; then
+    echo "Check for failed asv benchmarks"
+
+    cd asv_bench
+
+    asv machine --yes
+
+	RET=0
+
```
Comment (jreback) [inline ci/asv.sh]: i would tee here; i like the output to the terminal

**Review by jreback — CHANGES_REQUESTED** [review]

File: .travis.yml (hunk 6 above)
Comment (mroeschke) [reply .travis.yml]: @jorisvandenbossche prefered this before the doc build

https://github.com/pandas-dev/pandas/pull/19236#discussion_r162569822

File: .travis.yml (hunk 7 above)
Comment (mroeschke) [reply .travis.yml]: @jorisvandenbossche prefered this before the doc build

https://github.com/pandas-dev/pandas/pull/19236#discussion_r162569822

**Comment by mroeschke** [comment]
@jreback Okay I think this works now. The build failure for #35124.4 is unrelated.

**Comment by jreback** [comment]
looking good. a couple of things.

1) would catch future warnings for most things (you can use ``catch_warnings`` so its generic) as these are distracting
2) would tee to a file of the failed to a tmp file, then cat it at the end (and put some echos around this to make it prominent). So that we can see what exactly failed.

**Comment by mroeschke** [comment]
Warnings have been caught and now checking failed benchmarks through a file, `failed_asv.txt`

```
...
[100.00%] ··· Running ...a.TimedeltaProperties.time_timedelta_seconds     4.20μs
real	33m10.909s
user	29m41.485s
sys	3m37.056s
The following asvs benchmarks (if any) failed.
DONE displaying failed asvs benchmarks.
Check for failed asv benchmarks DONE
```

**Comment by jorisvandenbossche** [comment]
@mroeschke If it is not too difficult, can you do the clean-up of the benchmarks for rolling in a separate PR?

File: asv_bench/benchmarks/gil.py [hunk 9]
```diff
@@ -1,8 +1,6 @@
 import numpy as np
 import pandas.util.testing as tm
-from pandas import (DataFrame, Series, rolling_median, rolling_mean,
-                    rolling_min, rolling_max, rolling_var, rolling_skew,
-                    rolling_kurt, rolling_std, read_csv, factorize, date_range)
```
Comment (jorisvandenbossche) [inline asv_bench/benchmarks/gil.py]: I might be 'overhead' to keep, but we can also simply move those imports to withing the `else` statement, and then this keeps working for old releases.

**Comment by mroeschke** [comment]
@jorisvandenbossche Added back the rolling methods. Sorry I saw your other comment too late and squashed my commits where I made edits for the rolling methods. Is it still possible to cherry pick from a squashed commit?

**Comment by mroeschke** [comment]
Ping @jorisvandenbossche any additional feedback?

**Review by jreback — APPROVED** [review]

**Comment by jreback** [comment]
thanks @mroeschke 

let's see how this works. its the longest build, but ok for now.
