### PR TITLE
CI: Format isort output for azure

### LINKED ISSUE #27179: CI: Format isort output to be detected as Azure pipelines errors
`isort` is a tool to validate the order of the imports in Python code. We are using it in the CI to make sure all pandas imports follow a defined standard. It is implemented in `ci/code_checks.sh`.

When `isort` detects imports incorrectly sorted, it finishes with an exit code different than 0, and that makes the CI red. Besides that, it'd be useful that in Azure Pipelines (the CI system where `isort` runs) the output messages of `isort` were detected as errors.

Some tools provide an option to specify the output format, like `flake8`, but `isort` doesn't (see https://github.com/timothycrosley/isort/issues/961).

What we can do in this case is to modify the output with bash pipelines. We are already doing that in the `invgrep` function in `ci/code_checks.sh`.

What needs to be done is:
- Change the format of `isort` output to be: `##vso[task.logissue type=error;sourcepath=%(path)s]%(text)s"
- Make sure that the resulting command still has an exit code of `0` if no issues are found, and the exit code of `isort` is there are. e.g. the exit code of `isort -c foo.py | awk -F" " '{ print $2 }'` is 0, the exit code of `awk` even if errors are found (the exit code of `isort` is lost in the pipeline).

Note that the error message of `isort` is not delimited in a way that can be easily parsed. But since the error message does not change, it should be possible to extract the name of the file removing the number of characters of the text around it (see https://github.com/timothycrosley/isort/blob/develop/isort/isort.py#L122).

### PR DESCRIPTION
**Pull request by alimcmaster1**
- [x] closes #27179
- [x] tests added / passed
- [x] passes `black pandas`
- [x] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`

Current behaviour on master of isort formatting:
image

Finishing up stale PR @https://github.com/pandas-dev/pandas/pull/27334

### CODE REVIEW

**Review by WillAyd — APPROVED** [review]
lgtm

Thanks for picking this up! FYI for smaller changes we *typically* try to push to the original contributors branch so they get credit (I use `hub` to do this). By no means required just something to consider

@datapythonista @jbrockmendel if you care to look

File: ci/code_checks.sh [hunk 1]
```diff
@@ -109,7 +109,13 @@ if [[ -z "$CHECK" || "$CHECK" == "lint" ]]; then
 
     # Imports - Check formatting using isort see setup.cfg for settings
     MSG='Check import format using isort ' ; echo $MSG
-    isort --recursive --check-only pandas asv_bench
+    set -o pipefail
```
Comment (datapythonista) [inline ci/code_checks.sh]: I think you should disable when it's not needed anymore. Otherwise things in other part of the script can fail, and this is not expected to be active by default.

File: ci/code_checks.sh [hunk 2]
```diff
@@ -109,7 +109,13 @@ if [[ -z "$CHECK" || "$CHECK" == "lint" ]]; then
...
+    isort_cmd="isort --recursive --check-only pandas asv_bench"
```
Comment (datapythonista) [inline ci/code_checks.sh]: I think the convention is to have environment variables in bash in upper case.

File: ci/code_checks.sh [hunk 3]
```diff
@@ -109,7 +109,13 @@ if [[ -z "$CHECK" || "$CHECK" == "lint" ]]; then
...
+    if [[ "$AZURE" == "true" ]]; then
+         eval $isort_cmd | awk '{ORS=""} {print "##vso[task.logissue type=error;sourcepath="$2";]"} {$1=$2=""; print $0}'
+    else
+        eval $isort_cmd
```
Comment (datapythonista) [inline ci/code_checks.sh]: This indentation doesn't much the previous eval.

File: ci/code_checks.sh [hunk 4]
```diff
@@ -109,7 +109,13 @@ if [[ -z "$CHECK" || "$CHECK" == "lint" ]]; then
 
     # Imports - Check formatting using isort see setup.cfg for settings
     MSG='Check import format using isort ' ; echo $MSG
-    isort --recursive --check-only pandas asv_bench
+    set -o pipefail
+    isort_cmd="isort --recursive --check-only pandas asv_bench"
+    if [[ "$AZURE" == "true" ]]; then
+         eval $isort_cmd | awk '{ORS=""} {print "##vso[task.logissue type=error;sourcepath="$2";]"} {$1=$2=""; print $0}'
```
Comment (datapythonista) [inline ci/code_checks.sh]: Just an opinion, but I'd personally prefer something like:
```bash
if [[ "$AZURE" == "true" ]]; then
    FORMAT_ISORT="awk '{ORS=""} {print "##vso[task.logissue type=error;sourcepath="$2";]"} {$1=$2=""; print $0}'"
else
    FORMAT_ISORT="cat"
fi
isort --recursive --check-only pandas asv_bench | eval $FORMAT_ISORT
```
Not a huge difference, but I think it makes more clear what's going on, since the line that actually does things is just one, shorter, and more explicit on what it does

**Review by datapythonista — COMMENTED** [review]
Good stuff. Some minor stylistic comments, but looks good.

I think the error in the CI is missing some space that you may want to add in the awk expression too.

@WillAyd, I don't think @alimcmaster1 has got the permissions to push to other people PRs. @alimcmaster1 you can still give credits by adding co-authors to you commits I think. I don't remember the syntax, and it's not important. Just in case you think it's worth the research (probably not).

**Comment by alimcmaster1** [comment]
Since we are now using Github Actions ill update this.

Before this change output is:
image

**Comment by alimcmaster1** [comment]
Output now looks better - but I need to fix the return code 
image

File: ci/code_checks.sh [hunk 5]
```diff
@@ -105,7 +105,12 @@ if [[ -z "$CHECK" || "$CHECK" == "lint" ]]; then
 
     # Imports - Check formatting using isort see setup.cfg for settings
     MSG='Check import format using isort ' ; echo $MSG
-    isort --recursive --check-only pandas asv_bench
+    ISORT_CMD="isort --recursive --check-only pandas asv_bench"
+    if [[ "$GITHUB_ACTIONS" == "true" ]]; then
+         eval $ISORT_CMD | awk '{print "##[error]" $0}'
```
Comment (datapythonista) [inline ci/code_checks.sh]:
```suggestion
         eval $ISORT_CMD | awk '{print "##[error]" $0}' ; $?=${PIPESTATUS[0]}
```

Not sure if you can do something like this, or similar, but this will consider the return of `awk` to fail the CI, and will always be 0.

File: ci/code_checks.sh [hunk 6]
```diff
@@ -105,7 +105,12 @@ if [[ -z "$CHECK" || "$CHECK" == "lint" ]]; then
 
     # Imports - Check formatting using isort see setup.cfg for settings
     MSG='Check import format using isort ' ; echo $MSG
-    isort --recursive --check-only pandas asv_bench
+    ISORT_CMD="isort --recursive --check-only pandas asv_bench"
+    if [[ "$GITHUB_ACTIONS" == "true" ]]; then
+        eval $ISORT_CMD | awk '{print "##[error]" $0}'; $?=${PIPESTATUS[0]}
```
Comment (datapythonista) [inline ci/code_checks.sh]:
```suggestion
        eval $ISORT_CMD | awk '{print "##[error]" $0}'; RET=$(($RET + ${PIPESTATUS[0]}))
```
Assigning to `$?` doesn't seem to work. I think the above is my preferred option. `$RET` will be increased twice, one with 0, the result of the assignment, which feels a bit hacky. But I think other options will make the code more complicated, and the result of the proposed solution should always be correct.

**Review by datapythonista — APPROVED** [review]
lgtm, happy to get this merged once you restore the import order

File: ci/code_checks.sh (hunk 5 above)
Comment (alimcmaster1) [reply ci/code_checks.sh]: Thanks for this v. handy

**Comment by alimcmaster1** [comment]
Related failures: https://github.com/pandas-dev/pandas/issues/30031

**Comment by alimcmaster1** [comment]
CI finally passed. @datapythonista @WillAyd to merge

**Comment by alimcmaster1** [comment]
Thanks @WillAyd
