### PR TITLE
BUG: Don't over-optimize memory with jagged CSV

### LINKED ISSUE #23509: C error: Buffer overflow caught on CSV with chunksize
#### Code Sample

This will create the error, but it is slow. I recommend [downloading the file directly](https://github.com/pandas-dev/pandas/files/2548189/debug.txt). 

```python
import pandas
filename = 'https://github.com/pandas-dev/pandas/files/2548189/debug.txt'
for chunk in pandas.read_csv(filename, chunksize=1000, names=range(2504)):
    pass
```

#### Problem description

I get the following exception only while using the C engine. This is similar to https://github.com/pandas-dev/pandas/issues/11166.

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "D:\programs\anaconda3\lib\site-packages\pandas\io\parsers.py", line 1007, in __next__
    return self.get_chunk()
  File "D:\programs\anaconda3\lib\site-packages\pandas\io\parsers.py", line 1070, in get_chunk
    return self.read(nrows=size)
  File "D:\programs\anaconda3\lib\site-packages\pandas\io\parsers.py", line 1036, in read
    ret = self._engine.read(nrows)
  File "D:\programs\anaconda3\lib\site-packages\pandas\io\parsers.py", line 1848, in read
    data = self._reader.read(nrows)
  File "pandas\_libs\parsers.pyx", line 876, in pandas._libs.parsers.TextReader.read
  File "pandas\_libs\parsers.pyx", line 903, in pandas._libs.parsers.TextReader._read_low_memory
  File "pandas\_libs\parsers.pyx", line 945, in pandas._libs.parsers.TextReader._read_rows
  File "pandas\_libs\parsers.pyx", line 932, in pandas._libs.parsers.TextReader._tokenize_rows
  File "pandas\_libs\parsers.pyx", line 2112, in pandas._libs.parsers.raise_parser_error
pandas.errors.ParserError: Error tokenizing data. C error: Buffer overflow caught - possible malformed input file.
```

#### Expected Output

None. It should just loop through the file.

#### Output of ``pd.show_versions()``

Both machines exhibit the exception.

<details>
<summary>RedHat</summary>

```
INSTALLED VERSIONS
------------------
commit: None
python: 3.6.6.final.0
python-bits: 64
OS: Linux
OS-release: 3.10.0-862.14.4.el7.x86_64
machine: x86_64
processor: x86_64
byteorder: little
LC_ALL: None
LANG: en_US.UTF-8
LOCALE: en_US.UTF-8

pandas: 0.23.4
pytest: None
pip: 18.1
setuptools: 39.1.0
Cython: 0.29
numpy: 1.15.3
scipy: 1.1.0
pyarrow: None
xarray: None
IPython: None
sphinx: None
patsy: None
dateutil: 2.7.3
pytz: 2018.5
blosc: None
bottleneck: None
tables: None
numexpr: None
feather: None
matplotlib: 3.0.0
openpyxl: None
xlrd: None
xlwt: None
xlsxwriter: None
lxml: None
bs4: None
html5lib: None
sqlalchemy: None
pymysql: None
psycopg2: None
jinja2: None
s3fs: None
fastparquet: None
pandas_gbq: None
pandas_datareader: None
```
</details>

<details>
<summary>Windows 7</summary>

```
INSTALLED VERSIONS
------------------
commit: None
python: 3.6.5.final.0
python-bits: 64
OS: Windows
OS-release: 7
machine: AMD64
processor: Intel64 Family 6 Model 58 Stepping 9, GenuineIntel
byteorder: little
LC_ALL: None
LANG: None
LOCALE: None.None

pandas: 0.23.0
pytest: 3.5.1
pip: 18.1
setuptools: 39.1.0
Cython: 0.28.2
numpy: 1.14.3
scipy: 1.1.0
pyarrow: None
xarray: None
IPython: 6.4.0
sphinx: 1.7.4
patsy: 0.5.0
dateutil: 2.7.3
pytz: 2018.4
blosc: None
bottleneck: 1.2.1
tables: 3.4.3
numexpr: 2.6.5
feather: None
matplotlib: 2.2.2
openpyxl: 2.5.3
xlrd: 1.1.0
xlwt: 1.3.0
xlsxwriter: 1.0.4
lxml: 4.2.1
bs4: 4.6.0
html5lib: 1.0.1
sqlalchemy: 1.2.7
pymysql: None
psycopg2: None
jinja2: 2.10
s3fs: None
fastparquet: None
pandas_gbq: None
pandas_datareader: None
```
</details>

### PR DESCRIPTION
**Pull request by gfyoung**
With jagged CSV's, we risk being too quick to dump memory that we need to allocate because previous chunks would have indicated much larger rows than we can anticipate in subsequent chunks.

Closes #23509.

### CODE REVIEW

**Comment by gfyoung** [comment]
@jreback : Any thoughts on this one?

**Comment by jreback** [comment]
can you run the current benchmarks on this. do we have any that specifically target this?

**Comment by gfyoung** [comment]
@jreback : No specific benchmarks as far as know, though I did not observe any meaningful changes to the benchmarks after making this change.

**Comment by gfyoung** [comment]
@jreback : Any other thoughts on this?

File: pandas/_libs/src/parser/tokenizer.c [hunk 1]
```diff
@@ -1241,6 +1249,10 @@ int parser_trim_buffers(parser_t *self) {
 
     int64_t i;
```
Comment (jreback) [inline pandas/_libs/src/parser/tokenizer.c]: can you add a comment here

File: pandas/_libs/src/parser/tokenizer.c [hunk 2]
```diff
@@ -287,8 +288,15 @@ static int make_stream_space(parser_t *self, size_t nbytes) {
     */
 
     cap = self->words_cap;
+
```
Comment (jreback) [inline pandas/_libs/src/parser/tokenizer.c]: can you add a comment here

**Review by jreback — CHANGES_REQUESTED** [review]
@gfyoung ok I reviewed the original issue. so lgtm. if you would add some comments on the parts you added for future readers should be great. ping on green.

File: pandas/_libs/src/parser/tokenizer.c (hunk 1 above)
Comment (gfyoung) [reply pandas/_libs/src/parser/tokenizer.c]: Yep, done.

File: pandas/_libs/src/parser/tokenizer.c (hunk 2 above)
Comment (gfyoung) [reply pandas/_libs/src/parser/tokenizer.c]: Yep, done.

**Comment by gfyoung** [comment]
@jreback : Addressed the doc comments, and all is still green.  PTAL.

**Review by jreback — APPROVED** [review]

**Comment by jreback** [comment]
thanks @gfyoung
