### PR TITLE
CI: increase codecov target - append ArrayManager tests coverage

### LINKED ISSUE #40670: CI: coverage dropped below target
The codecov CI is failing. My guess is the seperate AM test added in #40496 overwrites the coverage report.

### PR DESCRIPTION
**Pull request by jorisvandenbossche**
Attempt to close #40670

### CODE REVIEW

File: ci/run_tests.sh [hunk 1]
```diff
@@ -30,6 +30,11 @@ fi
 echo $PYTEST_CMD
 sh -c "$PYTEST_CMD"
 
+if [ "$COVERAGE" ]; then
```
Comment (jreback) [inline ci/run_tests.sh:33]: this is already above: https://github.com/pandas-dev/pandas/pull/40711/files#diff-fad2fa83c042cce646b2c1a0455e9b60c22dd5f105ed8859ce85dcf361c07fbdL12

Comment (jorisvandenbossche) [reply ci/run_tests.sh:33]: Yes, but this one is different. 

Now, maybe it can't hurt to add the `--cov-append` in all cases, though (so also for the first invocation)

Comment (jreback) [reply ci/run_tests.sh:33]: ok, but let's try to have a single invocation

Comment (jorisvandenbossche) [reply ci/run_tests.sh:33]: >  try to have a single invocation

There are two invocations, that's the point of also testing the ArrayManager
