### PR TITLE
BUG: Segfault in to_json with tzaware datetime

### LINKED ISSUE #42130: BUG: segfault from json.dumps in Python 3.10
The segfault is from `pandas/tests/io/json/test_pandas::TestPandasContainer::test_tz_is_utc` and  `pandas/tests/io/json/test_pandas::TestPandasContainer::test_tz_range_is_utc`

### PR DESCRIPTION
**Pull request by lithomas1**
- [ ] closes #42130
- [ ] tests added / passed
- [ ] Ensure all linting tests pass, see [here](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit) for how to run them
- [ ] whatsnew entry

Basically, timedelta.total_seconds returns a float. PyInt_AsLong(actually PyLong_AsLong) wants an int, but would cast using __int__ for Pythons < 3.10. This stopped happening in python 3.10. (https://docs.python.org/3/c-api/long.html#c.PyLong_AsLong). 

IMO, it probably is fine to cast the result from float to int, as I don't think that any timezone has an offset from UTC that contains fractions of a second. But, I could be wrong given that I don't use timezones and are not too familiar with them.

### CODE REVIEW

**Review by jreback — APPROVED** [review]
nice ping on greenish

**Review by jbrockmendel — APPROVED** [review]
LGTM

**Review by mroeschke — APPROVED** [review]

File: pandas/_libs/tslibs/src/datetime/np_datetime.c [hunk 1]
```diff
@@ -378,7 +378,7 @@ int convert_pydatetime_to_datetimestruct(PyObject *dtobj,
             if (tmp == NULL) {
                 return -1;
             }
-            seconds_offset = PyInt_AsLong(tmp);
+            seconds_offset = PyInt_AsLong(PyNumber_Long(tmp));
```
Comment (WillAyd) [inline pandas/_libs/tslibs/src/datetime/np_datetime.c:381]: PyNumber_Long returns a new reference, so the way this is currently written it will leak memory. You ideally should break this into a few lines and be sure to call Py_DECREF on the object returned from PyNumber_Long

While touching this might as well also switch from PyInt_AsLong to PyLong_AsLong

**Review by WillAyd — CHANGES_REQUESTED** [review]

File: pandas/_libs/tslibs/src/datetime/np_datetime.c [hunk 2]
```diff
@@ -378,11 +379,14 @@ int convert_pydatetime_to_datetimestruct(PyObject *dtobj,
             if (tmp == NULL) {
                 return -1;
             }
-            seconds_offset = PyInt_AsLong(tmp);
+            tmp_int = PyNumber_Long(tmp);
```
Comment (WillAyd) [inline pandas/_libs/tslibs/src/datetime/np_datetime.c:382]: You will also want to do a `if (tmp_int == NULL)` check and return an error / DECREF tmp if that happens. Otherwise lgtm

File: pandas/_libs/tslibs/src/datetime/np_datetime.c (hunk 1 above)
Comment (lithomas1) [reply pandas/_libs/tslibs/src/datetime/np_datetime.c]: > While touching this might as well also switch from PyInt_AsLong to PyLong_AsLong
Will try to do this as a follow up as I'm planning to have this PR backported.

**Review by WillAyd — APPROVED** [review]

**Comment by WillAyd** [comment]
Thanks @lithomas1 awesome work
