### PR TITLE
BLD: 3.6.1 ABI compat

### LINKED ISSUE #15961: FYI, if you build pandas release binaries with 3.6.1, they'll be broken on 3.6.0
As a heads up: https://bugs.python.org/issue29943

Two possible workarounds:
* Make sure to use 3.6.0 if building release binaries (this way they'll work on 3.6.1 as well)
* add a `#ifdef PySlice_GetIndicesEx  #undef PySlice_GetIndicesEx  #endif` to `pandas/_libs/src/compat_helper.h` (but make sure to only enable this on 3.6, or you'll eventually get broken again

### PR DESCRIPTION
**Pull request by chris-b1**
- [x] closes #15961
 - [ ] tests added / passed
 - [ ] passes ``git diff upstream/master --name-only -- '*.py' | flake8 --diff``
 - [ ] whatsnew entry

So I _think_ this works - locally was able to build a wheel with `3.6.1` and import it into a `3.6.0` environment, which was failing before this patch.

### CODE REVIEW

File: pandas/_libs/src/compat_helper.h [hunk 1]
```diff
@@ -17,8 +17,19 @@ The full license is in the LICENSE file, distributed with this software.
 PySlice_GetIndicesEx changes signature in PY3
 but 3.6.1 in particular changes the behavior of this function slightly
 https://bugs.python.org/issue27867
+
+
+In 3.6.1 PySlice_GetIndicesEx was changed to a macro
```
Comment (jreback) [inline pandas/_libs/src/compat_helper.h]: cc @njsmith 

?

Comment (njsmith) [inline pandas/_libs/src/compat_helper.h]: This looks like it does what you're hoping it does to me.

**Comment by jreback** [comment]
thanks @chris-b1 @njsmith
