### PR TITLE
BUG: DataFrame.to_json OverflowError with np.long* dtypes

### LINKED ISSUE #55403: BUG: DataFrame.to_json OverflowError with np.long* dtypes
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [x] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.

### Reproducible Example

```python
import sys
import pandas as pd
import numpy as np

df = pd.DataFrame(
    np.random.randint(0, 100, size=(10, 1)),
    dtype=np.longdouble,
)

df.to_json(sys.stdout)
```

### Issue Description

Calling `DataFrame.to_json()` on a DataFrame with a `dtype=np.longdouble` or `dtype=np.longfloat` causes an `OverflowError: Maximum recursion level reached` error. This seems to be the result of the JSON serializer not handling these types; `DataFrame.to_csv()` is not affected by this issue.

### Expected Behavior

These types should be serialized as floats, or at a minimum, the recursion error should be fixed and a more appropriate serialization error should be raised.

### Installed Versions

INSTALLED VERSIONS
------------------
commit              : e86ed377639948c64c429059127bcf5b359ab6be
python              : 3.10.9.final.0
python-bits         : 64
OS                  : Darwin
OS-release          : 22.6.0
Version             : Darwin Kernel Version 22.6.0: Wed Jul  5 22:22:05 PDT 2023; root:xnu-8796.141.3~6/RELEASE_ARM64_T6000
machine             : arm64
processor           : arm
byteorder           : little
LC_ALL              : en_US.UTF-8
LANG                : None
LOCALE              : en_US.UTF-8

pandas              : 2.1.1
numpy               : 1.26.0
pytz                : 2023.3.post1
dateutil            : 2.8.2
setuptools          : 68.1.2
pip                 : 23.2.1
Cython              : None
pytest              : 7.4.2
hypothesis          : None
sphinx              : None
blosc               : None
feather             : None
xlsxwriter          : None
lxml.etree          : None
html5lib            : None
pymysql             : None
psycopg2            : None
jinja2              : None
IPython             : None
pandas_datareader   : None
bs4                 : None
bottleneck          : None
dataframe-api-compat: None
fastparquet         : None
fsspec              : None
gcsfs               : None
matplotlib          : None
numba               : None
numexpr             : None
odfpy               : None
openpyxl            : None
pandas_gbq          : None
pyarrow             : None
pyreadstat          : None
pyxlsb              : None
s3fs                : None
scipy               : None
sqlalchemy          : None
tables              : None
tabulate            : None
xarray              : None
xlrd                : None
zstandard           : 0.21.0
tzdata              : 2023.3
qtpy                : None
pyqt5               : None

### PR DESCRIPTION
**Pull request by gupta-paras**
- [x] closes #55403 (Replace xxxx with the GitHub issue number)
- [x] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature
- [x] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).
- [x] Added [type annotations](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#type-hints) to new arguments/methods/functions.
- [x] Added an entry in the latest `doc/source/whatsnew/vX.X.X.rst` file if fixing a bug or adding a new feature.

### CODE REVIEW

**Comment by WillAyd** [comment]
We don't support long double as a data type and I don't think upcasting double to long double is appropriate. We should probably just raise here

**Comment by gupta-paras** [comment]
@WillAyd, Agreed with issues with upcasting. I have updated the commit with changes suggested in above comment.
Thanks

File: pandas/_libs/src/vendored/ujson/python/objToJSON.c [hunk 1]
```diff
@@ -1610,6 +1610,11 @@ void Object_beginTypeContext(JSOBJ _obj, JSONTypeContext *tc) {
                                   PyArray_DescrFromType(NPY_DOUBLE));
         tc->type = JT_DOUBLE;
         return;
+    } else if (PyArray_IsScalar(obj, LongDouble)) {
```
Comment (WillAyd) [inline pandas/_libs/src/vendored/ujson/python/objToJSON.c:1613]: This works, but I think the lines directly following it are supposed to be a catchall for unsupported types. Do you know why that isn't being hit? I would rather we keep this generic instead of having to specify an error message for every type that we don't serialize

Comment (gupta-paras) [reply pandas/_libs/src/vendored/ujson/python/objToJSON.c:1613]: There is a code section at the end of this function: 
```    tc->type = JT_OBJECT;
    pc->iterBegin = Dir_iterBegin;
    pc->iterEnd = Dir_iterEnd;
    pc->iterNext = Dir_iterNext;
    pc->iterGetValue = Dir_iterGetValue;
    pc->iterGetName = Dir_iterGetName;
    return;
```
By default everything falls to this section and this causes infinite loop.

Comment (WillAyd) [reply pandas/_libs/src/vendored/ujson/python/objToJSON.c:1613]: Right but I'm asking about the next branch after what you've added. 

```c
} else if (PyArray_Check(obj) && PyArray_CheckScalar(obj)) {
```

Do you know what hits that currently? From reading the function I think the intent of that was to generically catch the issue you've described, but its possible the invariant is incorrect. Would something pass both `PyArray_Check` and `PyArray_CheckScalar`? Maybe the `PyArray_Check` call is incorrect and removing that alone would fix your issue?

Comment (gupta-paras) [reply pandas/_libs/src/vendored/ujson/python/objToJSON.c:1613]: Any value like: np.array(1) evaluates true for both of them. However yes, simply removing pyArray_check solves the issue. Again Thanks for the suggestion. Will updating the PR shortlyl.

File: doc/source/whatsnew/v2.2.0.rst [hunk 2]
```diff
@@ -348,6 +348,7 @@ I/O
 - Bug in :func:`read_csv` with ``engine="pyarrow"`` where ``usecols`` wasn't working with a csv with no headers (:issue:`54459`)
 - Bug in :func:`read_excel`, with ``engine="xlrd"`` (``xls`` files) erroring when file contains NaNs/Infs (:issue:`54564`)
 - Bug in :func:`to_excel`, with ``OdsWriter`` (``ods`` files) writing boolean/string value (:issue:`54994`)
+- Bug in :meth:`DataFrame.to_json` OverflowError with np.long* dtypes (:issue:`55403`)
```
Comment (WillAyd) [inline doc/source/whatsnew/v2.2.0.rst:351]:
```suggestion
- Bug where :meth:`DataFrame.to_json` would raise an ``OverflowError`` instead of a ``TypeError`` with unsupported NumPy types (:issue:`55403`)
```

File: pandas/_libs/src/vendored/ujson/python/objToJSON.c [hunk 3]
```diff
@@ -1610,9 +1610,13 @@ void Object_beginTypeContext(JSOBJ _obj, JSONTypeContext *tc) {
                                   PyArray_DescrFromType(NPY_DOUBLE));
         tc->type = JT_DOUBLE;
         return;
-    } else if (PyArray_Check(obj) && PyArray_CheckScalar(obj)) {
+    } else if (PyArray_CheckScalar(obj)) {
+        /* This handles all cases of array of zero dimension (numpy.array(1)) OR
```
Comment (WillAyd) [inline pandas/_libs/src/vendored/ujson/python/objToJSON.c:1614]: You can remove the comment - I think this is inferrable already from the code/tests

**Comment by nmacholl** [comment]
> We don't support long double as a data type and I don't think upcasting double to long double is appropriate. We should probably just raise here

I'm curious, if pandas doesn't support these numpy types in a data frame, would it make sense to raise an exception at the time of creation or dtype assignment? There are maybe other places in the code these unsupported types would break?

**Comment by WillAyd** [comment]
@nmacholl you might want to check existing issues for any discussion, but I don't think its quite that simple. For starters assignment/creation isn't the only way those types might make there way into a DataFrame. There also exists a subset of users who may not use pandas for I/O / computations (where a lot of those limitations are imposed) versus just using it as an easy way to get labeled access to NumPy arrays. As an example, you'll see quite a few use cases in the issue log where users contain NumPy unicode dtypes in DataFrames even though pandas has almost no support for those too; in such cases a DataFrame is just a labeled indexer, and I don't think we want to break that type of workflow

**Comment by WillAyd** [comment]
@gupta-paras this looks good to me aside from outstanding comments / code suggestions. @mroeschke any thoughts on your end?

File: doc/source/whatsnew/v2.2.0.rst (hunk 2 above)
Comment (gupta-paras) [reply doc/source/whatsnew/v2.2.0.rst]: Hi @WillAyd, I have incorporated this change in latest commit. Thanks for this suggestion.

File: pandas/_libs/src/vendored/ujson/python/objToJSON.c (hunk 3 above)
Comment (gupta-paras) [reply pandas/_libs/src/vendored/ujson/python/objToJSON.c]: Hi @WillAyd, I have incorporated this change in latest commit. Thanks for this suggestion.

**Review by WillAyd — APPROVED** [review]

**Review by mroeschke — APPROVED** [review]

**Comment by mroeschke** [comment]
Thanks @gupta-paras
