### PR TITLE
BUG: pandas.to_datetime() does not respect exact format string with ISO8601

### LINKED ISSUE #12649: BUG: pandas.to_datetime() does not respect exact format string with ISO8601
#### Code Sample, a copy-pastable example if possible

```
import pandas as pd
s = pd.Series(['2012-01-01 10:00', '2012-02-10 23:20', '2012-03-22 12:40', '2012-05-02 02:00', '2012-06-11 15:20', '2012-07-22 04:40','2012-08-31 18:00', '2012-10-11 07:20', '2012-11-20 20:40', '2012-12-31 10:00'])
print s
0    2012-01-01 10:00
1    2012-02-10 23:20
2    2012-03-22 12:40
3    2012-05-02 02:00
4    2012-06-11 15:20
5    2012-07-22 04:40
6    2012-08-31 18:00
7    2012-10-11 07:20
8    2012-11-20 20:40
9    2012-12-31 10:00
dtype: object
print pd.to_datetime(s, format='%Y-%m-%d', errors='raise', infer_datetime_format=False, exact=True)
0   2012-01-01 10:00:00
1   2012-02-10 23:20:00
2   2012-03-22 12:40:00
3   2012-05-02 02:00:00
4   2012-06-11 15:20:00
5   2012-07-22 04:40:00
6   2012-08-31 18:00:00
7   2012-10-11 07:20:00
8   2012-11-20 20:40:00
9   2012-12-31 10:00:00
dtype: datetime64[ns]
```
#### Expected Output

A ValueError exception because string `'2012-01-01 10:00'` (and all others of this series) does not comply with format string `'%Y-%m-%d'` and exact conversion is required.
## INSTALLED VERSIONS

commit: None
python: 2.7.10.final.0
python-bits: 64
OS: Darwin
OS-release: 15.3.0
machine: x86_64
processor: i386
byteorder: little
LC_ALL: None

pandas: 0.17.1
nose: 1.3.6
pip: 8.0.3
setuptools: 18.0
Cython: 0.23.4
numpy: 1.10.4
scipy: 0.16.0
statsmodels: None
IPython: 3.0.0
sphinx: None
patsy: None
dateutil: 2.5.0
pytz: 2015.7
blosc: None
bottleneck: 1.0.0
tables: 3.2.2
numexpr: 2.4.6
matplotlib: 1.4.3
openpyxl: 2.2.2
xlrd: 0.9.3
xlwt: 0.8.0
xlsxwriter: 0.7.3
lxml: 3.4.4
bs4: None
html5lib: None
httplib2: 0.9.1
apiclient: None
sqlalchemy: 1.0.9
pymysql: None
psycopg2: 2.6.1 (dt dec pq3 ext lo64)
Jinja2: None

### PR DESCRIPTION
**Pull request by nikitaved**
- [ ] closes #12649 (Replace xxxx with the GitHub issue number)
- [ ] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature
- [ ] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).
- [ ] Added [type annotations](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#type-hints) to new arguments/methods/functions.
- [ ] Added an entry in the latest `doc/source/whatsnew/vX.X.X.rst` file if fixing a bug or adding a new feature.

---

EDIT (by MarcoGorelli): this is something @nikitaved, @FDRocha, and I started working on together at a company retreat

### CODE REVIEW

File: pandas/_libs/tslibs/src/datetime/np_datetime_strings.c [hunk 1]
```diff
@@ -66,10 +66,29 @@ This file implements string parsing and creation for NumPy datetime.
...
+    --format_len; \
+  } else { \
+    if (format_len > 0) { \
+        if (*format != ch) { \
+            goto parse_error;  \
+        } \
+        ++format; \
+        --format_len; \
+    } \
+  } \
```
Comment (nikitaved) [inline pandas/_libs/tslibs/src/datetime/np_datetime_strings.c:85]: Nit: this could probably be simplified to something like this:
```c++
if (*format != ch) goto parse_error;
if (exact ^ format_len) goto parse_error;
++format;
--format_len;
```

Comment (nikitaved) [inline pandas/_libs/tslibs/src/datetime/np_datetime_strings.c:85]: super minor nit: maybe this cold be a bit easier to parse?
```c++
// Always error on character mismatch, or when format is exhausted in the exact case.
if (*format != ch || (exact && !format_len)) goto parse_error;
// Advance pointer if format is not exhausted
if (format_len) {
  ++format;
  --format_len;
}
```

Comment (MarcoGorelli) [reply pandas/_libs/tslibs/src/datetime/np_datetime_strings.c:85]: thanks for your suggestion! are you sure this is right though? if `exact=False` and we're at the end of the format string, won't `*format != ch` resolve to `True` and so go to the `parse_error`? At least, if I try this, then I get a few test failures, e.g.
```console
(.venv) megorelli@penguin:~/pandas-dev$ cat f.py 
import pandas as pd

pd.to_datetime(['2022-01-01'], format='%Y-%m', exact=False)

(.venv) megorelli@penguin:~/pandas-dev$ python f.py 
Traceback (most recent call last):
  File "/home/megorelli/pandas-dev/f.py", line 3, in <module>
    pd.to_datetime(['2022-01-01'], format='%Y-%m', exact=False)
  File "/home/megorelli/pandas-dev/pandas/core/tools/datetimes.py", line 1130, in to_datetime
    result = convert_listlike(argc, format)
  File "/home/megorelli/pandas-dev/pandas/core/tools/datetimes.py", line 441, in _convert_listlike_datetimes
    result, tz_parsed = objects_to_datetime64ns(
  File "/home/megorelli/pandas-dev/pandas/core/arrays/datetimes.py", line 2205, in objects_to_datetime64ns
    result, tz_parsed = tslib.array_to_datetime(
  File "pandas/_libs/tslib.pyx", line 440, in pandas._libs.tslib.array_to_datetime
    cpdef array_to_datetime(
  File "pandas/_libs/tslib.pyx", line 622, in pandas._libs.tslib.array_to_datetime
    raise ValueError(
ValueError: time data "2022-01-01" at position 0 doesn't match format "%Y-%m"
```

Comment (nikitaved) [reply pandas/_libs/tslibs/src/datetime/np_datetime_strings.c:85]: Would changing to `if (format_len > 1)` solve that? This should prevent `format` going beyond the very last character.

Comment (nikitaved) [reply pandas/_libs/tslibs/src/datetime/np_datetime_strings.c:85]: The format exhaustion is not tested outside of the macro, right?

Comment (nikitaved) [reply pandas/_libs/tslibs/src/datetime/np_datetime_strings.c:85]: @MarcoGorelli , I have updated the condition so that `*format != ch` is conditioned on `format_len > 0`. Would that work now? I would still argue that changing this whole function to iterate over format is a  better approach, but I might be missing some use cases for which this is not the case...

File: pandas/_libs/tslibs/src/datetime/np_datetime_strings.c [hunk 2]
```diff
@@ -235,13 +271,17 @@ int parse_iso_8601_datetime(const char *str, int len, int want_exc,
         if (out_local != NULL) {
             *out_local = 0;
         }
+        if (format_len) {
+          goto parse_error;
+        }
```
Comment (nikitaved) [inline pandas/_libs/tslibs/src/datetime/np_datetime_strings.c:276]: A question: do we want the block after `parse_error` to also reflect this format introduction with a meaningful error message? If format is incorrect, the error message will be about the date string, not the format string...

Comment (MarcoGorelli) [reply pandas/_libs/tslibs/src/datetime/np_datetime_strings.c:276]: That's a good question - the error message will still mention the format though, e.g.:
```python
>>> import pandas as pd
>>> pd.to_datetime('2022-01-01', format='%Y-%m-%d %H')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/megorelli/pandas-dev/pandas/core/tools/datetimes.py", line 1132, in to_datetime
    result = convert_listlike(np.array([arg]), format)[0]
  File "/home/megorelli/pandas-dev/pandas/core/tools/datetimes.py", line 441, in _convert_listlike_datetimes
    result, tz_parsed = objects_to_datetime64ns(
  File "/home/megorelli/pandas-dev/pandas/core/arrays/datetimes.py", line 2205, in objects_to_datetime64ns
    result, tz_parsed = tslib.array_to_datetime(
  File "pandas/_libs/tslib.pyx", line 440, in pandas._libs.tslib.array_to_datetime
    cpdef array_to_datetime(
  File "pandas/_libs/tslib.pyx", line 622, in pandas._libs.tslib.array_to_datetime
    raise ValueError(
ValueError: time data "2022-01-01" at position 0 doesn't match format "%Y-%m-%d %H"
```

File: pandas/_libs/tslibs/src/datetime/np_datetime_strings.c (hunk 1 above)
Comment (MarcoGorelli) [reply pandas/_libs/tslibs/src/datetime/np_datetime_strings.c]: Yeah, that's cleaner, thanks!

Regarding iterating over `format` - not sure that'd be possible, because there are parts of the codebase which reach here just by specifying `require_iso8601` but without passing `format`. An option could be to do something like:
- if `format == ''` and `not exact` then use the current path,
- else if `format != ''`, then iterate over `format` until it's exhausted, then use the current codepath
but I think that would add even more complexity (if I've understood correctly)

File: pandas/_libs/tslib.pyx [hunk 3]
```diff
@@ -445,6 +445,8 @@ cpdef array_to_datetime(
     bint utc=False,
     bint require_iso8601=False,
     bint allow_mixed=False,
+    str format="",
```
Comment (WillAyd) [inline pandas/_libs/tslib.pyx:448]: Can you use None as a default rather than `""`? I think can just type as Optional[str] which would be a bit cleaner

File: pandas/_libs/tslibs/src/datetime/np_datetime_strings.c [hunk 4]
```diff
@@ -66,10 +66,24 @@ This file implements string parsing and creation for NumPy datetime.
  *
  * Returns 0 on success, -1 on failure.
  */
+
+#define FORMAT_STARTSWITH(ch) \
```
Comment (WillAyd) [inline pandas/_libs/tslibs/src/datetime/np_datetime_strings.c:70]: Can you make this a function instead of a macro?

**Review by WillAyd — CHANGES_REQUESTED** [review]

**Comment by WillAyd** [comment]
This is vendored from numpy - can you also check if there's something like this upstream? If not may be worth doing there as well

File: pandas/_libs/tslibs/src/datetime/np_datetime_strings.c (hunk 4 above)
Comment (nikitaved) [reply pandas/_libs/tslibs/src/datetime/np_datetime_strings.c:70]: The macro modifies two variables and has access to the goto location. A separate function then has to have at least two variables accepted with one of them being a pointer to a pointer. It also has to return a flag that needs a check every single time it is called. We can remove this pointer to a pointer, however, and modify just an offset variable, but checks are unavoidable. Is that a preferred approach? What do you think about checks being done in a macro instead?

Comment (WillAyd) [reply pandas/_libs/tslibs/src/datetime/np_datetime_strings.c:70]: You can also just do one function that performs the check and in the caller run the goto in the failing branch while advancing the pointers in the succeeding branch. It is more verbose but also more explicit than the macro.

**Review by MarcoGorelli — COMMENTED** [review]
Thanks for your review - I've changed the macro to a function

Regarding the numpy function this is vendored from - that one's a lot stricter, it only allows `-` as a separator

https://github.com/numpy/numpy/blob/7653829fa0d409d5850566cda1c031d9fadc1c22/numpy/core/src/multiarray/datetime_strings.c#L402-L413

whereas pandas allows multiple separators (so long as they're consistent)

https://github.com/pandas-dev/pandas/blob/12721b07faa2dfe8bb45ee3d5d249f819fd6ee6e/pandas/_libs/tslibs/src/datetime/np_datetime_strings.c#L97

so I don't think this would be useful to them

Regarding whether the pandas function should become stricter - not sure, it's not user-facing anyway, it just gives users a fast-path for ISO8601-like date strings

File: pandas/_libs/tslibs/src/datetime/np_datetime_strings.c [hunk 5]
```diff
@@ -66,10 +66,19 @@ This file implements string parsing and creation for NumPy datetime.
  *
  * Returns 0 on success, -1 on failure.
  */
+
+int format_startswith(char ch, int format_len, char format, int exact) {
+    if ((format_len && format != ch) || (exact && !format_len)) {
```
Comment (nikitaved) [inline pandas/_libs/tslibs/src/datetime/np_datetime_strings.c:71]: Nit: let's probably restore the comments?

Comment (nikitaved) [reply pandas/_libs/tslibs/src/datetime/np_datetime_strings.c:77]: Also a minor. What C do you use, and with what optimization flags? Maybe we could also inline these checks.

Comment (MarcoGorelli) [reply pandas/_libs/tslibs/src/datetime/np_datetime_strings.c:77]: As in, `inline int format_startswith`?

I think this is where all the C compilation information is set: https://github.com/pandas-dev/pandas/blob/main/setup.py

Comment (nikitaved) [reply pandas/_libs/tslibs/src/datetime/np_datetime_strings.c:77]: Yes, this is the one. Should work here unless it earlier than C99 is used afair.

File: pandas/_libs/tslib.pyx (hunk 3 above)
Comment (nikitaved) [reply pandas/_libs/tslib.pyx:448]: If None can be interpreted as nullptr, I agree that having None is a cleaner option.

Comment (MarcoGorelli) [reply pandas/_libs/tslib.pyx:448]: This isn't user-facing, it's just used internally

Not sure I understand about None being interpreted as nullptr, but if I pass `None` to `get_c_string_buf_and_size` I get
```
Traceback (most recent call last):
  File "t.py", line 109, in <module>
    print(to_datetime('2012-01-01T10:00', format='%Y-%m-%dT%H:%M', exact=False))
  File "/home/marcogorelli/pandas-dev/pandas/core/tools/datetimes.py", line 1117, in to_datetime
    result = convert_listlike(np.array([arg]), format)[0]
  File "/home/marcogorelli/pandas-dev/pandas/core/tools/datetimes.py", line 441, in _convert_listlike_datetimes
    result, tz_parsed = objects_to_datetime64ns(
  File "/home/marcogorelli/pandas-dev/pandas/core/arrays/datetimes.py", line 2177, in objects_to_datetime64ns
    result, tz_parsed = tslib.array_to_datetime(
  File "pandas/_libs/tslib.pyx", line 440, in pandas._libs.tslib.array_to_datetime
    cpdef array_to_datetime(
  File "pandas/_libs/tslib.pyx", line 706, in pandas._libs.tslib.array_to_datetime
    raise
  File "pandas/_libs/tslib.pyx", line 606, in pandas._libs.tslib.array_to_datetime
    string_to_dts_failed = string_to_dts(
  File "pandas/_libs/tslibs/np_datetime.pyx", line 288, in pandas._libs.tslibs.np_datetime.string_to_dts
    format_buf = get_c_string_buf_and_size(None, &format_length)
  File "pandas/_libs/tslibs/util.pxd", line 221, in pandas._libs.tslibs.util.get_c_string_buf_and_size
    return PyUnicode_AsUTF8AndSize(py_string, length)
TypeError: bad argument type for built-in operation
```

So I think the conversion between `None` and `str` needs to happen at some point internally anyway

If `exact` if False and `format` is `''`, then it should match anything

Comment (nikitaved) [reply pandas/_libs/tslib.pyx:448]: What about?
```python
if format is not None: 
  format_buf = 0
  format_lenght = 0
else:
  format_buf = get_c_string_buf_and_size(...)
...

return parse_iso...
```
The rest of the code should work just fine given that the checks are conditioned on `format_lenght`.

Comment (nikitaved) [reply pandas/_libs/tslib.pyx:448]: As long as `format_len` is `0`, `*format_buf` could be anything, so it is a bit clearer to have it as `NULL`, imho.

Comment (MarcoGorelli) [reply pandas/_libs/tslib.pyx:448]: how though? because if it's `0`, then we get
```
  File "t.py", line 109, in <module>
    print(to_datetime('2012-01-01T10:00', format='%Y-%m-%dT%H:%M', exact=False))
  File "/home/marcogorelli/pandas-dev/pandas/core/tools/datetimes.py", line 1117, in to_datetime
    result = convert_listlike(np.array([arg]), format)[0]
  File "/home/marcogorelli/pandas-dev/pandas/core/tools/datetimes.py", line 441, in _convert_listlike_datetimes
    result, tz_parsed = objects_to_datetime64ns(
  File "/home/marcogorelli/pandas-dev/pandas/core/arrays/datetimes.py", line 2177, in objects_to_datetime64ns
    result, tz_parsed = tslib.array_to_datetime(
  File "pandas/_libs/tslib.pyx", line 440, in pandas._libs.tslib.array_to_datetime
    cpdef array_to_datetime(
  File "pandas/_libs/tslib.pyx", line 706, in pandas._libs.tslib.array_to_datetime
    raise
  File "pandas/_libs/tslib.pyx", line 606, in pandas._libs.tslib.array_to_datetime
    string_to_dts_failed = string_to_dts(
  File "pandas/_libs/tslibs/np_datetime.pyx", line 287, in pandas._libs.tslibs.np_datetime.string_to_dts
    format_buf = get_c_string_buf_and_size(0, &format_length)
TypeError: Expected unicode, got int
```

Comment (MarcoGorelli) [reply pandas/_libs/tslib.pyx]: I've tried
```
format_buf = <const char*> 0
```
but then get
```
Segmentation fault
```
(with no further info)

For now I've gone with `format = b''`, and handling `None` inside this function does indeed look cleaner, thanks!

File: pandas/_libs/tslibs/np_datetime.pyx [hunk 6]
```diff
@@ -273,14 +274,25 @@ cdef inline int string_to_dts(
...
         Py_ssize_t length
         const char* buf
+        Py_ssize_t format_length
+        const char* format_buf
 
     buf = get_c_string_buf_and_size(val, &length)
+    if format is None:
+        format_buf = b''
+        format_length = 0
+        exact = False
```
Comment (nikitaved) [inline pandas/_libs/tslibs/np_datetime.pyx:290]: do we need to set `exact` to `False` if format is empty but `exact=True` is provided?

File: pandas/_libs/tslibs/np_datetime.pyx [hunk 7]
```diff
@@ -273,14 +274,25 @@ cdef inline int string_to_dts(
     int* out_local,
     int* out_tzoffset,
     bint want_exc,
+    format: str | None = None,
+    bint exact = True,
 ) except? -1:
```
[the remark this answers is not in the document]
Comment (MarcoGorelli) [reply pandas/_libs/tslibs/np_datetime.pyx:279]: True but in `to_datetime` the defaults are `format=None` and `exact=True`, so this was just for compatibility with that

File: pandas/_libs/tslibs/np_datetime.pyx (hunk 6 above)
Comment (MarcoGorelli) [reply pandas/_libs/tslibs/np_datetime.pyx:290]: If we stick with the `to_datetime` defaults of `format=None` and `exact=True`, then in the case of `format=None` there's no format to respect, and having an empty `format_buf` with `exact=True` would fail on any non-empty date-string

I think `format=None` should be interpreted as "don't match `format`", in which case if the C function doesn't accept `None` and we need to pass an empty string, then we'd need to set `exact` to `False`

File: pandas/_libs/tslibs/src/datetime/np_datetime_strings.c [hunk 8]
```diff
@@ -66,10 +66,25 @@ This file implements string parsing and creation for NumPy datetime.
  *
  * Returns 0 on success, -1 on failure.
  */
+
+inline int format_startswith(char ch, int format_len, char format, int exact) {
```
Comment (WillAyd) [inline pandas/_libs/tslibs/src/datetime/np_datetime_strings.c:70]: Still not sure about this function. What is the advantage of this over using `strncmp`? Seems like it would be cleaner to just use that plus some combination of `exact` outside of this

File: pandas/_libs/tslibs/src/datetime/np_datetime_strings.c [hunk 9]
```diff
@@ -104,19 +119,28 @@ int parse_iso_8601_datetime(const char *str, int len, int want_exc,
     while (sublen > 0 && isspace(*substr)) {
         ++substr;
         --sublen;
+        if (!format_startswith(' ', format_len, *format, exact)) goto parse_error;
```
Comment (WillAyd) [inline pandas/_libs/tslibs/src/datetime/np_datetime_strings.c:122]: Minor nit but can you run `clang-format` against this file? I think it would format this differently

**Review by WillAyd — CHANGES_REQUESTED** [review]

File: pandas/_libs/tslibs/np_datetime.pyx [hunk 10]
```diff
@@ -273,14 +274,25 @@ cdef inline int string_to_dts(
...
     cdef:
         Py_ssize_t length
         const char* buf
+        Py_ssize_t format_length
+        const char* format_buf
 
     buf = get_c_string_buf_and_size(val, &length)
```
Comment (WillAyd) [inline pandas/_libs/tslibs/np_datetime.pyx:286]: Orthogonal to this but if you want to work more with the C codebase I think we should just replace `get_c_string_buf_and_size` with `PyUnicode_AsUTF8AndSize` directly; the former might have served a purpose with the Py2/3 transition but is just an unnecessary layer at this point

File: pandas/_libs/tslibs/src/datetime/np_datetime_strings.c (hunk 8 above)
Comment (WillAyd) [reply pandas/_libs/tslibs/src/datetime/np_datetime_strings.c:70]: You might also be interested in the POSIX `strstr` function for substring searches with the `exact` argument

Comment (WillAyd) [reply pandas/_libs/tslibs/src/datetime/np_datetime_strings.c:70]: OK I think I understand a bit more now what you are trying to do. I think it would be best if you just kept a local variable for characters consumed, which you can increment every time you increment the format pointer (you are kind of doing this anyway).  You don't really need a function but can rather just do `if (format++ != '%') { // handle error }`

The order of operations will do the postfix increment after assignment, so this consolidates what you are trying to do

Comment (MarcoGorelli) [reply pandas/_libs/tslibs/src/datetime/np_datetime_strings.c:70]: Just checking I've understood, is the suggestion to get rid of the function and each time do something like
```
if (((format_len > 0) && (format++ != '%')) || (exact && (format_len<=0))){
    if (format_len > 0) format_len--;
    goto parse_error;
}
```
?

I presume I've misunderstood because to me this looks more complicated and loses the docstring 😄

Comment (nikitaved) [reply pandas/_libs/tslibs/src/datetime/np_datetime_strings.c:70]: It is possible to even do everything in one single if statement, but it then starts to look as one of these tricky C language questions... This separate function has comments, it is more clear imho, and is very likely to get inlined.

Comment (WillAyd) [reply pandas/_libs/tslibs/src/datetime/np_datetime_strings.c:70]: Its not a matter of inlining as much as code organization. For instance, this block:

```c
    if (!format_startswith('%', format_len, *format, exact)) goto parse_error;
    if (format_len) {++format; --format_len;}
    if (!format_startswith('Y', format_len, *format, exact)) goto parse_error;
    if (format_len) {++format; --format_len;}
```

Would seem more naturally expressed as:

```c
if (format_len < 2 && exact) {
  goto parse_error;
} 

if (*format++ != '%') {
  goto parse_error;
} 

if (*format++ != 'Y') {
  goto parse_error;
}
```

There's some code golf you can do therein to shorten it but that's not really what I'm after. Moreso we should refactor this to avoid trying to cram a lot into a function with a lot of side effects, as we don't use that type of pattern much if at all in our code base, and a lot of the character by character checks being done are overkill

Comment (WillAyd) [reply pandas/_libs/tslibs/src/datetime/np_datetime_strings.c:70]: The other advantage of this is you _could_ provide an actual error message as to what went wrong at what position of the format, though not critical to scope for this PR

Comment (nikitaved) [reply pandas/_libs/tslibs/src/datetime/np_datetime_strings.c:70]: I agree. Can't we just refactor everything and replace it with something like

1) match given format with the full format and return position of mismatch/success that depends on lengths and exactness.
2) Parse the string with sprintf or something like this, with additional validity checks. Provided that 1 is a success
?
Unless doing everything in one go is a performance decision.

Comment (WillAyd) [reply pandas/_libs/tslibs/src/datetime/np_datetime_strings.c:70]: If you see a better way to refactor I am definitely open to it. I don't think the performance here will be that critical. 
_Probably_ better served as a pre cursor before adding functionality here, or alternately as a follow up to the "side-effect-less" design mentioned already

File: pandas/_libs/tslibs/src/datetime/np_datetime_strings.c [hunk 11]
```diff
@@ -104,19 +105,30 @@ int parse_iso_8601_datetime(const char *str, int len, int want_exc,
     while (sublen > 0 && isspace(*substr)) {
         ++substr;
         --sublen;
+        if (format_len < 1 && exact) goto parse_error;
```
Comment (WillAyd) [inline pandas/_libs/tslibs/src/datetime/np_datetime_strings.c:108]:
```suggestion
        if (format_len < 1 && exact) {
          goto parse_error;
        }
```

I think clang-format will automatically enforce this style for you

File: pandas/_libs/tslibs/src/datetime/np_datetime_strings.c [hunk 12]
```diff
@@ -69,7 +69,8 @@ This file implements string parsing and creation for NumPy datetime.
 int parse_iso_8601_datetime(const char *str, int len, int want_exc,
                             npy_datetimestruct *out,
                             NPY_DATETIMEUNIT *out_bestunit,
-                            int *out_local, int *out_tzoffset) {
+                            int *out_local, int *out_tzoffset,
+                            const char* format, int format_len, int exact) {
```
Comment (WillAyd) [inline pandas/_libs/tslibs/src/datetime/np_datetime_strings.c:73]: Do we ever have to worry about `format_len` being negative? Seems like it could cause undefined behavior if that was passed this way - would be best to validate the argument and set an appropriate error up front

File: pandas/_libs/tslibs/src/datetime/np_datetime_strings.c [hunk 13]
```diff
@@ -104,19 +105,30 @@ int parse_iso_8601_datetime(const char *str, int len, int want_exc,
...
+        if (format_len && *format++ != '-') goto parse_error;
+        if (format_len) --format_len;
     }
 
     if (sublen == 0) {
         goto parse_error;
     }
 
     /* PARSE THE YEAR (4 digits) */
+    if (format_len < 2 && exact) goto parse_error;
```
Comment (WillAyd) [inline pandas/_libs/tslibs/src/datetime/np_datetime_strings.c:127]:
```suggestion
    if (format_len < 2) {
      if (exact) {
        goto parse_error;
      }
      // What happens here?
    } else {
      if (*format++ != '%' && *format++ != 'Y') {
        goto parse_error;
      }
      
      format_len -= 2;
    }
```

Current code has undefined behavior and a possible segfault if `format_len` is 1 while `exact` is False. Need to think through what action should be taken there

File: pandas/_libs/tslibs/src/datetime/np_datetime_strings.c (hunk 11 above)
Comment (WillAyd) [inline pandas/_libs/tslibs/src/datetime/np_datetime_strings.c:108]:
```suggestion
        if (format_len < 1) {
          if (exact) {
            goto parse_error;
          }
        // Do something?
        } else {
          if (*format++ != ' ') {
            goto parse_error;
          }
          
          format_len--;
        }
```

I think this control flow would work more universally and avoid logic pitfalls / segfaults (see other comment)

**Review by WillAyd — CHANGES_REQUESTED** [review]
Making really nice progress here. Mostly a suggestion on branching layout that I think can be applied to all cases

File: pandas/_libs/tslibs/src/datetime/np_datetime_strings.c (hunk 13 above)
Comment (MarcoGorelli) [reply pandas/_libs/tslibs/src/datetime/np_datetime_strings.c]: In practice that shouldn't be possible - this function's only used internally, and 

https://github.com/pandas-dev/pandas/blob/57d8d3a7cc2c4afc8746bf774b5062fa70c0f5fd/pandas/_libs/tslibs/parsing.pyx#L886-L903

would return false if the format were for example `%Y-%`. I've changed it to raise if `format_len` isn't `0` anyway, thanks

File: pandas/_libs/tslibs/src/datetime/np_datetime_strings.c (hunk 12 above)
Comment (MarcoGorelli) [reply pandas/_libs/tslibs/src/datetime/np_datetime_strings.c:73]: That shouldn't ever happen - it's the same with the `len` variable, it comes from

https://github.com/pandas-dev/pandas/blob/f3060c9afab7f8cd8e4362324cc3978d71314a73/pandas/_libs/tslibs/np_datetime.pyx#L284-L296

so I don't see how `len` nor `format_len` could be negative, as `parse_iso_8601_datetime` is only used internally

I've added a check anyway

File: pandas/_libs/tslibs/src/datetime/np_datetime_strings.c (hunk 11 above)
Comment (MarcoGorelli) [reply pandas/_libs/tslibs/src/datetime/np_datetime_strings.c]: I tried `clang-format` and it formatted it without the braces, i.e.
```
        if (format_len < 1 && exact)
          goto parse_error;
```
so I've gone with that for now

File: .pre-commit-config.yaml [hunk 14]
```diff
@@ -48,7 +48,13 @@ repos:
         # this particular codebase (e.g. src/headers, src/klib). However,
         # we can lint all header files since they aren't "generated" like C files are.
         exclude: ^pandas/_libs/src/(klib|headers)/
-        args: [--quiet, '--extensions=c,h', '--headers=h', --recursive, '--filter=-readability/casting,-runtime/int,-build/include_subdir']
+        args: [
+            --quiet,
+            '--extensions=c,h',
+            '--headers=h',
+            --recursive,
+            '--filter=-readability/casting,-runtime/int,-build/include_subdir,-readability/fn_size'
```
Comment (MarcoGorelli) [inline .pre-commit-config.yaml:56]: `parse_iso_8601_datetime` is now more than 500 non-comment lines, so I've turned off that check for now

**Review by MarcoGorelli — COMMENTED** [review]
Thanks @WillAyd for your review!

File: pandas/_libs/tslibs/src/datetime/np_datetime_strings.c (hunk 13 above)
Comment (WillAyd) [reply pandas/_libs/tslibs/src/datetime/np_datetime_strings.c]: Yea what you will find with C is that you want to be extremely explicit. Even if it's not possible today, if someone refactors the code and it does happen things become very difficult to debug. 

Our error checking in some of our extensions is really loose, which is why our internal code is relatively difficult to refactor

File: .pre-commit-config.yaml (hunk 14 above)
Comment (WillAyd) [reply .pre-commit-config.yaml:56]: Separate to this but I would also be fine exploring another tool aside from cpplint. I haven't seen many other projects use this tool, particularly for C instead of C++. clang has a formating and static analyzer tool that would likely be more useful

File: pandas/_libs/tslibs/src/datetime/np_datetime_strings.c [hunk 15]
```diff
@@ -104,19 +107,44 @@ int parse_iso_8601_datetime(const char *str, int len, int want_exc,
     while (sublen > 0 && isspace(*substr)) {
         ++substr;
         --sublen;
+        if (format_len < 1) {
```
Comment (WillAyd) [inline pandas/_libs/tslibs/src/datetime/np_datetime_strings.c:110]: OK looking great. Now I think we've established a pretty clear pattern for a function. So with inputs of:
  * format string
  * format length remaining
  * characters to compare
  * whether exactness matters or not

I think you can now convert this back into the reusable function you always wanted. Something like:

```c
// This function will advance the pointer on format
// and decrement characters_remaining by n on success
// On failure will return -1 without incrementing
int compare_format(const char **format, int *characters_remaining, 
                 const char *compare_to, int n, const int exact) {
  if (*characters_remaining < n) {
    if (exact) {
      // TODO: in the future we should set a PyErr here 
      // to be very clear about what went wrong
      return -1;
    } else {
      // TODO: same return value in this function as
      // above branch, but stub out a future where
      // we have a better error message
      return -1;
    }
  }
  else {
    if (!strncmp(*format, compare_to, n)) {
      // TODO: PyErr to differentiate what went wrong
      return -1;
    } else {
      *format += n;
      *characters_remaining -= n;
      return 0;
    }
  }
}
```

Calling this like `compare_format(&format, &format_len, '%y', 2, check)` should do the mutation you are looking for and give us a better pattern to set explicit error messages about what went wrong. Ideally would do this along with this function, but I think in a follow up it would be better if we replaced the `goto` with a `-1` return value + setting a PyError, as that is a common practice in CPython development

**Comment by MarcoGorelli** [comment]
Thanks @WillAyd for your review, I've learned a few new things!

I wasn't sure how to pass a character (like `ymd_sep`) to `strncmp`, so I did `const char tmp = {ymd_sep}`, is that alright?

File: pandas/_libs/tslibs/src/datetime/np_datetime_strings.c [hunk 16]
```diff
@@ -66,10 +66,45 @@ This file implements string parsing and creation for NumPy datetime.
  *
  * Returns 0 on success, -1 on failure.
  */
+
+// This function will advance the pointer on format
+// and decrement characters_remaining by n on success
+// On failure will return -1 without incrementing
+int compare_format(const char **format, int *characters_remaining,
```
Comment (WillAyd) [inline pandas/_libs/tslibs/src/datetime/np_datetime_strings.c:73]:
```suggestion
static int compare_format(const char **format, int *characters_remaining,
```

File: pandas/_libs/tslibs/src/datetime/np_datetime_strings.c [hunk 17]
```diff
@@ -156,13 +201,21 @@ int parse_iso_8601_datetime(const char *str, int len, int want_exc,
         ymd_sep = valid_ymd_sep[i];
         ++substr;
         --sublen;
+
+        const char tmp[1] = {ymd_sep};
+        if (compare_format(&format, &format_len, tmp, 1, exact)) {
```
Comment (WillAyd) [inline pandas/_libs/tslibs/src/datetime/np_datetime_strings.c:206]:
```suggestion
        if (compare_format(&format, &format_len, &ymd_sep, 1, exact)) {
```

The address of a char gives you a char * that you need. If you do this can delete the preceding line

Comment (MarcoGorelli) [reply pandas/_libs/tslibs/src/datetime/np_datetime_strings.c]: ah that works, thanks!

**Review by WillAyd — APPROVED** [review]
nice work lgtm @mroeschke

**Review by mroeschke — APPROVED** [review]

**Comment by mroeschke** [comment]
Just a merge conflict otherwise very nice!

**Comment by MarcoGorelli** [comment]
Thanks Will and Matthew for your reviews/approvals!

Let's ship this then, and thanks @nikitaved and @fdrocha for the collaboration
