### PR TITLE
Remove Encoding of values in char** For Labels

### LINKED ISSUE #20500: DataFrame.to_json() produces malformed JSON when DataFrame contains tuples as column
#### Code Sample, a copy-pastable example if possible

```python
# Your code here
# coding: utf-8
import json, traceback, pandas
test = pandas.DataFrame(data = {
    'key': ['a', 'a', 'b', 'b', 'a'],
    'value': [1, 2, 3, 4, 5]
})
stat = test.groupby('key').agg(['sum', 'mean', 'count'])
stat_json = stat.to_json()
print(stat)
print(stat_json)
try:
    json.loads(stat_json)
except ValueError:
    traceback.print_exc()
stat_reset = stat.reset_index()
stat_reset_json = stat_reset.to_json()
print(stat_reset)
print(stat_reset_json)
try:
    json.loads(stat_reset_json)
except ValueError:
    traceback.print_exc()
```

##### Result by Python 2.7

```
    value                
      sum      mean count
key                      
a       8  2.666667     3
b       7  3.500000     2
{"["value","sum"]":{"a":8,"b":7},"["value","mean"]":{"a":2.6666666667,"b":3.5},"["value","count"]":{"a":3,"b":2}}
Traceback (most recent call last):
  File "pycheck.py", line 12, in <module>
    json.loads(stat_json)
  File "/usr/local/Cellar/python@2/2.7.14_3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/local/Cellar/python@2/2.7.14_3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/Cellar/python@2/2.7.14_3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 380, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Expecting : delimiter: line 1 column 5 (char 4)
  key value                
        sum      mean count
0   a     8  2.666667     3
1   b     7  3.500000     2
{"["key",""]":{"0":"a","1":"b"},"["value","sum"]":{"0":8,"1":7},"["value","mean"]":{"0":2.6666666667,"1":3.5},"["value","count"]":{"0":3,"1":2}}
Traceback (most recent call last):
  File "pycheck.py", line 20, in <module>
    json.loads(stat_reset_json)
  File "/usr/local/Cellar/python@2/2.7.14_3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/local/Cellar/python@2/2.7.14_3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/Cellar/python@2/2.7.14_3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 380, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Expecting : delimiter: line 1 column 5 (char 4)
```

##### Result by Python 3
```
    value                
      sum      mean count
key                      
a       8  2.666667     3
b       7  3.500000     2
{"["value","sum"]":{"a":8,"b":7},"["value","mean"]":{"a":2.6666666667,"b":3.5},"["value","count"]":{"a":3,"b":2}}
Traceback (most recent call last):
  File "pycheck.py", line 12, in <module>
    json.loads(stat_json)
  File "/usr/local/Cellar/python/3.6.4_4/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/local/Cellar/python/3.6.4_4/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/Cellar/python/3.6.4_4/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/decoder.py", line 355, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting ':' delimiter: line 1 column 5 (char 4)
  key value                
        sum      mean count
0   a     8  2.666667     3
1   b     7  3.500000     2
{"["key",""]":{"0":"a","1":"b"},"["value","sum"]":{"0":8,"1":7},"["value","mean"]":{"0":2.6666666667,"1":3.5},"["value","count"]":{"0":3,"1":2}}
Traceback (most recent call last):
  File "pycheck.py", line 20, in <module>
    json.loads(stat_reset_json)
  File "/usr/local/Cellar/python/3.6.4_4/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/local/Cellar/python/3.6.4_4/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/Cellar/python/3.6.4_4/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/decoder.py", line 355, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting ':' delimiter: line 1 column 5 (char 4)
```

#### Problem description

``DataFrame.to_json()`` returns malformed JSON when its column contains tuple object, such as ``('value', 'sum')``, ``('value', 'mean')`` etc. in this case.

#### Expected Output

I think, at least in this case, correct output of double quote in strings should be escaped like this:

```
{"[\"value\",\"sum\"]":{"a":8,"b":7},"[\"value\",\"mean\"]":{"a":2.6666666667,"b":3.5},"[\"value\",\"count\"]":{"a":3,"b":2}}

{"[\"key\",\"\"]":{"0":"a","1":"b"},"[\"value\",\"sum\"]":{"0":8,"1":7},"[\"value\",\"mean\"]":{"0":2.6666666667,"1":3.5},"[\"value\",\"count\"]":{"0":3,"1":2}}
```

##### Python2.7

<details>

```
INSTALLED VERSIONS
------------------
commit: None
python: 2.7.14.final.0
python-bits: 64
OS: Darwin
OS-release: 16.7.0
machine: x86_64
processor: i386
byteorder: little
LC_ALL: None
LANG: en_US.UTF-8
LOCALE: None.None

pandas: 0.22.0
pytest: None
pip: 9.0.1
setuptools: 38.5.2
Cython: None
numpy: 1.14.1
scipy: None
pyarrow: None
xarray: None
IPython: None
sphinx: 1.6.3
patsy: None
dateutil: 2.7.0
pytz: 2017.2
blosc: None
bottleneck: None
tables: None
numexpr: None
feather: None
matplotlib: None
openpyxl: None
xlrd: None
xlwt: None
xlsxwriter: None
lxml: None
bs4: 4.5.3
html5lib: None
sqlalchemy: 1.2.5
pymysql: None
psycopg2: None
jinja2: 2.9.6
s3fs: None
fastparquet: None
pandas_gbq: None
pandas_datareader: None
```

</details>

##### Python3

<details>

```
INSTALLED VERSIONS
------------------
commit: None
python: 3.6.4.final.0
python-bits: 64
OS: Darwin
OS-release: 16.7.0
machine: x86_64
processor: i386
byteorder: little
LC_ALL: None
LANG: en_US.UTF-8
LOCALE: en_US.UTF-8

pandas: 0.22.0
pytest: None
pip: 9.0.1
setuptools: 38.5.2
Cython: None
numpy: 1.14.1
scipy: None
pyarrow: None
xarray: None
IPython: None
sphinx: None
patsy: None
dateutil: 2.7.0
pytz: 2018.3
blosc: None
bottleneck: None
tables: None
numexpr: None
feather: None
matplotlib: None
openpyxl: None
xlrd: None
xlwt: None
xlsxwriter: None
lxml: None
bs4: None
html5lib: None
sqlalchemy: 1.2.5
pymysql: None
psycopg2: None
jinja2: 2.10
s3fs: None
fastparquet: None
pandas_gbq: None
pandas_datareader: None
```

</details>

_I have checked past issues briefly, but I'm sorry if same issue was already filed._

### PR DESCRIPTION
**Pull request by WillAyd**
- [X] closes #20500

In reviewing this module there is a shared function for object keys and values which encodes objects into a separate buffer and subsequently indexes off of that. Instead of encoding values in a buffer I've updated that function to be a char ** pointing to string representations of the labels (or index / columns, rather). 

This is arguably a pre-cursor to:

  1. #19486 to disentangle date time functions from JSON
  2. #12004 to add indent support (tried this previously but vendoring ujson updates but didn't work because of this limitation)
  3. #27164 because the various formats may need column / index labels at different points in time, so encoding up front makes that very difficult to reuse

The only downside here I haven't been able to figure out is how to deal with date formatting. Right now all labels are written as epochs. I'm sure there is a way to handle but I wasn't clear on what the best way to convert arbitrary input (i.e. object or datetime dtypes) into ISO formats by element where applicable.

cc @jbrockmendel in case you have insight on that

### CODE REVIEW

**Comment by jbrockmendel** [comment]
can you give an example of the datetime inputs that are trouble?

**Comment by WillAyd** [comment]
Sure. I'm not sure how to best handle this:

```python
>>> df = pd.DataFrame([[1]], columns=[pd.Timestamp("today")])
>>> df.to_json(date_format="iso")
```

While also supporting:

```python
>>> df.columns = df.columns.astype(object)
>>> df.to_json(date_format="iso")
```

In a concise manner. AFAICT in the first example inspecting the object during iteration with `PyDateTime_Check` doesn't recognize it as a datetime whereas when passed in as an object it does

**Comment by WillAyd** [comment]
Right now the code handles neither and simply provides out the default str, which I guess is epoch for both cases

File: pandas/_libs/src/ujson/python/objToJSON.c [hunk 1]
```diff
@@ -1614,68 +1629,44 @@ char **NpyArr_encodeLabels(PyArrayObject *labels, JSONObjectEncoder *enc,
...
-
-        if (PyErr_Occurred() || enc->errorMsg) {
+        item = getitem(dataptr, labels);
+        if (!item) {
+	  NpyArr_freeLabels(ret, num);
+	  ret = 0;
+	  break;
+	}
+
+	PyObject *str = PyObject_Str(item);
```
Comment (WillAyd) [inline pandas/_libs/src/ujson/python/objToJSON.c]: @jbrockmendel last comment...here is where I think that check needs to go. We are getting the `str` of the object but when passed in as a DTA the introspection is different than when passed in an object array. Wondering if we have shared utilities to already handle that ambiguity I could leverage instead of trying to do it all in this extension

**Comment by jbrockmendel** [comment]
> AFAICT in the first example inspecting the object during iteration with PyDateTime_Check doesn't recognize it as a datetime whereas when passed in as an object it does

Off the top of my head, I'd guess that in the non-object case the array you're iterating over is a `ndarray[datetime64[ns]]` and not a DatetimeArray/DatetimeIndex.  As a result, the objects you get when iterating are datetime64 objects, which do not subclass datetime.  The check for that would be `PyObject_TypeCheck(obj, &PyDatetimeArrType_Type)` (at least that's how we do it in `tslibs.util`).

**Comment by WillAyd** [comment]
Thanks! Sounds in the direction I’ll give that a look

**Comment by WillAyd** [comment]
Sorry should clarify - so if the columns are all datetimes it appears that `PyTypeNum_ISDATETIME(type_num)` is true (this was in the pre-existing code as well). Otherwise if mixed objects then `PyDateTime_Check` and `PyDate_Check` would work.

Do we have one function that can arbitrary convert objects from either as appropriate to an isoformat that you know of?

**Comment by jbrockmendel** [comment]
> Do we have one function that can arbitrary convert objects from either as appropriate to an isoformat that you know of?

In python/cython I would probably just use `Timestamp(obj).isoformat()`.  Not sure how big a hassle that would be to do in the c file

File: pandas/tests/io/json/test_pandas.py [hunk 2]
```diff
@@ -1012,77 +1012,86 @@ def test_convert_dates_infer(self):
...
+        df["date"] = Timestamp(date)
+        df.iloc[1, df.columns.get_loc("date")] = pd.NaT
+        df.iloc[5, df.columns.get_loc("date")] = pd.NaT
+        if date_unit:
+            json = df.to_json(date_format="iso", date_unit=date_unit)
+        else:
+            json = df.to_json(date_format="iso")
+        result = read_json(json)
+        expected = df.copy()
+        # expected.index = expected.index.tz_localize("UTC")
```
Comment (WillAyd) [inline pandas/tests/io/json/test_pandas.py]: I commented this out as it was failing the test suite, but I don't think this is actually desired per #12997 . This change actually prevents index / column labels from undesirably being cast to UTC

The downside to doing this here is that how we handle timestamps differs slightly now depending on whether the timestamp appears as a JSON object key (for example, index and/or column values) versus as a value

Values get encoded via the `make_iso_8601_datetime` function that appears in tslibs/src/datetime/np_datetime_strings.c . I know @jbrockmendel was thinking about decoupling this dependency which we may be able to do when fully aligning the logic for creating a label versus encoding the data

File: pandas/_libs/src/ujson/python/objToJSON.c [hunk 3]
```diff
@@ -1614,68 +1628,111 @@ char **NpyArr_encodeLabels(PyArrayObject *labels, JSONObjectEncoder *enc,
...
+	      ret = 0;
+	      break;
+	    }
+
+	    cLabel = PyUnicode_AsUTF8(iso);
+	    Py_DECREF(iso);
+	    len = strlen(cLabel);
+	  } else {
+	    npy_int64 value;
+	    // TODO: refactor to not duplicate what goes on in beginTypeContext
```
Comment (WillAyd) [inline pandas/_libs/src/ujson/python/objToJSON.c]: Comment says it all but this duplicates logic here:

https://github.com/pandas-dev/pandas/blob/358107330d6805829d3af8dcdd49f2e828aaa81d/pandas/_libs/src/ujson/python/objToJSON.c#L1837

I was thinking of aligning in a follow up as there's a lot of things that can be refactored but happy to do here as well

File: pandas/_libs/src/ujson/python/objToJSON.c [hunk 4]
```diff
@@ -1614,68 +1628,111 @@ char **NpyArr_encodeLabels(PyArrayObject *labels, JSONObjectEncoder *enc,
...
+        item = getitem(dataptr, labels);
+        if (!item) {
+	  NpyArr_freeLabels(ret, num);
+	  ret = 0;
+	  break;
+	}
+
+	// Using a date as a key we need to special case the formatting
+	if (PyTypeNum_ISDATETIME(type_num) ||
+	    PyDateTime_Check(item) || PyDate_Check(item)) {
```
Comment (WillAyd) [inline pandas/_libs/src/ujson/python/objToJSON.c]: Might need to add Timedelta to the list though this doesn't fail anything. I'll check more thoroughly next

File: pandas/tests/io/json/test_pandas.py [hunk 5]
```diff
@@ -1012,77 +1012,86 @@ def test_convert_dates_infer(self):
             result = read_json(dumps(data))[["id", infer_word]]
             assert_frame_equal(result, expected)
 
-    def test_date_format_frame(self):
+    @pytest.mark.parametrize(
```
Comment (WillAyd) [inline pandas/tests/io/json/test_pandas.py]: Slightly orthogonal as this entire module could use some parametrization but added these here as they were helpful in debugging and I think easy to grok diff

File: pandas/_libs/src/ujson/python/objToJSON.c (hunk 4 above)
Comment (WillAyd) [reply pandas/_libs/src/ujson/python/objToJSON.c]: It looks like there is an existing issue with `Timedelta` and how it writes out opened by @TomAugspurger in #15137 

Here is behavior on master:

```python
In [8]: pd.DataFrame([[1]], columns=[pd.Timedelta('1D')]).to_json(date_format="iso")
Out[8]: '{"1970-01-02T00:00:00.000Z":{"0":1}}'
```

versus this branch

```python
In [9]: pd.DataFrame([[1]], columns=[pd.Timedelta('1D')]).to_json(date_format="iso")
Out[9]: '{"1970-01-02T00:00:00":{"0":1}}'
```

Neither is correct though I think this branch would make it easier to identify how to actually make that update, especially once the logic for writing out dt-like objects is aligned between the keys and values of JSON serialization

**Comment by WillAyd** [comment]
I think this is reviewable again. This is a little complicated so to summarize this change it would remove custom label encoding that we do in objToJSON. This theoretically would make the code easier to reason about and opens up the possibility to easily add #12004 indent support through work that is identical or similar to #26457 

A few caveats:
 - This change only affects *labels* which depending on the format could be any combination of the index and column values, if any at all
 - This causes performance regressions dealing with datetimelike objects as *labels only*. Benchmarks and reasoning are showing in Appendix A
 - Previous behavior would recursively encode labels. The plus side of this was that how items appear as keys would use the same logic was what appeared as a value for JSON objects. The downside is that this fights the JSON spec and ujson, as object keys by definition MUST be strings. It is also non-trivial to produce invalid JSON this way (see appendix B)
 - While the ultimate goal is to simplify things, this does introduce slightly different behavior for labels versus the actual data. For example, this change partially solves #15137 by appropriately handling Timedelta data in the labels, but doesn't work for Timedeltas appearing in the data. Ideally how Python objects are handled would be consistent regardless of location, but I've left this inconsistency for now because to truly make it work and resolve all performance implications might take a while

I feel like (save a few minor cleanups) it would be easiest to merge this in the current state and resolve label / data inconsistencies in follow ups, since to do that all at once would be a huge diff and tough to tackle incrementally. Open to suggestions on how to handle though.

## Appendix A
Here are all of the performance regressions. The reason for these is that when detecting a datetime-like array the new label encoding will create Python Timestamp objects for each entry, so that it can appropriately build an isoformat or scale the units from there. 

A vectorized solution would help a lot here and wouldn't be unreasonable to implement. I don't think this will be a long term / architectural problem just needs focus and addressing in follow up

```sh
       before           after         ratio
     [35810733]       [104d2f27]
     <remove-buf-writes~3^2>       <remove-buf-writes>
+        136±30ms        462±100ms     3.39  io.json.ToJSON.time_to_json('index', 'df_int_floats')
+         139±6ms        465±100ms     3.34  io.json.ToJSON.time_to_json('index', 'df_int_float_str')
+        125±30ms         365±80ms     2.93  io.json.ToJSON.time_to_json('index', 'df_date_idx')
+        131±10ms        357±100ms     2.72  io.json.ToJSON.time_to_json('index', 'df_td_int_ts')
+        117±20ms         309±40ms     2.64  io.json.ToJSON.time_to_json('columns', 'df_int_float_str')
+        128±20ms          301±6ms     2.36  io.json.ToJSON.time_to_json('columns', 'df_int_floats')
+        130±20ms         295±40ms     2.27  io.json.ToJSON.time_to_json('columns', 'df_date_idx')
+        150±50ms         301±20ms     2.01  io.json.ToJSON.time_to_json('columns', 'df_td_int_ts')
+         126±5ms         240±10ms     1.91  io.json.ToJSON.time_to_json_wide('records', 'df_date_idx')
+        194±10ms         323±40ms     1.67  io.json.ToJSON.time_to_json_wide('records', 'df_td_int_ts')
+         196±4ms         288±50ms     1.47  io.json.ToJSON.time_to_json_wide('records', 'df_int_float_str')
+         191±2ms         233±20ms     1.22  io.json.ToJSON.time_to_json_wide('columns', 'df_int_float_str')
+         125±1ms         149±10ms     1.19  io.json.ToJSONLines.time_floats_with_int_idex_lines
```

## Appendix B
As mentioned we would previously encode key values for JSON objects. This is pretty easy to break as shown in the example below (note the invalid string that this produces without error):

```python
In [15]: class Foo:
    ...:
    ...:     def toDict(self):
    ...:         return {"a": "b"}
    ...:
    ...: df = pd.DataFrame([[1]], columns=[Foo()])
    ...: print(df.to_json())
{"{"a":"b"}":{"0":1}}
```

This PR instead handles datetimelike objects by converting them to either epoch or iso formats and stringifying from there. All other objects are simply stringified. 

This has the added bonus of making tuples round-trippable albeit with data loss. To illustrate here is current master behavior:

```python
In [18]: pd.read_json(pd.DataFrame([[1]], index=[('a', 'b')]).to_json())
ValueError: No ':' found when decoding object value
```

As opposed to on this branch:
```python
In [5]: pd.read_json(pd.DataFrame([[1]], index=[('a', 'b')]).to_json())
Out[5]:
            0
('a', 'b')  1
```

So again some data loss but at the very least does not produce invalid JSON

File: pandas/_libs/src/ujson/lib/ultrajsonenc.c [hunk 6]
```diff
@@ -714,6 +714,12 @@ int Buffer_EscapeStringValidated(JSOBJ obj, JSONObjectEncoder *enc,
     }
 }
 
+#define Buffer_Reserve(__enc, __len) \
+    if ( (size_t) ((__enc)->end - (__enc)->offset) < (size_t) (__len))  \
+    {   \
+      Buffer_Realloc((__enc), (__len));\
+    }   \
+
```
Comment (jbrockmendel) [inline pandas/_libs/src/ujson/lib/ultrajsonenc.c]: does it matter that this is moved from the .h file?

File: pandas/_libs/src/ujson/python/objToJSON.c [hunk 7]
```diff
@@ -787,30 +789,23 @@ JSOBJ NpyArr_iterGetValue(JSOBJ obj, JSONTypeContext *tc) {
...
-static void NpyArr_getLabel(JSOBJ obj, JSONTypeContext *tc, size_t *outLen,
-                            npy_intp idx, char **labels) {
-    JSONObjectEncoder *enc = (JSONObjectEncoder *)tc->encoder;
-    PRINTMARK();
-    *outLen = strlen(labels[idx]);
-    Buffer_Reserve(enc, *outLen);
-    memcpy(enc->offset, labels[idx], sizeof(char) * (*outLen));
-    enc->offset += *outLen;
-    *outLen = 0;
-}
```
Comment (jbrockmendel) [inline pandas/_libs/src/ujson/python/objToJSON.c]: it looks like replacing this function with the simpler version below is orthogonal ot everything else.  am i reading it wrong?

File: pandas/tests/io/json/test_pandas.py (hunk 5 above)
Comment (jbrockmendel) [reply pandas/tests/io/json/test_pandas.py]: Given the difficulty of this PR, I'd say anything that can be broken off should be.

File: pandas/_libs/src/ujson/lib/ultrajsonenc.c (hunk 6 above)
Comment (WillAyd) [reply pandas/_libs/src/ujson/lib/ultrajsonenc.c]: No this is intentional and matches the ujson source. It essentially reverts part of #17857

**Comment by jbrockmendel** [comment]
How much of the difficulty here could be avoided by working in cython rather than C?  Moving the whole file to cython would be too much, but supposedly it is possible to make cython export a .h file so it can be used in a c file.  If I could figure out how to make this work, would that make things easier here?

File: pandas/_libs/src/ujson/python/objToJSON.c (hunk 7 above)
Comment (WillAyd) [reply pandas/_libs/src/ujson/python/objToJSON.c]: Not orthogonal just simplified. Previously since the labels would all be encoded into a buffer this function would help return the unencoded label. Instead now all labels are stored unencoded in the `char **` and can easily be accessed by index, leaving the ultimate encoding up to ujson

**Comment by WillAyd** [comment]
Good question. I don't think we would want to move the entire extension to Cython since if done correctly this should theoretically be a very small extension that dictates key / value pairs for pandas objects. 

Right now there is too much custom logic here though (ex: date time handling) which if decoupled should be moved somewhere else for shared C functions (whether Cython or hand coded), so the majority can be removed but I don't consider entire replacement a goal

**Comment by WillAyd** [comment]
Actually this could close #20500 as well. I can add a test and whatsnew for that (though again wouldn’t be round trippable)

**Comment by WillAyd** [comment]
Any objections to merging this? As is this intentionally causes a regression when writing out a DTI but I think resolvable in a follow up. This refactor should also enable some of the items linked above.

I'm catching a flight back to the US tomorrow so should have spare time to focus on follow ups. Worst case I think could revert this before 1.0.0 if those never come to fruition

**Comment by jbrockmendel** [comment]
what's the DTI regression?

**Comment by WillAyd** [comment]
Takes 1-4x as long to write out index / columns containing 100k date times. Actual benchmarks are shown in Appendix A here https://github.com/pandas-dev/pandas/pull/27618#issuecomment-519568589

The reason is that this change constructs a Timestamp object during serialization for each label, whether or not that label is stuck in an object array or a DTI. 

A more performant approach would be to check for a DTI and dispatch to a vectorized stringification for the labels, which I think would just be better done in a follow up

**Comment by jbrockmendel** [comment]
Seems totally reasonable.

File: pandas/_libs/src/ujson/python/objToJSON.c [hunk 8]
```diff
@@ -166,6 +166,8 @@ void *initObjToJSON(void)
         cls_index = (PyTypeObject *)PyObject_GetAttrString(mod_pandas, "Index");
         cls_series =
             (PyTypeObject *)PyObject_GetAttrString(mod_pandas, "Series");
+        cls_timestamp = PyObject_GetAttrString(mod_pandas, "Timestamp");
+	cls_timedelta = PyObject_GetAttrString(mod_pandas, "Timedelta");
```
Comment (TomAugspurger) [inline pandas/_libs/src/ujson/python/objToJSON.c]: Is this indentation off?

**Review by TomAugspurger — COMMENTED** [review]
I'm OK with the slowdown if we think this is more maintainable.

File: pandas/_libs/src/ujson/python/objToJSON.c (hunk 8 above)
Comment (WillAyd) [reply pandas/_libs/src/ujson/python/objToJSON.c]: I think just matching the block but generally indentation is off in the C files. We don’t have any linting here so I think a good follow up generally for extension modules. 

We have cpplint but I don’t think that really covers C code. gnu indent might be worth looking at

**Comment by WillAyd** [comment]
Sounds good. Merging for now will formalize follow ups over next few days. Worst case can always revert
