### PR TITLE
JSON Date Handling 1.0 Regressions

### LINKED ISSUE #30904: to_json doesn't work with Datetime.date
This is a regression between 0.25.3 and 1.0

```python
>>> import pandas as pd
>>> import datetime
>>> data = [datetime.date(year=2020, month=1, day=1), "a"]
>>> pd.Series(data).to_json(date_format="iso")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/williamayd/clones/pandas/pandas/core/generic.py", line 2363, in to_json
    indent=indent,
  File "/Users/williamayd/clones/pandas/pandas/io/json/_json.py", line 85, in to_json
    indent=indent,
  File "/Users/williamayd/clones/pandas/pandas/io/json/_json.py", line 145, in write
    self.indent,
  File "/Users/williamayd/clones/pandas/pandas/io/json/_json.py", line 199, in _write
    indent,
  File "/Users/williamayd/clones/pandas/pandas/io/json/_json.py", line 167, in _write
    indent=indent,
TypeError: Expected datetime object
```

Noticed while working on #30903

### PR DESCRIPTION
**Pull request by WillAyd**
closes #30904

Came across these adding parametrized tests in #30903 which this pulls some elements from but which will also ultimately refactor to avoid duplication; just getting this to work as is

To be clear the regressions were:

1. ISO dates with datetime.date objects was broken

```python
>>> import pandas as pd
>>> import datetime
>>> data = [datetime.date(year=2020, month=1, day=1), "a"]
>>> pd.Series(data).to_json(date_format="iso")
TypeError: Expected datetime object
```

2. `pd.NaT` labels would now yield the sentinel value instead of writing "null"

```python
>>> data = [pd.Timestamp("2020-01-01"), pd.NaT]
>>> pd.Series(data, index=data).to_json()
'{"1577836800000":1577836800000,"-9223372036854":null}'
```

Both have been fixed here

### CODE REVIEW

File: pandas/_libs/src/ujson/python/objToJSON.c [hunk 1]
```diff
@@ -456,7 +456,7 @@ static char *PyDateTimeToIso(PyDateTime_Date *obj, NPY_DATETIMEUNIT base,
 static char *PyDateTimeToIsoCallback(JSOBJ obj, JSONTypeContext *tc,
                                      size_t *len) {
 
-    if (!PyDateTime_Check(obj)) {
+    if (!PyDate_Check(obj)) {
         PyErr_SetString(PyExc_TypeError, "Expected datetime object");
```
Comment (jbrockmendel) [inline pandas/_libs/src/ujson/python/objToJSON.c]: should the error message say "date" instead of "datetime"?  is the call to PyDateTimeToIso below safe if we have a date and not a datetime?

Comment (WillAyd) [reply pandas/_libs/src/ujson/python/objToJSON.c]: Happy to change; was thinking about that myself just didn't want to go down a rabbit hole of cleaning this all up just yet

w.r.t your second question that error check currently doesn't actually raise an error, so I guess it's a no-op (though it probably should do something)

Comment (WillAyd) [reply pandas/_libs/src/ujson/python/objToJSON.c]: Changed commented areas to date for now; note the second would segfault if you passed it something that wasn't a date object but I think out of scope to fix here

**Review by TomAugspurger — APPROVED** [review]

**Comment by jreback** [comment]
does this have similar perf to master?

**Comment by WillAyd** [comment]
Looks like a mixed bag:

```sh
       before           after         ratio
     [d78c0616]       [25444958]
     <master>         <json-date-regr>
+         115±4ms         231±10ms     2.02  io.json.ToJSON.time_to_json('columns', 'df')
+         103±3ms         161±10ms     1.57  io.json.ToJSON.time_to_json('records', 'df')
+        205±10ms         282±20ms     1.37  io.json.ToJSON.time_to_json_wide('index', 'df_int_floats')
-        265±30ms         194±10ms     0.73  io.json.ToJSON.time_to_json_wide('split', 'df_int_float_str')
-        235±10ms          141±9ms     0.60  io.json.ToJSON.time_to_json_wide('records', 'df')
-         276±7ms          141±4ms     0.51  io.json.ToJSON.time_to_json('index', 'df_td_int_ts')

SOME BENCHMARKS HAVE CHANGED SIGNIFICANTLY.
PERFORMANCE DECREASED.
```

May want to just couple this with #30903 which has a refactor which helps performance and fixes Timedelta issues, at the cost of a little more code movement

**Comment by jbrockmendel** [comment]
@WillAyd it looks like between this and #30903 perf is a mixed bag but there are some unambiguous bug fixes?

**Comment by WillAyd** [comment]
#30903 fixes #28256 and an unreported memory leak when using datetimelike labels.

There is overlap between that and this PR. I consider this the bare minimum to fix regressions, though would have a slight inclination towards doing this and #30903 (after rebase) to keep performance the same without jumping through a ton of hoops

**Comment by jreback** [comment]
> #30903 fixes #28256 and an unreported memory leak when using datetimelike labels.
> 
> There is overlap between that and this PR. I consider this the bare minimum to fix regressions, though would have a slight inclination towards doing this and #30903 (after rebase) to keep performance the same without jumping through a ton of hoops

not averse to doing another patch to fix perf, but is there a minimal patch you can add to this one that doesn't involve timedelta (which i view as a nice-to-have); the datetimes are the regression, yes?

**Comment by WillAyd** [comment]
Yea can probably extract something out tonirrow

**Comment by WillAyd** [comment]
To keep performance inline I pulled in the encodeLabels refactor from #30903, though not doing any of the Timedelta fixes. 

To help translate the diff, just note that the code now basically checks for up front for a date-like value and converts to its nanosecond resolution (note that NPY_DATETIME includes both numpy datetimes and time deltas). That nanosecond resolution gets checked against NaT and continues further to the appropriate serializer depending on the type of object supplied and other keyword arguments

Here are the benchmarks:

```sh
       before           after         ratio
     [bc9d329b]       [c102f5b9]
     <master>         <json-date-regr>
-        242±20ms          173±2ms     0.72  io.json.ToJSON.time_to_json_wide('columns', 'df_int_floats')

SOME BENCHMARKS HAVE CHANGED SIGNIFICANTLY.
PERFORMANCE INCREASED.
```

File: pandas/_libs/src/ujson/python/objToJSON.c [hunk 2]
```diff
@@ -1615,6 +1641,10 @@ char **NpyArr_encodeLabels(PyArrayObject *labels, PyObjectEncoder *enc,
         ret[i] = PyObject_Malloc(len + 1);
         memcpy(ret[i], cLabel, len + 1);
 
+        if (is_datetimelike) {
```
Comment (WillAyd) [inline pandas/_libs/src/ujson/python/objToJSON.c]: This was a memory leak before; new structure makes it easier to clean this up

File: pandas/_libs/src/ujson/python/objToJSON.c [hunk 3]
```diff
@@ -1541,60 +1542,85 @@ char **NpyArr_encodeLabels(PyArrayObject *labels, PyObjectEncoder *enc,
...
+                cLabel = PyObject_Malloc(len);
+                strncpy(cLabel, "null", len);
             } else {
-                cLabel = PyObject_Malloc(21); // 21 chars for int64
-                sprintf(cLabel, "%" NPY_DATETIME_FMT,
-                        PyDateTimeToEpoch(item, base));
-                len = strlen(cLabel);
+                if (enc->datetimeIso) {
+                    // TODO: Vectorized Timedelta function
+                    if ((type_num == NPY_TIMEDELTA) || (PyDelta_Check(item))) {
```
Comment (WillAyd) [inline pandas/_libs/src/ujson/python/objToJSON.c]: This entire timedelta block was mostly copy / paste with a few changes at the end to fit the memory assumptions; this will be blown away by #30903

**Comment by jreback** [comment]
thanks @WillAyd
