### PR TITLE
BUG: to_json not serializing non-nanosecond numpy dt64 correctly

### LINKED ISSUE #53686: BUG: to_json returns incorrect timestamps if DatetimeIndex precision is not ns
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [x] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.

### Reproducible Example

```python
import pandas as pd
import numpy as np

d = pd.DataFrame({'testcol': pd.Series([12], index=[np.datetime64('2023-01-01T11:22:33.123456')])})
d.index = d.index.astype('datetime64[us]')

d.to_json(date_format='iso')
```

### Issue Description

With a DataFrame in which the DatetimeIndex precision has been set to _us_, the json representation is incorrect.

With the usual initialization, the DatetimeIndex has precision _ns_, and it works fine:

```python
>>> import pandas as pd
>>> d = pd.DataFrame({'testcol': pd.Series([12], index=[np.datetime64('2023-01-01T11:22:33.123456')])})
>>> d.to_json(date_format='iso')
'{"testcol":{"2023-01-01T11:22:33.123":12}}'
```

If the precision is changed (I tried it as a workaround of issue #53684 ), the date is incorrect in `to_json`:

```python
>>> d.index = d.index.astype('datetime64[us]')
>>> d
                            testcol
2023-01-01 11:22:33.123456       12

>>> d.to_json(date_format='iso')
'{"testcol":{"1970-01-20T08:36:12.153":12}}'
```

The `date_unit` parameter doesn't help, the date is still incorrect.

Other precisions fail too:

```python
>>> d.index = d.index.astype('datetime64[s]')
>>> d
                     testcol
2023-01-01 11:22:33       12

>>> d.to_json(date_format='iso')
'{"testcol":{"1970-01-01T00:00:01.672":12}}'
```

### Expected Behavior

The output of `to_json` in iso format should be `'{"testcol":{"2023-01-01T11:22:33.123456":12}}'`

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit           : 965ceca9fd796940050d6fc817707bba1c4f9bff
python           : 3.10.8.final.0
python-bits      : 64
OS               : Linux
OS-release       : 4.12.14-195-default
Version          : #1 SMP Tue May 7 10:55:11 UTC 2019 (8fba516)
machine          : x86_64
processor        : x86_64
byteorder        : little
LC_ALL           : None
LANG             : en_US.UTF-8
LOCALE           : en_US.UTF-8

pandas           : 2.0.2
numpy            : 1.24.3
pytz             : 2023.3
dateutil         : 2.8.2
setuptools       : 63.2.0
pip              : 22.2.2
Cython           : None
pytest           : 7.3.1
hypothesis       : None
sphinx           : 7.0.1
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : 4.9.2
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : 3.1.2
IPython          : 8.13.2
pandas_datareader: None
bs4              : 4.12.2
bottleneck       : None
brotli           : None
fastparquet      : None
fsspec           : None
gcsfs            : None
matplotlib       : 3.7.1
numba            : None
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : None
pyreadstat       : None
pyxlsb           : None
s3fs             : None
scipy            : 1.10.1
snappy           : None
sqlalchemy       : None
tables           : None
tabulate         : None
xarray           : None
xlrd             : 2.0.1
zstandard        : None
tzdata           : 2023.3
qtpy             : None
pyqt5            : None

</details>

### PR DESCRIPTION
**Pull request by lithomas1**
- [ ] closes #53686 (Replace xxxx with the GitHub issue number)
- [ ] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature
- [ ] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).
- [ ] Added [type annotations](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#type-hints) to new arguments/methods/functions.
- [ ] Added an entry in the latest `doc/source/whatsnew/vX.X.X.rst` file if fixing a bug or adding a new feature.

### CODE REVIEW

File: pandas/_libs/src/vendored/ujson/python/objToJSON.c [hunk 1]
```diff
@@ -1303,35 +1314,39 @@ char **NpyArr_encodeLabels(PyArrayObject *labels, PyObjectEncoder *enc,
                              "Cannot cast numpy dtype %d to long",
                              enc->npyType);
             }
-            castfunc(dataptr, &nanosecVal, 1, NULL, NULL);
+            castfunc(dataptr, &i8date, 1, NULL, NULL);
+            // copied from
+            // https://github.com/numpy/numpy/blob/c8fe278a754a271af57eaf6c7ffb2382e5a954f9/numpy/core/src/multiarray/datetime.c#L692-L701
+            dateUnit = ((PyArray_DatetimeDTypeMetaData *)dtype->c_metadata)->meta.base;
```
Comment (lithomas1) [inline pandas/_libs/src/vendored/ujson/python/objToJSON.c:1320]: This part is probably the most sketchy part of this PR.

We currently do this the exact same way numpy does it, but not sure if this is part of the public numpy C API.

FWIW, ``PyArray_DatetimeDTypeMetaData`` appears in ``ndarraytypes.h``.

File: pandas/_libs/include/pandas/datetime/date_conversions.h [hunk 2]
```diff
@@ -18,7 +18,10 @@ int scaleNanosecToUnit(npy_int64 *value, NPY_DATETIMEUNIT unit);
 // up to precision `base` e.g. base="s" yields 2020-01-03T00:00:00Z
 // while base="ns" yields "2020-01-01T00:00:00.000000000Z"
 // len is mutated to save the length of the returned string
-char *int64ToIso(int64_t value, NPY_DATETIMEUNIT base, size_t *len);
+char *int64ToIso(int64_t value,
+                 NPY_DATETIMEUNIT valueUnit,
```
Comment (WillAyd) [inline pandas/_libs/include/pandas/datetime/date_conversions.h:22]: I don't think we need to add a new argument here - shouldn't we just be using the `base` argument?

File: pandas/_libs/src/vendored/ujson/python/objToJSON.c (hunk 1 above)
Comment (WillAyd) [reply pandas/_libs/src/vendored/ujson/python/objToJSON.c:1320]: It would be better if we stuck to a method exposed in the datetime header. Does `get_datetime_metadata_from_dtype` not help here?

**Review by WillAyd — COMMENTED** [review]
Very nice

File: pandas/_libs/src/vendored/ujson/python/objToJSON.c (hunk 1 above)
Comment (lithomas1) [reply pandas/_libs/src/vendored/ujson/python/objToJSON.c:1320]: It would be nice to use that, not sure if that's public either (it's defined in ``multiarray/_datetime.h``).
Like ``PyArray_DatetimeDTypeMetaData``, it also seems to be undocumented.

Maybe one of the numpy maintainers(@seberg?) can clarify more?

File: pandas/_libs/include/pandas/datetime/date_conversions.h (hunk 2 above)
Comment (lithomas1) [reply pandas/_libs/include/pandas/datetime/date_conversions.h:22]: Base is the output unit (corresponds to ``date_unit``).

This new parameter is to indicate the input unit, aka the unit of value, (for the ``pandas_datetime_to_datetimestruct`` call).

Previously, this was hard-coded as nano.
https://github.com/pandas-dev/pandas/blob/main/pandas/_libs/src/datetime/date_conversions.c#L48

**Comment by jbrockmendel** [comment]
@lithomas1 is there a viable way to do this using values_for_json, i.e. keep this complexity out of the C code?

**Comment by lithomas1** [comment]
> @lithomas1 is there a viable way to do this using values_for_json, i.e. keep this complexity out of the C code?

Long term, we could move to using ``to_native_types`` like CSV does, and just directly feed strings to the JSON serializer (for datetime/EA types).

I don't think this PR adds too much complexity (the core changes are just ~3 lines), so maybe we can merge this for now, and then try to pull the logic for anything other than native types (e.g. ints, floats) out of the JSON C code?

**Comment by WillAyd** [comment]
The challenge with values_for_json is also that to_json has keyword arguments that control the JSON output, e.g. date_format and date_unit. Those are both handled in the serializer currently; the challenge for values_for_json would be to handle those arguments generically across EAs

File: pandas/_libs/include/pandas/datetime/date_conversions.h (hunk 2 above)
Comment (WillAyd) [reply pandas/_libs/include/pandas/datetime/date_conversions.h:22]: Ah gotcha. In that case though I think we need to take a step back and just pass in the datetimestruct along with its metadata; that would match the existing APIs for numpy like `convert_datetimestruct_to_datetime`

Any idea how hard that would be? A lot of this JSON code is spaghetti code so it may take a bit to unwind, but the current way of unwrapping to an int64 value and passing in the metadata separately is kind of confusing

Comment (lithomas1) [reply pandas/_libs/include/pandas/datetime/date_conversions.h:22]: I think the current approach is probably OK. 

numpy stores a dt64 array as an int array + the reso metadata too.
(The struct is probably some sort of convenience thing.)

I wish I could pass the entire ndarray to the datetime serialization func, but ujson seems to only operate element by element.

Comment (WillAyd) [reply pandas/_libs/include/pandas/datetime/date_conversions.h:22]: Right technically this implementation will work as long as the numpy internals don't change; which is also unlikely. But from a readability perspective it is very confusing - we've essentially decoupled the int and metadata values but are passing them back into this `int64ToIso` function. The function name would suggest an integer along would suffice but it really is two critical components. 

The semantics need to be cleaned up instead of just bolting more on here

Comment (WillAyd) [reply pandas/_libs/include/pandas/datetime/date_conversions.h:22]: Here's for instance how numpy handles this internally. Note that `convert_datetime_to_datetimestruct` is defined in their _datetime.h header, but isn't something we've vendored in our np_datetime.h; we should probably just vendor that

Also keep in mind npy_datetime is just typedef'ed from npy_int64 (see npy_common.h), so we shouldn't have to jump through too many hoops to use their methodology

Comment (lithomas1) [reply pandas/_libs/include/pandas/datetime/date_conversions.h:22]: I could pull the ``pandas_datetime_to_datetimestruct`` call out of int64ToIso (and rename that to dtstructToIso or smth).

Does that work?

Comment (WillAyd) [reply pandas/_libs/include/pandas/datetime/date_conversions.h:22]: I think what we should do is this:

1. Add the descr to the NpyArrayContext struct (type PyArray_Descr)
2. Create a function with the following signature

```c
static char* npy_datetime_to_iso_string(npy_datetime *dt, JSONTypeContext *ti, size_t *_outLen) { ... }
```

The implementation should be pretty close to NumPy's way of converting a primitive npy_datetime value to a char* string. 

If you assign `pc->PyTypeToUTF8 = npy_datetime_to_iso_string` Step 1 from the type context should give you access to the data type of the array via tc->npyarr->dtype so you don't need to add more state management to this at all

The NpyArrayContext predates my contributions to pandas so don't know the full intent, but I think it was meant to mirror numpys `PyArrayObject` type. For maybe timing reasons the `PyArrayObject` type has the `descr` struct member described in point 1 above

Comment (jbrockmendel) [reply pandas/_libs/include/pandas/datetime/date_conversions.h:22]: Does any of this get easier if https://github.com/numpy/numpy/pull/21199 is merged (once our min version catches up i guess)?

**Comment by jbrockmendel** [comment]
> values_for_json would have to handle those arguments generically across EAs

that sounds like a better long-term solution than doing more here (assuming perf is OK).  I'm happy to defer to you two on this PR in the interim.

File: pandas/_libs/include/pandas/datetime/date_conversions.h (hunk 2 above)
Comment (lithomas1) [reply pandas/_libs/include/pandas/datetime/date_conversions.h:22]: Sorry for the late reply on this.

I had a look at the approach you mentioned and it doesn't work since the NpyArrContext is cleared out in ``Object_beginTypeContext`` here at the end of the is datetime block.

https://github.com/pandas-dev/pandas/blob/dec49044fe44f2b4dd8b13f87138f0c80b31fbda/pandas/_libs/src/vendored/ujson/python/objToJSON.c#L1472-L1477

So the dtype will still have to be on the TypeContext or the encoder itself for now.
(I will try to move it back under the NpyArrContext and remove that TODO later.)

Comment (WillAyd) [reply pandas/_libs/include/pandas/datetime/date_conversions.h:22]: Ah well that is unfortunate...this stuff really needs an overhaul...in another PR on another day

File: pandas/_libs/src/vendored/ujson/python/objToJSON.c [hunk 3]
```diff
@@ -1293,7 +1301,8 @@ char **NpyArr_encodeLabels(PyArrayObject *labels, PyObjectEncoder *enc,
         }
 
         int is_datetimelike = 0;
-        npy_int64 nanosecVal;
+        npy_int64 i8date;
+        NPY_DATETIMEUNIT dateUnit = NPY_FR_ns;
```
Comment (WillAyd) [inline pandas/_libs/src/vendored/ujson/python/objToJSON.c:1305]: Is the idea here that this should default to NS for things that are stored within object arrays?

Comment (lithomas1) [reply pandas/_libs/src/vendored/ujson/python/objToJSON.c:1305]: It's for the other stuff like timedeltas and dates. We use nanosecond reso there.

I didn't try to fix those cases as well.

Comment (WillAyd) [reply pandas/_libs/src/vendored/ujson/python/objToJSON.c:1305]: What do you think it would take to handle those consistently? I don't know how common this would happen but I guess its strange to only do this for numpy-typed arrays and not object arrays that may contain datetimes

Comment (jbrockmendel) [reply pandas/_libs/src/vendored/ujson/python/objToJSON.c:1305]: knee-jerk i think that for object-dtype we should just call `str(x)` on everything and call it a day

Comment (WillAyd) [reply pandas/_libs/src/vendored/ujson/python/objToJSON.c:1305]: The object stuff definitely adds a lot of complexity that may not be worth it, but that would be a breaking change to just pass as a str. Particularly for nested containers within an object array that would not work

Comment (lithomas1) [reply pandas/_libs/src/vendored/ujson/python/objToJSON.c:1305]: I think it might work for object arrays, already.

I haven't checked yet, I'm not on the right branch. Will update later in the day.

File: pandas/_libs/src/vendored/ujson/python/objToJSON.c [hunk 4]
```diff
@@ -364,8 +366,9 @@ static char *NpyTimeDeltaToIsoCallback(JSOBJ Py_UNUSED(unused),
 /* JSON callback */
 static char *PyDateTimeToIsoCallback(JSOBJ obj, JSONTypeContext *tc,
                                      size_t *len) {
-    if (!PyDate_Check(obj)) {
-        PyErr_SetString(PyExc_TypeError, "Expected date object");
+    if (!PyDate_Check(obj) && !PyDateTime_Check(obj)) {
+        PyErr_SetString(PyExc_TypeError, "Expected date or datetime object");
+        ((JSONObjectEncoder *)tc->encoder)->errorMsg = "";
```
Comment (lithomas1) [inline pandas/_libs/src/vendored/ujson/python/objToJSON.c:371]: Off-topic, but we should be setting the errorMsg whenever we return NULL in a callback.

Otherwise, there is a possibility of a segfault, since ujson will still think it's in a valid state and try to continue encoding, instead of instantly returning (allowing the Python exception to propagate up).

File: pandas/_libs/src/vendored/ujson/python/objToJSON.c (hunk 3 above)
Comment (lithomas1) [reply pandas/_libs/src/vendored/ujson/python/objToJSON.c:1306]: Well, it turns out that this didn't work already. Sorry for the confusion.

I've fixed this in the latest commit.

File: pandas/_libs/src/vendored/ujson/python/objToJSON.c [hunk 5]
```diff
@@ -1538,13 +1550,24 @@ void Object_beginTypeContext(JSOBJ _obj, JSONTypeContext *tc) {
         tc->type = JT_UTF8;
         return;
     } else if (PyArray_IsScalar(obj, Datetime)) {
+        npy_int64 longVal;
         if (((PyDatetimeScalarObject *)obj)->obval == get_nat()) {
             tc->type = JT_NULL;
             return;
         }
+        PyArray_Descr *dtype = PyArray_DescrFromScalar(obj);
+        if (dtype->type_num == NPY_OBJECT) {
```
Comment (lithomas1) [inline pandas/_libs/src/vendored/ujson/python/objToJSON.c:1559]: Wondering if this can be removed. This shouldn't ever fail, but if it does, we'll end up with a nasty segfault.

Comment (WillAyd) [reply pandas/_libs/src/vendored/ujson/python/objToJSON.c:1559]: https://numpy.org/doc/stable/reference/c-api/array.html#c.PyArray_DescrFromScalar

Reading through that makes me think we are supposed to check we are dealing with an array scalar before even calling this function,

As far as the resulting comparison to NPY_OBJECT, I think would be better to explicitly use the `PyTypeNum_ISDATETIME` macro and error when that is not true; that would be a better and more explicit safeguard against troublesome refactors

File: pandas/_libs/src/vendored/ujson/python/objToJSON.c [hunk 6]
```diff
@@ -1538,13 +1550,24 @@ void Object_beginTypeContext(JSOBJ _obj, JSONTypeContext *tc) {
...
+            PyErr_Format(PyExc_ValueError, "Could not get resolution of datetime");
```
Comment (WillAyd) [inline pandas/_libs/src/vendored/ujson/python/objToJSON.c:1560]: Any reason we aren't returning here? Feels a bit off to let execution continue after setting error

**Review by WillAyd — APPROVED** [review]
lgtm. minor comments but OK with merging whenever you feel complete

File: pandas/_libs/src/vendored/ujson/python/objToJSON.c (hunk 5 above)
Comment (lithomas1) [reply pandas/_libs/src/vendored/ujson/python/objToJSON.c:1559]: Yeah, this whole block is in a PyArray_IsScalar if block.

File: pandas/_libs/src/vendored/ujson/python/objToJSON.c (hunk 6 above)
Comment (lithomas1) [reply pandas/_libs/src/vendored/ujson/python/objToJSON.c:1560]: My bad, updated.

**Comment by lithomas1** [comment]
gonna put this in then.

Thanks for the reviews all.
