### PR TITLE
BUG: Fix segfault in csv tokenizer

### LINKED ISSUE #28071: Loading CSV files (using `read_csv`) with blank lines between header and data rows quits Python interpreter
#### Code Sample, a copy-pastable example if possible

```
import pandas as pd # tested with pandas 25.0 using Python 3.6.8
pd.read_csv('my_csv.csv', delimiter='|', header=4, nrows=1, skip_blank_lines=False) # this makes interpreter exit without any error message

pd.read_csv('my_csv.csv', delimiter='|', header=4, nrows=2, skip_blank_lines=False) # this is fine producing output below
   int_id_1_1_1  date_2019-01-01_2019-12-31_2  ascii_str_8_8_3  double_-1.0_1.0_4  integer_-1000_1000_5
0           NaN                           NaN              NaN                NaN                   NaN
1           NaN                           NaN              NaN                NaN                   NaN
```

#### Problem description

I have been trying to load a test CSV file ("my_csv.txt", attached), which is structured in a way that there's an information text on the second row; row header line on the fifth row; and the data starts at the ninth row. As you can see in the Python code above, `read_csv` fails when `nrows=1` , but doesn't when `nrows>1`.

I think there's some uncaught bug in Pandas' `read_csv` when CSV file has blank lines between header and the start of the data rows. Thank you for your hard work maintaining and extending this very useful library.

[my_csv.txt](https://github.com/pandas-dev/pandas/files/3526892/my_csv.txt)

### PR DESCRIPTION
**Pull request by roberthdevries**
- [x] closes #28071
- [x] tests added / passed
- [x] passes `black pandas`
- [x] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [x] whatsnew entry

### CODE REVIEW

File: pandas/_libs/src/parser/tokenizer.c [hunk 1]
```diff
@@ -1189,8 +1189,13 @@ int parser_consume_rows(parser_t *self, size_t nrows) {
 
     /* cannot guarantee that nrows + 1 has been observed */
     word_deletions = self->line_start[nrows - 1] + self->line_fields[nrows - 1];
-    char_count = (self->word_starts[word_deletions - 1] +
-                  strlen(self->words[word_deletions - 1]) + 1);
+    if (word_deletions >= 1) {
```
Comment (WillAyd) [inline pandas/_libs/src/parser/tokenizer.c]: Do you have a handle on why this is required in the first place? I think there is a more general problem with the statement management that this works around (maybe OK)

File: pandas/tests/io/parser/test_textreader.py [hunk 2]
```diff
@@ -341,6 +341,16 @@ def test_empty_csv_input(self):
         df = read_csv(StringIO(), chunksize=20, header=None, names=["a", "b", "c"])
         assert isinstance(df, TextFileReader)
 
+    def test_blank_lines_between_header_and_data_rows(self):
+        ref = DataFrame(
+            [[np.nan, np.nan], [np.nan, np.nan], [1, 2], [np.nan, np.nan], [3, 4]],
+            columns=list("ab"),
+        )
+        csv = "\nheader\n\na,b\n\n\n1,2\n\n3,4"
+        for nrows in range(1, 6):
```
Comment (WillAyd) [inline pandas/tests/io/parser/test_textreader.py]: Instead of doing this can you just parametrize on the values that matter?

File: pandas/tests/io/parser/test_textreader.py [hunk 3]
```diff
@@ -341,6 +341,16 @@ def test_empty_csv_input(self):
         df = read_csv(StringIO(), chunksize=20, header=None, names=["a", "b", "c"])
         assert isinstance(df, TextFileReader)
 
+    def test_blank_lines_between_header_and_data_rows(self):
+        ref = DataFrame(
```
Comment (WillAyd) [inline pandas/tests/io/parser/test_textreader.py]: Can you add the GH issue number as a comment?

**Review by WillAyd — CHANGES_REQUESTED** [review]
Great thanks for the PR @roberthdevries . We don't get a ton of contributions to the C extensions so much appreciate what you are doing here

File: pandas/_libs/src/parser/tokenizer.c (hunk 1 above)
Comment (roberthdevries) [reply pandas/_libs/src/parser/tokenizer.c]: As I have said in the ticket, I am also not certain *why* this works (apart from the obvious fact that this guards against a negative index in the array).
I took the heuristic route and created a test and fiddled around with a couple of options (setting charcount to 0 and to 1).
As it seemed to work and did not break any other unit tests, I thought that it would be useful to submit as a PR.
However, I agree that it does not feel good not knowing exactly *why* this works.
Maybe I put too much trust in unit testing, in the sense that this may break other functionality without unit tests.

File: pandas/tests/io/parser/test_textreader.py (hunk 2 above)
Comment (roberthdevries) [reply pandas/tests/io/parser/test_textreader.py]: Can you elaborate which values you would like to see parameterized?
I basically took the example in the ticket to reproduce the issue and checked that for all sensible values for `nrows` I get the expected outcome.
The reason for this is that this covers more cases that could cause errors like the one in the original ticket due to various edge cases.

File: pandas/tests/io/parser/test_textreader.py (hunk 3 above)
Comment (roberthdevries) [reply pandas/tests/io/parser/test_textreader.py]: done

File: pandas/tests/io/parser/test_textreader.py [hunk 4]
```diff
@@ -341,6 +341,17 @@ def test_empty_csv_input(self):
         df = read_csv(StringIO(), chunksize=20, header=None, names=["a", "b", "c"])
         assert isinstance(df, TextFileReader)
 
+    def test_blank_lines_between_header_and_data_rows(self):
```
Comment (jreback) [inline pandas/tests/io/parser/test_textreader.py]: this test needs to be in test_common.py and use the all_parsers fixture so it testsed.

**Review by jreback — CHANGES_REQUESTED** [review]

File: pandas/tests/io/parser/test_textreader.py (hunk 2 above)
Comment (gfyoung) [reply pandas/tests/io/parser/test_textreader.py]: @roberthdevries : @WillAyd is asking that you use `pytest.mark.parameterize` over the `nrows` parameter.

File: pandas/_libs/src/parser/tokenizer.c (hunk 1 above)
Comment (gfyoung) [reply pandas/_libs/src/parser/tokenizer.c]: @roberthdevries : Is there a test that you added which fails when `char_count = 0` ?

File: pandas/tests/io/parser/test_textreader.py (hunk 2 above)
Comment (roberthdevries) [reply pandas/tests/io/parser/test_textreader.py]: fixed

File: pandas/_libs/src/parser/tokenizer.c (hunk 1 above)
Comment (roberthdevries) [reply pandas/_libs/src/parser/tokenizer.c]: if `char_count` is 0, there will be an endless loop. So that option was abandoned :smile:

File: pandas/tests/io/parser/test_textreader.py (hunk 4 above)
Comment (roberthdevries) [reply pandas/tests/io/parser/test_textreader.py]: done

File: pandas/_libs/src/parser/tokenizer.c (hunk 1 above)
Comment (gfyoung) [reply pandas/_libs/src/parser/tokenizer.c]: With respect to the test you wrote, this loop would manifest for all values of `nrows`

Also, add a comment about `char_count` needing to be at least one.

Comment (roberthdevries) [reply pandas/_libs/src/parser/tokenizer.c]: The original ticket only mentions `nrows=1`. I cannot guarantee that the bug would trigger on other values, only the test would not progress further than the first one.
I added the other numbers of `nrows` to be sure that my fix did not introduce unwanted behavior when multiple rows were being read.

I did some more experiments and the value that makes some kind of sense to me is `self->stream_len`. If there are no `word_deletions`, the parser must consume something, and the maximum that can be skipped is the `stream_len`.
With this value all the tests in the `pandas/tests/io/parser` directory keep working.

Comment (gfyoung) [reply pandas/_libs/src/parser/tokenizer.c]: The fact you can make that modification and still have tests passing concerns me a little.  It is hard to tell whether or not there is coverage for the `else` case.

To confirm, if you set `char_count = 0` in the `else` block, do you get test failures?  If not, you may need to add a `sprintf` debug command to see when this case ever gets hit.

Comment (roberthdevries) [reply pandas/_libs/src/parser/tokenizer.c]: I tested this case, and it passes the test just fine. (Not sure why it failed in the past).
I am investigating this a bit more, stay tuned. But for now it does not seem to matter much which value I put in there, as long as it is smaller or equal to `stream_len`

Comment (roberthdevries) [reply pandas/_libs/src/parser/tokenizer.c]: The patch is changed to `char_count = 0`. As `word_deletions == 0`, and `char_count` is used to skip characters, it seems logical to me that if `word_deletions == 0` that `char_count` must be 0 as well.

Comment (gfyoung) [reply pandas/_libs/src/parser/tokenizer.c]: I have to say that it's still a little weird that we can't pinpoint an exact reason for setting the value of `char_count`, but at least this number I can understand.  Can you add a comment to explain that reasoning?

Comment (roberthdevries) [reply pandas/_libs/src/parser/tokenizer.c]: Added

**Review by gfyoung — APPROVED** [review]

**Review by jreback — APPROVED** [review]

**Comment by jreback** [comment]
@roberthdevries pls merge master; ping on green.

**Comment by roberthdevries** [comment]
ping @jreback everything is green

**Comment by jreback** [comment]
thanks @roberthdevries
