### PR TITLE
BUG: to_json incorrectly localizes tz-naive datetimes to UTC

### LINKED ISSUE #38760: pandas.Series.to_json() incorrectly localizes tz-naive datetimes to UTC
Seemingly related but not identical to #12997
## How to reproduce the bug
Checked with pandas 0.24.2, 1.1.5 and 1.2.0.
```
import pandas as pd

index = pd.date_range(
    start='2020-12-28 00:00:00',
    end='2020-12-28 02:00:00',
    freq='1H',
)
a = pd.Series(
    data=range(3),
    index=index,
)
a.to_json(date_format='iso')
```
## Output
```
'{"2020-12-28T00:00:00.000Z":0,"2020-12-28T01:00:00.000Z":1,"2020-12-28T02:00:00.000Z":2}'
```
(Notice the "Z" indicating UTC)
## Expected output
```
'{"2020-12-28T00:00:00.000":0,"2020-12-28T01:00:00.000":1,"2020-12-28T02:00:00.000":2}'
```
(without "Z")

### PR DESCRIPTION
**Pull request by lithomas1**
- [ ] closes #38760 (Replace xxxx with the Github issue number)
- [ ] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature
- [ ] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).
- [ ] Added an entry in the latest `doc/source/whatsnew/vX.X.X.rst` file if fixing a bug or adding a new feature.

### CODE REVIEW

File: pandas/_libs/src/ujson/python/date_conversions.c [hunk 1]
```diff
@@ -90,7 +90,32 @@ char *PyDateTimeToIso(PyObject *obj, NPY_DATETIMEUNIT base,
 
     *len = (size_t)get_datetime_iso_8601_strlen(0, base);
     char *result = PyObject_Malloc(*len);
-    ret = make_iso_8601_datetime(&dts, result, *len, base);
+    // Check to see if PyDateTime has a timezone.
+    // Don't convert to UTC if it doesn't.
+    int is_tz_aware = 0;
```
Comment (WillAyd) [inline pandas/_libs/src/ujson/python/date_conversions.c:95]: Can you just make this its own function?

File: pandas/_libs/src/ujson/python/date_conversions.c [hunk 2]
```diff
@@ -90,7 +90,32 @@ char *PyDateTimeToIso(PyObject *obj, NPY_DATETIMEUNIT base,
...
+    PyObject *tmp;
+    PyObject *offset;
+    if (PyObject_HasAttrString((PyObject*)obj, "tzinfo")) {
```
Comment (WillAyd) [inline pandas/_libs/src/ujson/python/date_conversions.c:98]: Can you remove the cast?

File: pandas/_libs/src/ujson/python/objToJSON.c [hunk 3]
```diff
@@ -707,6 +717,22 @@ void PdBlock_iterBegin(JSOBJ _obj, JSONTypeContext *tc) {
 
     for (i = 0; i < PyObject_Length(arrays); i++) {
         array = PyList_GET_ITEM(arrays, i);
+        // tz information is lost when dt64tz is converted
+        // to numpy arrays.
+        // TODO(lithomas1): Patch column_arrays(actually values_for_json)
```
Comment (WillAyd) [inline pandas/_libs/src/ujson/python/objToJSON.c:722]: How hard is it to patch values_for_json instead? We have a few branches in this function already would be ideal to not add more

Comment (WillAyd) [inline pandas/_libs/src/ujson/python/objToJSON.c:722]: How hard is it to patch values_for_json instead? We have a few branches in this function already would be ideal to not add more

File: pandas/_libs/src/ujson/python/date_conversions.c [hunk 4]
```diff
@@ -90,7 +90,32 @@ char *PyDateTimeToIso(PyObject *obj, NPY_DATETIMEUNIT base,
...
+        tmp = PyObject_GetAttrString(obj, "tzinfo");
+        if (tmp == NULL) {
+            return NULL;
+        }
+        if (tmp == Py_None) {
```
Comment (WillAyd) [inline pandas/_libs/src/ujson/python/date_conversions.c:103]: I think if you make the invariant here `tmp != Py_None` you can refactor and just do `Py_DECREF(tmp)` outside of the branches to reduce code duplication a bit

Comment (WillAyd) [inline pandas/_libs/src/ujson/python/date_conversions.c:103]: I think if you make the invariant here `tmp != Py_None` you can refactor and just do `Py_DECREF(tmp)` outside of the branches to reduce code duplication a bit

**Review by WillAyd — COMMENTED** [review]
Wow great start. A few things I think we can improve upon but this looks great

File: pandas/_libs/src/ujson/python/objToJSON.c [hunk 5]
```diff
@@ -221,8 +221,18 @@ static PyObject *get_values(PyObject *obj) {
         // The special cases to worry about are dt64tz and category[dt64tz].
         //  In both cases we want the UTC-localized datetime64 ndarray,
         //  without going through and object array of Timestamps.
```
Comment (lithomas1) [inline pandas/_libs/src/ujson/python/objToJSON.c:223]: @WillAyd In my current (very rough) implementation of this, I've decided to force an array of Timestamps(not sure what the perf/behavior implications of this would be). 

Alternatively, I could try to just use the dt64 ndarray, and grab the tz of the DTA(as the tz should be the same). Then, I can probably store this inside the JSONTypeContext and pass that through to int64ToISO function. This muddles up the code a little, since numpy dt64 objects are supposed to be tz-naive and PyDateTimetoISO should really be handling this case.

Do you have a preference for one way or the other?
(also cc @jbrockmendel who may have an opinion)

File: pandas/_libs/src/ujson/python/objToJSON.c (hunk 3 above)
Comment (lithomas1) [reply pandas/_libs/src/ujson/python/objToJSON.c:722]: Haven't tried yet, will try soon. Was just trying to slash and burn my way to a prototype that works. Assuming that the json code is the only thing that uses values_for_json, this should be fairly straightforward.

File: pandas/_libs/src/ujson/python/date_conversions.c (hunk 2 above)
Comment (jbrockmendel) [reply pandas/_libs/src/ujson/python/date_conversions.c:98]: could cast to PyDateTime or whatever up-front and use something like _PyDateTime_HAS_TZINFO instead of hasttr/getattr?

Comment (lithomas1) [reply pandas/_libs/src/ujson/python/date_conversions.c]: Will try to use datetime C API in followup. Unfortunately, this PR is getting a little large already.

File: pandas/_libs/src/ujson/python/date_conversions.c [hunk 6]
```diff
@@ -54,8 +54,8 @@ char *int64ToIso(int64_t value, NPY_DATETIMEUNIT base, size_t *len) {
         PyErr_NoMemory();
         return NULL;
     }
-
-    ret_code = make_iso_8601_datetime(&dts, result, *len, base);
+    ret_code = make_iso_8601_datetime(&dts, result, *len,
```
Comment (jreback) [inline pandas/_libs/src/ujson/python/date_conversions.c:57]: can you make the comment inline with `//` rather than this as its very hard to read

File: pandas/tests/io/json/test_pandas.py [hunk 7]
```diff
@@ -1192,6 +1188,16 @@ def test_tz_is_utc(self, ts):
         dt = ts.to_pydatetime()
         assert dumps(dt, iso_dates=True) == exp
 
+    def test_tz_is_naive(self):
+        from pandas.io.json import dumps
```
Comment (jreback) [inline pandas/tests/io/json/test_pandas.py:1192]: is there a reason this is imported here? i c this is done else where, can you fix this.

**Review by jreback — CHANGES_REQUESTED** [review]
needs a big whatsnew note

File: pandas/tests/io/json/test_pandas.py (hunk 7 above)
Comment (lithomas1) [reply pandas/tests/io/json/test_pandas.py:1192]: In the tests, we test both our internal ``pandas._libs.json.dumps`` method and ``json.dumps`` (from the stdlib). It's best to import it inside the function to avoid conflicts between the names.

File: pandas/_libs/src/ujson/python/date_conversions.c (hunk 6 above)
Comment (WillAyd) [reply pandas/_libs/src/ujson/python/date_conversions.c]: @lithomas1 you *might* be able to just run clang-format to do this automatically while cleaning up the rest of the code. Can't remember if done to this file already but definitely done with other files in the past

[28144](https://github.com/pandas-dev/pandas/pull/28144#issuecomment-524687696)

File: pandas/_libs/tslibs/src/datetime/np_datetime.c [hunk 8]
```diff
@@ -331,6 +331,34 @@ int cmp_npy_datetimestruct(const npy_datetimestruct *a,
 
     return 0;
 }
+/*
+* Returns the offset from utc of the timezone.
+* If the passed object is timezone naive, or if extraction
```
Comment (WillAyd) [inline pandas/_libs/tslibs/src/datetime/np_datetime.c:336]: I would advise against having NULL mean potentially two different things. I think it would be cleanest if NULL explicitly signaled an error, so that handlers know to either pass that back up the stack or check the error message and handle accordingly. We can just add checks for None in callers of this right?

https://docs.python.org/3/c-api/exceptions.html#exception-handling

File: pandas/core/internals/blocks.py [hunk 9]
```diff
@@ -1989,6 +1987,12 @@ class DatetimeTZBlock(DatetimeLikeBlock):
     _validate_ndim = True
     _can_consolidate = False
 
+    def values_for_json(self) -> np.ndarray:
+        # force dt64tz to go through object dtype
+        # tz info will be lost when converting to
+        # dt64 which is naive
+        return self.values.astype(object)
```
Comment (jbrockmendel) [inline pandas/core/internals/blocks.py:1994]: with this change, behavior is equivalent to just removing both this and DatimeLikeBlock.values_for_json.  Might mean a perf hit for dt64naive and td64 though

File: pandas/_libs/tslibs/src/datetime/np_datetime.c (hunk 8 above)
Comment (WillAyd) [reply pandas/_libs/tslibs/src/datetime/np_datetime.c:336]: Alternately you can move the hasattr check and do that before calling the function. That is likely the most explicit way of handling

File: pandas/core/internals/blocks.py (hunk 9 above)
Comment (lithomas1) [reply pandas/core/internals/blocks.py:1994]: Sorry, I'm not sure I follow here about dt64naive and td64. 
Don't those go through DatetimeLikeBlock instead of DatetimeTZBlock? (I didn't change any behavior there).

File: pandas/_libs/src/ujson/python/date_conversions.c (hunk 6 above)
Comment (lithomas1) [reply pandas/_libs/src/ujson/python/date_conversions.c]: I guess cpplint didn't catch this one 🤷 . I develop mainly on Windows so I don't really use clang(Can one install clang-format without clang?).

Anyways, fixed the formatting.

File: pandas/_libs/src/ujson/python/objToJSON.c (hunk 5 above)
Comment (lithomas1) [reply pandas/_libs/src/ujson/python/objToJSON.c:223]: I added the test. Can you elaborate more about how to handle this in the serializer?
I don't see anywhere else where I could store the tz info other than in the TypeContext.

I guess the way it is handled now is fine, but it would be nice to avoid the performance hit from casting to object.

Comment (WillAyd) [reply pandas/_libs/src/ujson/python/objToJSON.c:223]: You might get away with storing this information in the `NpyArrayContext` since that already has the type number from NumPy. My hesitation with TypeContext is that it is already pretty sparsely overloaded for different types so its difficult to debug and figure out the intent of it within various contexts

File: pandas/core/internals/blocks.py (hunk 9 above)
Comment (jbrockmendel) [reply pandas/core/internals/blocks.py:1994]: right.  what im saying is that i think NDArrayBackedBlock.values_for_json works, so no longer needs to be overridden

File: doc/source/whatsnew/v1.5.0.rst [hunk 10]
```diff
@@ -175,10 +175,17 @@ Styler
...
 
-notable_bug_fix2
-^^^^^^^^^^^^^^^^
+Serializing tz-naive Timestamps with to_json() with ``iso_dates=True``
+^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
+
+:meth:`DataFrame.to_json`, :meth:`Series.to_json`, and :meth:`Index.to_json`
+would incorrectly localize DatetimeArrays/DatetimeIndexes with tz-naive Timestamps
+to UTC. (:issue:`38760`)
+
```
Comment (jreback) [inline doc/source/whatsnew/v1.5.0.rst:186]: can you show previously what the output and what the new output is.

**Review by jreback — CHANGES_REQUESTED** [review]

File: pandas/_libs/tslibs/src/datetime/np_datetime.c [hunk 11]
```diff
@@ -332,32 +332,31 @@ int cmp_npy_datetimestruct(const npy_datetimestruct *a,
...
-            PyObject *offset = PyObject_CallMethod(tmp, "utcoffset", "O", obj);
-            if (offset == NULL) {
-                Py_DECREF(tmp);
-                return NULL;
-            }
-            if (offset != Py_None) {
-                return offset;
-            }
-            Py_DECREF(offset);
+        if (offset != Py_None) {
```
Comment (WillAyd) [inline pandas/_libs/tslibs/src/datetime/np_datetime.c:355]: Do we even need this branching down here or can we not just `return tmp`?

File: pandas/_libs/src/ujson/python/date_conversions.c [hunk 12]
```diff
@@ -93,10 +93,14 @@ char *PyDateTimeToIso(PyObject *obj, NPY_DATETIMEUNIT base,
     // Check to see if PyDateTime has a timezone.
     // Don't convert to UTC if it doesn't.
     int is_tz_aware = 0;
-    PyObject *offset = extract_utc_offset(obj);
-    if (offset != NULL) {
-        is_tz_aware = 1;
-        Py_DECREF(offset);
+    if (PyObject_HasAttrString(obj, "tzinfo")) {
+        PyObject *offset = extract_utc_offset(obj);
+        if (offset != NULL) {
```
Comment (WillAyd) [inline pandas/_libs/src/ujson/python/date_conversions.c:98]: I think if you get NULL back from `extract_utc_offset` you still want to propogate up the stack, so would be better to do something like:

```
if (offset == NULL) {
  return NULL;
}

is_tz_aware = offset != Py_None;
...
...
```

**Comment by lithomas1** [comment]
Sorry for the low quality code. I was prototyping quickly and forgot to clean up afterwards.

Regarding https://github.com/pandas-dev/pandas/pull/46730/#discussion_r856421763, I think I'll stick to the current approach for now. Existing perf benchmarks surprisingly seem unaffected by this change, so not sure its worth pursuing at least for now(it might be worth doing for the tz-aware case later).

File: pandas/core/internals/blocks.py (hunk 9 above)
Comment (lithomas1) [reply pandas/core/internals/blocks.py:1994]: I'll take care of this in a follow up.

File: pandas/_libs/src/ujson/python/date_conversions.c [hunk 13]
```diff
@@ -90,7 +90,18 @@ char *PyDateTimeToIso(PyObject *obj, NPY_DATETIMEUNIT base,
...
     *len = (size_t)get_datetime_iso_8601_strlen(0, base);
     char *result = PyObject_Malloc(*len);
-    ret = make_iso_8601_datetime(&dts, result, *len, base);
+    // Check to see if PyDateTime has a timezone.
+    // Don't convert to UTC if it doesn't.
+    int is_tz_aware = 0;
+    if (PyObject_HasAttrString(obj, "tzinfo")) {
+        PyObject *offset = extract_utc_offset(obj);
+        if (offset == NULL) {
+            return NULL;
```
Comment (WillAyd) [inline pandas/_libs/src/ujson/python/date_conversions.c:99]: Looks like we also need to `PyObject_Free(result)` before returning if things fail to avoid any leaks

**Review by WillAyd — COMMENTED** [review]
one last nit otherwise this lgtm

**Review by WillAyd — APPROVED** [review]
Lgtm - impressive work

**Review by jreback — APPROVED** [review]

**Comment by jreback** [comment]
thanks @lithomas1 very nice!

I believe there is a de-duplication followup (values_for_json) if you can
