### PR TITLE
BUG: fix memory leak in JSON datetime serialization

### LINKED ISSUE #62204: BUG: memory leak in to_json when converting DateTime values
### Pandas version checks

- [x] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [x] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.

### Reproducible Example

```python
import pandas as pd
while True:
    dr = pd.date_range(start='1/1/2019', end='1/2/2019', freq='s', tz='UTC')
    df = pd.DataFrame({'col1': [12.34]}, index=dr)
    df.reset_index().to_json(orient='values', date_format='iso')
```

### Issue Description

There appears to be a memory leak in Pandas `to_json()` when converting DateTime values.  When running the reproducer, the system's memory use will continuously increase.

### Expected Behavior

Memory use should be stable.

### Installed Versions

<details>
__
INSTALLED VERSIONS
------------------
commit                : 4665c10899bc413b639194f6fb8665a5c70f7db5
python                : 3.11.13
python-bits           : 64
OS                    : Linux
OS-release            : 6.14.0-1012-aws
Version               : #12~24.04.1-Ubuntu SMP Fri Aug 15 00:16:05 UTC 2025
machine               : x86_64
processor             : x86_64
byteorder             : little
LC_ALL                : None
LANG                  : C.UTF-8
LOCALE                : en_US.UTF-8

pandas                : 2.3.2
numpy                 : 2.3.2
pytz                  : 2025.2
dateutil              : 2.9.0.post0
pip                   : 24.0
Cython                : None
sphinx                : None
IPython               : None
adbc-driver-postgresql: None
adbc-driver-sqlite    : None
bs4                   : None
blosc                 : None
bottleneck            : None
dataframe-api-compat  : None
fastparquet           : None
fsspec                : None
html5lib              : None
hypothesis            : None
gcsfs                 : None
jinja2                : None
lxml.etree            : None
matplotlib            : None
numba                 : None
numexpr               : None
odfpy                 : None
openpyxl              : None
pandas_gbq            : None
psycopg2              : None
pymysql               : None
pyarrow               : None
pyreadstat            : None
pytest                : None
python-calamine       : None
pyxlsb                : None
s3fs                  : None
scipy                 : None
sqlalchemy            : None
tables                : None
tabulate              : None
xarray                : None
xlrd                  : None
xlsxwriter            : None
zstandard             : None
tzdata                : 2025.2
qtpy                  : None
pyqt5                 : None

</details>

### PR DESCRIPTION
**Pull request by Alvaro-Kothe**
- [x] closes #62204 (Replace xxxx with the GitHub issue number)
- [ ] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature
- [ ] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).
- [ ] Added [type annotations](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#type-hints) to new arguments/methods/functions.
- [ ] Added an entry in the latest `doc/source/whatsnew/vX.X.X.rst` file if fixing a bug or adding a new feature.

### CODE REVIEW

**Comment by swt2c** [comment]
Thanks @Alvaro-Kothe, I can confirm this resolves the memory leak that I am seeing.  Also, your solution makes sense.

:+1:

**Review by swt2c — COMMENTED** [review]
I think you might also need to add a `GET_TC(tc)->freeCStr = 1;` in `Object_getBigNumStringValue`

**Comment by Alvaro-Kothe** [comment]
Thanks for pointing that out. Just fixed it.

File: pandas/_libs/src/vendored/ujson/python/objToJSON.c [hunk 1]
```diff
@@ -107,6 +107,7 @@ typedef struct __TypeContext {
   JSINT64 longValue;
 
   const char *cStr;
+  int freeCStr;
```
Comment (WillAyd) [inline pandas/_libs/src/vendored/ujson/python/objToJSON.c]: Generally the problem with the JSON code is that over time we have incrementally added many different state management operations, and it is not always clear how they should work in tandem. So I am a little hesitant to add more state to solve the current issue. Is it possible to solve the issue without changing this struct?

Comment (swt2c) [reply pandas/_libs/src/vendored/ujson/python/objToJSON.c]: Any suggestions on how to do that?  Revert the changes in https://github.com/pandas-dev/pandas/commit/fb6c4e33c45938d7675d4c9a132324cd08df2f3c that make some of the uses of `cStr` stack allocated?  It doesn't seem possible to make all uses of `cStr` stack allocated, at least at first glance.

Comment (WillAyd) [reply pandas/_libs/src/vendored/ujson/python/objToJSON.c]: Sure that might be a reasonable approach

Comment (Alvaro-Kothe) [reply pandas/_libs/src/vendored/ujson/python/objToJSON.c]: I removed the `freeCStr` flag and stored all the strings assigned in `*IterNext` in dynamic memory.

File: pandas/_libs/src/vendored/ujson/python/objToJSON.c [hunk 2]
```diff
@@ -1880,6 +1905,7 @@ static void Object_endTypeContext(JSOBJ Py_UNUSED(obj), JSONTypeContext *tc) {
     GET_TC(tc)->rowLabels = NULL;
     NpyArr_freeLabels(GET_TC(tc)->columnLabels, GET_TC(tc)->columnLabelsLen);
     GET_TC(tc)->columnLabels = NULL;
+    PyObject_Free((void *)GET_TC(tc)->cStr);
```
Comment (WillAyd) [inline pandas/_libs/src/vendored/ujson/python/objToJSON.c]: I'm not too sure about this approach - generally the CPython API only wants you to call this function when you've allocated with the corresponding function(s)

https://docs.python.org/3/c-api/memory.html#c.PyObject_Free

> Frees the memory block pointed to by p, which must have been returned by a previous call to [PyObject_Malloc()](https://docs.python.org/3/c-api/memory.html#c.PyObject_Malloc), [PyObject_Realloc()](https://docs.python.org/3/c-api/memory.html#c.PyObject_Realloc) or [PyObject_Calloc()](https://docs.python.org/3/c-api/memory.html#c.PyObject_Calloc). Otherwise, or if PyObject_Free(p) has been called before, undefined behavior occurs.

Comment (WillAyd) [reply pandas/_libs/src/vendored/ujson/python/objToJSON.c]: Ah sorry I misread your PR. I see you allocate 20 bytes to `cStr`, so this is clean in that regards. However, I think you want to use the `PyMem_` functions since we are dealing with raw C constructs and not Python objects, so maybe replace this with `PyMem_Free`, any `PyObject_Malloc` calls with `PyMem_Malloc`

Comment (swt2c) [reply pandas/_libs/src/vendored/ujson/python/objToJSON.c]: Unless I'm missing something, `PyObject_Free()` is being called on memory that's been allocated with `PyObject_Malloc()`...

File: pandas/_libs/src/vendored/ujson/python/objToJSON.c [hunk 3]
```diff
@@ -1007,16 +1008,24 @@ static const char *List_iterGetName(JSOBJ Py_UNUSED(obj),
 //=============================================================================
 static void Index_iterBegin(JSOBJ Py_UNUSED(obj), JSONTypeContext *tc) {
   GET_TC(tc)->index = 0;
+  GET_TC(tc)->cStr = PyObject_Malloc(20);
```
Comment (WillAyd) [inline pandas/_libs/src/vendored/ujson/python/objToJSON.c]: Its probably better to create a static const variable for a size within the module, rather than repeating the hard-coded 20 multiple times

File: pandas/_libs/src/vendored/ujson/python/objToJSON.c [hunk 4]
```diff
@@ -1007,16 +1008,24 @@ static const char *List_iterGetName(JSOBJ Py_UNUSED(obj),
...
 static int Index_iterNext(JSOBJ obj, JSONTypeContext *tc) {
   const Py_ssize_t index = GET_TC(tc)->index;
   Py_XDECREF(GET_TC(tc)->itemValue);
+  if (!GET_TC(tc)->cStr) {
+    return 0;
+  }
+
   if (index == 0) {
-    GET_TC(tc)->cStr = "name";
+    strcpy((char *)GET_TC(tc)->cStr, "name");
```
Comment (WillAyd) [inline pandas/_libs/src/vendored/ujson/python/objToJSON.c]: I think if you want to use strcpy here you will need to drop the const qualifier on the struct member; casting away const-ness like this is going to trigger undefined behavior

File: pandas/_libs/src/vendored/ujson/python/objToJSON.c (hunk 2 above)
Comment (WillAyd) [inline pandas/_libs/src/vendored/ujson/python/objToJSON.c]: Why cast to a void pointer here?

**Review by WillAyd — CHANGES_REQUESTED** [review]
Are there any object types where it is possible to go through the destructor without initializing the `cStr` member? Looking at say the dict iteration code it seems like that may be happening?

Its a bit confusing here that the type context begin functions have an implicit requirement to allocate the `cStr` member. I wonder if it wouldn't be cleaner to allocate that up front, and leave it to individual functions to free or replace memory as required

File: pandas/_libs/src/vendored/ujson/python/objToJSON.c (hunk 2 above)
Comment (Alvaro-Kothe) [reply pandas/_libs/src/vendored/ujson/python/objToJSON.c]: It was because of the const qualifier in `cStr`, but since I removed this qualifier, I am no longer casting.

File: pandas/_libs/src/vendored/ujson/python/objToJSON.c (hunk 4 above)
Comment (Alvaro-Kothe) [reply pandas/_libs/src/vendored/ujson/python/objToJSON.c]: I removed the `const` qualifier.

File: pandas/_libs/src/vendored/ujson/python/objToJSON.c (hunk 3 above)
Comment (Alvaro-Kothe) [reply pandas/_libs/src/vendored/ujson/python/objToJSON.c]: I created the variable `CSTR_SIZE`

File: pandas/_libs/src/datetime/date_conversions.c [hunk 5]
```diff
@@ -49,7 +49,7 @@ char *int64ToIso(int64_t value, NPY_DATETIMEUNIT valueUnit,
   pandas_datetime_to_datetimestruct(value, valueUnit, &dts);
 
   *len = (size_t)get_datetime_iso_8601_strlen(0, base);
-  char *result = PyObject_Malloc(*len);
+  char *result = PyMem_Malloc(*len);
```
Comment (WillAyd) [inline pandas/_libs/src/datetime/date_conversions.c]: Since the focus of the PR is to fix the JSON modules, let's leave the others untouched for now. These may be viable fixes, but they can always be done in a follow up

Comment (WillAyd) [reply pandas/_libs/src/datetime/date_conversions.c]: Ah nevermind - I guess you are doing this because the JSON module makes use of this function

Comment (Alvaro-Kothe) [reply pandas/_libs/src/datetime/date_conversions.c]: Exacly, I made this change because of the assignment of `cStr` in `NpyDateTimeToIsoCallback`.

 I also made changes in other functions to allocate with `PyMem_Malloc` in `int64ToIsoDuration` and `PyDateTimeToIso`, but I think that the CI errors are because of this changes. Is it correct to use `PyMem_Malloc` in them or should I change back to `PyObject_Malloc`?

**Comment by WillAyd** [comment]
@Alvaro-Kothe the address and undefined behavior violations can be pretty tricky to debug. If you aren't aware, you can turn on sanitizers locally to better understand what is happening (assuming your compiler supports them):

```
python -m pip install -e . -Csetup-args="-Db_sanitize=address,undefined" -Csetupargs="-Dbuildtype=debug"
```

File: pandas/_libs/src/datetime/date_conversions.c (hunk 5 above)
Comment (WillAyd) [reply pandas/_libs/src/datetime/date_conversions.c]: Strange - I don't think PyObject_Malloc is correct. Upstream, it looks like they have made a similar change (see https://github.com/python/cpython/issues/114569)

However, if its a blocker for now sure lets stick with the PyObject_ functions; can figure out the rest later

File: pandas/_libs/src/vendored/ujson/python/objToJSON.c [hunk 6]
```diff
@@ -1880,6 +1907,7 @@ static void Object_endTypeContext(JSOBJ Py_UNUSED(obj), JSONTypeContext *tc) {
     GET_TC(tc)->rowLabels = NULL;
     NpyArr_freeLabels(GET_TC(tc)->columnLabels, GET_TC(tc)->columnLabelsLen);
     GET_TC(tc)->columnLabels = NULL;
+    PyObject_Free(GET_TC(tc)->cStr);
```
Comment (WillAyd) [inline pandas/_libs/src/vendored/ujson/python/objToJSON.c:1910]: Can you double check the paths that actually hit this? Right now it seems like we either implicitly have some kind of relation with the types allocate storage for the struct member and this function getting called, or we have undefined behavior when always calling free here, if the type doesn't allocate this in the first place

**Review by WillAyd — COMMENTED** [review]
Cool nice work

File: pandas/_libs/src/vendored/ujson/python/objToJSON.c (hunk 6 above)
Comment (Alvaro-Kothe) [reply pandas/_libs/src/vendored/ujson/python/objToJSON.c:1910]: I checked these paths where `cStr` is assigned to a dynamic memory allocated with `PyObject_Malloc`:
- `NpyDateTimeToIsoCallback -> int64ToIso`
- `NpyTimeDeltaToIsoCallback -> int64ToIsoDuration`
- `PyDateTimeToIsoCallback -> PyDateTimeToIso`
- `Index_iterBegin`
- `Series_iterBegin`
- `DataFrame_iterBegin`
- `Object_getBigNumStringValue`

There is no `*_Free` call for `cStr` outside of the `Object_endTypeContext` function to cause an undefined behaviour. 

Other cases seems like `cStr` isn't assigned and end up being `NULL`, making the `PyObject_Free` a [no-op](https://docs.python.org/3/c-api/memory.html#c.PyObject_Free).

**Review by WillAyd — APPROVED** [review]

**Comment by WillAyd** [comment]
Great thanks @Alvaro-Kothe ! Definitely open to any other improvements you can find here
