### PR TITLE
Fix validation error type `SS05` and check in CI 

### LINKED ISSUE #25112: Fix validation error type `SS05` and check in CI
#### Problem description
In order to have a continuous check by the CI on validation error `SS05` (Summary must start with infinitive verb, not third person), fixing them in the code base enables the addition to the CI for automated testing in the future.

`SS05` has just 52 occurrences (see [overview of the errors](https://gist.github.com/198cfa552c727d71bd7360fda66fdbb4)):

method | file | file_line | github_link
-- | -- | -- | --
pandas.core.resample.Resampler.get_group | pandas/core/groupby/groupby.py | 626.0 | https://github.com/pandas-dev/pandas/blob/master/pandas/core/groupby/groupby.py#L626
pandas.core.resample.Resampler.nunique | pandas/core/resample.py | 877.0 | https://github.com/pandas-dev/pandas/blob/master/pandas/core/resample.py#L877
pandas.api.extensions.register_extension_dtype | pandas/core/dtypes/dtypes.py | 19.0 | https://github.com/pandas-dev/pandas/blob/master/pandas/core/dtypes/dtypes.py#L19
pandas.core.groupby.GroupBy.get_group | pandas/core/groupby/groupby.py | 626.0 | https://github.com/pandas-dev/pandas/blob/master/pandas/core/groupby/groupby.py#L626
pandas.core.groupby.GroupBy.all | pandas/core/groupby/groupby.py | 1059.0 | https://github.com/pandas-dev/pandas/blob/master/pandas/core/groupby/groupby.py#L1059
pandas.core.groupby.GroupBy.any | pandas/core/groupby/groupby.py | 1046.0 | https://github.com/pandas-dev/pandas/blob/master/pandas/core/groupby/groupby.py#L1046
pandas.core.groupby.GroupBy.head | pandas/core/groupby/groupby.py | 2039.0 | https://github.com/pandas-dev/pandas/blob/master/pandas/core/groupby/groupby.py#L2039
pandas.core.groupby.GroupBy.rank | pandas/core/groupby/groupby.py | 1811.0 | https://github.com/pandas-dev/pandas/blob/master/pandas/core/groupby/groupby.py#L1811
pandas.core.groupby.GroupBy.tail | pandas/core/groupby/groupby.py | 2067.0 | https://github.com/pandas-dev/pandas/blob/master/pandas/core/groupby/groupby.py#L2067
pandas.core.groupby.DataFrameGroupBy.all | pandas/core/groupby/groupby.py | 1059.0 | https://github.com/pandas-dev/pandas/blob/master/pandas/core/groupby/groupby.py#L1059
pandas.core.groupby.DataFrameGroupBy.any | pandas/core/groupby/groupby.py | 1046.0 | https://github.com/pandas-dev/pandas/blob/master/pandas/core/groupby/groupby.py#L1046
pandas.core.groupby.DataFrameGroupBy.rank | pandas/core/groupby/groupby.py | 1811.0 | https://github.com/pandas-dev/pandas/blob/master/pandas/core/groupby/groupby.py#L1811
pandas.core.groupby.SeriesGroupBy.nunique | pandas/core/groupby/generic.py | 1023.0 | https://github.com/pandas-dev/pandas/blob/master/pandas/core/groupby/generic.py#L1023
pandas.plotting.andrews_curves | pandas/util/_decorators.py | 272.0 | https://github.com/pandas-dev/pandas/blob/master/pandas/util/_decorators.py#L272
pandas.Series.put | pandas/core/series.py | 581.0 | https://github.com/pandas-dev/pandas/blob/master/pandas/core/series.py#L581
pandas.Series.keys | pandas/core/series.py | 1457.0 | https://github.com/pandas-dev/pandas/blob/master/pandas/core/series.py#L1457
pandas.Series.lt | pandas/core/ops.py | 1864.0 | https://github.com/pandas-dev/pandas/blob/master/pandas/core/ops.py#L1864
pandas.Series.le | pandas/core/ops.py | 1864.0 | https://github.com/pandas-dev/pandas/blob/master/pandas/core/ops.py#L1864
pandas.Series.rolling | pandas/core/generic.py | 10145.0 | https://github.com/pandas-dev/pandas/blob/master/pandas/core/generic.py#L10145
pandas.Series.expanding | pandas/core/generic.py | 10156.0 | https://github.com/pandas-dev/pandas/blob/master/pandas/core/generic.py#L10156
pandas.Series.ewm | pandas/core/generic.py | 10164.0 | https://github.com/pandas-dev/pandas/blob/master/pandas/core/generic.py#L10164
pandas.Series.argsort | pandas/core/series.py | 2988.0 | https://github.com/pandas-dev/pandas/blob/master/pandas/core/series.py#L2988
pandas.Series.str.len | pandas/core/strings.py | 1737.0 | https://github.com/pandas-dev/pandas/blob/master/pandas/core/strings.py#L1737
pandas.Series.cat.rename_categories | pandas/core/accessor.py | 94.0 | https://github.com/pandas-dev/pandas/blob/master/pandas/core/accessor.py#L94
pandas.Series.cat.reorder_categories | pandas/core/accessor.py | 94.0 | https://github.com/pandas-dev/pandas/blob/master/pandas/core/accessor.py#L94
pandas.Series.cat.remove_categories | pandas/core/accessor.py | 94.0 | https://github.com/pandas-dev/pandas/blob/master/pandas/core/accessor.py#L94
pandas.Series.cat.remove_unused_categories | pandas/core/accessor.py | 94.0 | https://github.com/pandas-dev/pandas/blob/master/pandas/core/accessor.py#L94
pandas.Series.cat.set_categories | pandas/core/accessor.py | 94.0 | https://github.com/pandas-dev/pandas/blob/master/pandas/core/accessor.py#L94
pandas.Index.equals | pandas/core/indexes/base.py | 4050.0 | https://github.com/pandas-dev/pandas/blob/master/pandas/core/indexes/base.py#L4050
pandas.Index.asof_locs | pandas/core/indexes/base.py | 4145.0 | https://github.com/pandas-dev/pandas/blob/master/pandas/core/indexes/base.py#L4145
pandas.CategoricalIndex.rename_categories | pandas/core/accessor.py | 94.0 | https://github.com/pandas-dev/pandas/blob/master/pandas/core/accessor.py#L94
pandas.CategoricalIndex.reorder_categories | pandas/core/accessor.py | 94.0 | https://github.com/pandas-dev/pandas/blob/master/pandas/core/accessor.py#L94
pandas.CategoricalIndex.remove_categories | pandas/core/accessor.py | 94.0 | https://github.com/pandas-dev/pandas/blob/master/pandas/core/accessor.py#L94
pandas.CategoricalIndex.remove_unused_categories | pandas/core/accessor.py | 94.0 | https://github.com/pandas-dev/pandas/blob/master/pandas/core/accessor.py#L94
pandas.CategoricalIndex.set_categories | pandas/core/accessor.py | 94.0 | https://github.com/pandas-dev/pandas/blob/master/pandas/core/accessor.py#L94
pandas.CategoricalIndex.equals | pandas/core/indexes/category.py | 233.0 | https://github.com/pandas-dev/pandas/blob/master/pandas/core/indexes/category.py#L233
pandas.DatetimeIndex.indexer_at_time | pandas/core/indexes/datetimes.py | 1285.0 | https://github.com/pandas-dev/pandas/blob/master/pandas/core/indexes/datetimes.py#L1285
pandas.DataFrame.lt | pandas/core/ops.py | 2059.0 | https://github.com/pandas-dev/pandas/blob/master/pandas/core/ops.py#L2059
pandas.DataFrame.le | pandas/core/ops.py | 2059.0 | https://github.com/pandas-dev/pandas/blob/master/pandas/core/ops.py#L2059
pandas.DataFrame.rolling | pandas/core/generic.py | 10145.0 | https://github.com/pandas-dev/pandas/blob/master/pandas/core/generic.py#L10145
pandas.DataFrame.expanding | pandas/core/generic.py | 10156.0 | https://github.com/pandas-dev/pandas/blob/master/pandas/core/generic.py#L10156
pandas.DataFrame.ewm | pandas/core/generic.py | 10164.0 | https://github.com/pandas-dev/pandas/blob/master/pandas/core/generic.py#L10164
pandas.DataFrame.melt | pandas/core/frame.py | 6106.0 | https://github.com/pandas-dev/pandas/blob/master/pandas/core/frame.py#L6106
pandas.Panel.apply | pandas/core/panel.py | 1000.0 | https://github.com/pandas-dev/pandas/blob/master/pandas/core/panel.py#L1000
pandas.api.types.pandas_dtype | pandas/core/dtypes/common.py | 1981.0 | https://github.com/pandas-dev/pandas/blob/master/pandas/core/dtypes/common.py#L1981
pandas.Timestamp.now | None | NaN | https://github.com/pandas-dev/pandas/blob/master/None#LNone
pandas.melt | pandas/core/reshape/melt.py | 21.0 | https://github.com/pandas-dev/pandas/blob/master/pandas/core/reshape/melt.py#L21
pandas.io.stata.StataReader.data | pandas/io/stata.py | 1430.0 | https://github.com/pandas-dev/pandas/blob/master/pandas/io/stata.py#L1430
pandas.io.stata.StataReader.data_label | pandas/io/stata.py | 1728.0 | https://github.com/pandas-dev/pandas/blob/master/pandas/io/stata.py#L1728
pandas.io.stata.StataReader.value_labels | pandas/io/stata.py | 1738.0 | https://github.com/pandas-dev/pandas/blob/master/pandas/io/stata.py#L1738
pandas.io.stata.StataReader.variable_labels | pandas/io/stata.py | 1732.0 | https://github.com/pandas-dev/pandas/blob/master/pandas/io/stata.py#L1732
pandas.Series.ptp | pandas/core/generic.py | 10943.0 | https://github.com/pandas-dev/pandas/blob/master/pandas/core/generic.py#L10943

Todo:
* [ ]  get rid of the errors in the code base
* [ ]  update the `code_check.sh` script to take into account the `SS05` type of errors

### PR DESCRIPTION
**Pull request by thoo**
- [x] closes #25112
- [ ] tests added / passed (`./scripts/validate_docstrings.py --errors=SS05`)
- [ ] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`

### CODE REVIEW

**Comment by datapythonista** [comment]
@thoo there is one test that checks the docstrings that is being affected by this change. Can you take a look and make the test pass please?

**Comment by jreback** [comment]
can you merge master

File: ci/code_checks.sh [hunk 1]
```diff
@@ -240,8 +240,8 @@ fi
 ### DOCSTRINGS ###
 if [[ -z "$CHECK" || "$CHECK" == "docstrings" ]]; then
 
-    MSG='Validate docstrings (GL06, GL07, GL09, SS04, PR03, PR05, EX04)' ; echo $MSG
```
Comment (jreback) [inline ci/code_checks.sh]: maybe would be helpful to have a description of these here? (future PR ok)

**Comment by jreback** [comment]
thanks @thoo
