### PR TITLE
Lint rule to catch incorrect sphinx directives

### LINKED ISSUE #18425: Lint rule to catch incorrect sphinx directives
#### Code Sample, a copy-pastable example if possible
None. Documentation / build issue.

#### Problem description

There are few places where tag "versionadded" misses one semicolon, making it a sphinx comment instead of directive:
```
pandas/core/frame.py
4516:            .. versionadded: 0.18.0
4679:            .. versionadded: 0.16.1

pandas/core/generic.py
968:            .. versionadded: 0.21.0

pandas/core/series.py
1629:            .. versionadded: 0.19.0
2216:            .. versionadded: 0.18.0

pandas/core/tools/datetimes.py
117:        .. versionadded: 0.18.1
143:        .. versionadded: 0.16.1
181:        .. versionadded: 0.20.0
187:        .. versionadded: 0.22.0

pandas/tseries/offsets.py
778:    .. versionadded: 0.16.1
882:    .. versionadded: 0.18.1
```

Correct way to use it: `.. versionadded:: x.xx.x"` (note two semicolons).

Apart from fixing it here and now, it would be useful to have a lint rule that warns contributors about this and similar issues in future (in docstrings and in docs).

#### Expected Output

Lint rule to catch incorrect sphinx directives.

#### Output of ``pd.show_versions()``
Doesn't matter.

### PR DESCRIPTION
**Pull request by Scorpil**
- [x] closes #18425
- [x] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`

### CODE REVIEW

File: ci/lint.sh [hunk 1]
```diff
@@ -90,13 +90,26 @@ if [ "$LINT" ]; then
     #
     # Check the following functions:
     # any(), all(), sum(), max(), min(), list(), dict(), set(), frozenset(), tuple(), str.join()
-    grep -R --include="*.py*" -E "[^_](any|all|sum|max|min|list|dict|set|frozenset|tuple|join)\(\[.* for .* in .*\]\)"
+    grep -R --include="*.py*" -E "[^_](any|all|sum|max|min|list|dict|set|frozenset|tuple|join)\(\[.* for .* in .*\]\)" *
```
Comment (Scorpil) [inline ci/lint.sh]: I've added a `*` in the end because without it this regexp will just wait for stdin (unless linux version works differently. I've tried it on mac).

File: ci/lint.sh [hunk 2]
```diff
@@ -90,13 +90,26 @@ if [ "$LINT" ]; then
...
 
-    if [ $? = "0" ]; then
+    if [ $? -ne "0" ]; then
```
Comment (Scorpil) [inline ci/lint.sh]: `0` means "nothing found", so I've changed it to `-ne "0"`.

File: ci/lint.sh (hunk 1 above)
Comment (mroeschke) [reply ci/lint.sh]: +1. On Linux, it will grep all directories without the `*`, but for consistency adding `*` or `.` is good.

File: ci/lint.sh [hunk 3]
```diff
@@ -90,13 +90,26 @@ if [ "$LINT" ]; then
...
     echo "Check for use of lists instead of generators in built-in Python functions DONE"
 
+    echo "Check for incorrect sphinx directives"
+    SPHINX_DIRECTIVES=$(echo \
+       "autosummary|contents|currentmodule|deprecated|function|image|"\
+       "important|include|ipython|literalinclude|math|module|note|raw|"\
+       "seealso|toctree|versionadded|versionchanged|warning" | tr -d "[:space:]")
+    for path in './pandas' './doc/source'
+    do
+        grep -R --include="*.py" --include="*.rst" -E "\.\. ($SPHINX_DIRECTIVES):[^:]" $path
```
Comment (jreback) [inline ci/lint.sh]: could include *.pyx here as well (I don't know if we actually have doc-strings that include directives in cython, but can't hurt).

**Review by jreback — APPROVED** [review]
small comment. ping when pushed / green.

**Comment by jreback** [comment]
thanks @Scorpil nice patch!
