### PR TITLE
STY: Use ruff to format docstrings

### LINKED ISSUE #56804: DOC: fix EX03 errors in docstrings
pandas has a script for validating docstrings

https://github.com/pandas-dev/pandas/blob/b7e2202459eadc9dd599cbe58251ecc930798b97/ci/code_checks.sh#L72-L172

Currently, some methods fail the EX03 check.

The task here is:
- take 2-4 methods
- run: scripts/validate_docstrings.py --format=actions --errors=EX03 `method-name`
- check if validation docstrings passes for those methods, and if it’s necessary fix the docstrings according to whatever error is reported
- remove those methods from code_checks.sh
- commit, push, open pull request

Please don't comment `take` as multiple people can work on this issue. You also don't need to ask for permission to work on this, just comment on which methods are you going to work.

If you're new contributor, please check the [contributing guide](https://pandas.pydata.org/docs/dev/development/contributing.html)

thanks @MarcoGorelli for giving me the idea for this issue.

### PR DESCRIPTION
**Pull request by mroeschke**
closes https://github.com/pandas-dev/pandas/issues/56804

### CODE REVIEW

File: ci/code_checks.sh [hunk 1]
```diff
@@ -69,71 +69,6 @@ if [[ -z "$CHECK" || "$CHECK" == "docstrings" ]]; then
     $BASE_DIR/scripts/validate_docstrings.py --format=actions --errors=EX01,EX02,EX04,GL01,GL02,GL03,GL04,GL05,GL06,GL07,GL09,GL10,PR03,PR04,PR05,PR06,PR08,PR09,PR10,RT01,RT02,RT04,RT05,SA02,SA03,SA04,SS01,SS02,SS03,SS04,SS05,SS06
     RET=$(($RET + $?)) ; echo $MSG "DONE"
 
-    MSG='Partially validate docstrings (EX03)' ;  echo $MSG
-    $BASE_DIR/scripts/validate_docstrings.py --format=actions --errors=EX03 --ignore_functions \
-        pandas.Series.plot.line \
```
Comment (MarcoGorelli) [inline ci/code_checks.sh:74]: are you sure this can be removed? `ruff` only works statically, so only checks generated docstrings - any docstring with a substitution won't be checked. that's what `validate_docstrings.py` does

File: pandas/core/base.py [hunk 2]
```diff
@@ -713,8 +713,15 @@ def argmax(
         --------
         Consider dataset containing cereal calories
 
-        >>> s = pd.Series({{'Corn Flakes': 100.0, 'Almond Delight': 110.0,
-        ...                'Cinnamon Toast Crunch': 120.0, 'Cocoa Puff': 110.0}})
+        >>> s = pd.Series(
+        ...     [100.0, 110.0, 120.0, 110.0],
```
Comment (twoertwein) [inline pandas/core/base.py:717]: If ruff can't handle `{{`, it might be better to open an issue at ruff instead of re-writing the documentation.

File: ci/code_checks.sh (hunk 1 above)
Comment (mroeschke) [reply ci/code_checks.sh]: Ah good point. Yeah none of the dynamic docstrings were able to get formatted so I'll revert this

File: pandas/core/base.py (hunk 2 above)
Comment (mroeschke) [reply pandas/core/base.py:717]: True but IMO I think it's okay to rewrite these ones for now just to avoid the potential `{{` confusion for future contributors

File: ci/code_checks.sh (hunk 1 above)
Comment (MarcoGorelli) [reply ci/code_checks.sh]: one more reason to get rid of dynamic docstrings 😉

Comment (mroeschke) [reply ci/code_checks.sh]: Big +1 to remove them!

**Review by rhshadrach — COMMENTED** [review]
lgtm - though I did not exhaustive check every change. Almost everything I see is overwhelmingly positive. The only negative I saw is that some examples became a bit long, and might be good to shorten at some point.

**Comment by mroeschke** [comment]
Thanks for the reviews all. Going to merge to try out this ruff formatting but happy to follow up and update

File: pandas/core/apply.py [hunk 3]
```diff
@@ -1794,14 +1794,14 @@ def normalize_keyword_aggregation(
 
 
 def _make_unique_kwarg_list(
-    seq: Sequence[tuple[Any, Any]]
+    seq: Sequence[tuple[Any, Any]],
```
Comment (simonjayhawkins) [inline pandas/core/apply.py:1797]: this isn't a docstring. did ruff change this?

**Review by simonjayhawkins — COMMENTED** [review]
nice

File: pandas/core/apply.py (hunk 3 above)
Comment (mroeschke) [reply pandas/core/apply.py:1797]: Yeah I believe from ruff's upgrade to `v0.1.13` in this PR
