### PR TITLE
BUG: csv parsing with EOF byte on windows, Revert gh-16039

### LINKED ISSUE #16559: Old read_csv() & EOF character issue back
I recently updated from pandas 0.19.2 to 0.2
I am experiencing the exact same issue as this person did back in 2013
https://github.com/pandas-dev/pandas/issues/5500
"Error tokenizing data. C error: EOF inside string starting at line. 140"

Reverting back to 0.19.2 has fixed the issue. Can run the unit test that was created for this problem?
 https://github.com/gfyoung/pandas/commit/8c4cf85943e647cbb8a0e081ad1e6277dbd309b9

### PR DESCRIPTION
**Pull request by gfyoung**
#16039 created a bug in which files containing byte-like data could break on Windows, as EOF characters mid-field (despite being quoted) would cause premature line breaks.  Given that this PR was a performance patch, this commit can be safely reverted.

Closes #16559 (confirmed with unit test).

cc @dgwynne

### CODE REVIEW

File: pandas/_libs/src/parser/io.c [hunk 1]
```diff
@@ -90,31 +83,17 @@ int del_rd_source(void *rds) {
...
 void *buffer_file_bytes(void *source, size_t nbytes, size_t *bytes_read,
                         int *status) {
-    file_source *fs = FS(source);
-    ssize_t rv;
+    file_source *src = FS(source);
 
-    if (nbytes > fs->size) {
-        nbytes = fs->size;
-    }
+    *bytes_read = fread((void *)src->buffer, sizeof(char), nbytes, src->fp);
```
Comment (jreback) [inline pandas/_libs/src/parser/io.c]: does this only read min(bytes left, nbytes)?

**Comment by jreback** [comment]
looks reasonable. 3.6/windows is failing & pls run the csv asv's just to confirm no regression.

File: pandas/_libs/src/parser/io.c (hunk 1 above)
Comment (gfyoung) [inline pandas/_libs/src/parser/io.c]: Yes, that is correct.

**Comment by gfyoung** [comment]
> 3.6/windows is failing

Actually, it's the 2.7 build on Windows (it passes just fine on Python 3.6)

> pls run the csv asv's just to confirm no regression.

Didn't see any noticeable regressions on my end.

**Comment by gfyoung** [comment]
@jreback : All green and ready to go now.

File: pandas/_libs/src/parser/io.c [hunk 2]
```diff
@@ -9,40 +9,33 @@ The full license is in the LICENSE file, distributed with this software.
...
-#include <sys/stat.h>
-#include <fcntl.h>
-
 /*
   On-disk FILE, uncompressed
 */
 
 void *new_file_source(char *fname, size_t buffer_size) {
     file_source *fs = (file_source *)malloc(sizeof(file_source));
-    if (fs == NULL) {
```
Comment (jreback) [inline pandas/_libs/src/parser/io.c]: fs can still be a NULL pointer no?

File: pandas/_libs/src/parser/io.c [hunk 3]
```diff
@@ -9,40 +9,33 @@ The full license is in the LICENSE file, distributed with this software.
...
-    if (fs->fd == -1) {
-        goto err_free;
-    }
+    fs->initial_file_pos = ftell(fs->fp);
 
     // Only allocate this heap memory if we are not memory-mapping the file
     fs->buffer = (char *)malloc((buffer_size + 1) * sizeof(char));
 
     if (fs->buffer == NULL) {
-        goto err_free;
```
Comment (jreback) [inline pandas/_libs/src/parser/io.c]: don't you need to free fs here? (what about closing the fh)?

File: pandas/_libs/src/parser/io.c [hunk 4]
```diff
@@ -173,86 +152,81 @@ void *buffer_rd_bytes(void *source, size_t nbytes, size_t *bytes_read,
...
 
-    mm->memmap = mmap(NULL, filesize, PROT_READ, MAP_SHARED, mm->fd, 0);
-    if (mm->memmap == MAP_FAILED) {
+    mm->memmap = mmap(NULL, filesize, PROT_READ, MAP_SHARED, fd, 0);
+    if (mm->memmap == NULL) {
         /* XXX Eventually remove this print statement. */
         fprintf(stderr, "new_file_buffer: mmap() failed.\n");
-        goto err_close;
+        free(mm);
+        mm = NULL;
```
Comment (jreback) [inline pandas/_libs/src/parser/io.c]: shouldn't just return NULL here?

**Comment by gfyoung** [comment]
@jreback : I think you raise a couple of good points, but I think I would prefer to merge this (so that the bug is patched) and look into those afterwards as a follow-up, if that works?

**Comment by jreback** [comment]
> I think you raise a couple of good points, but I think I would prefer to merge this (so that the bug is patched) and look into those afterwards as a follow-up, if that works?

that's fine. marking for 0.20.3 as this is a bug fix. if you run into issues and we have to make a bigger change can always just move to 0.21

yes bullet-proofing memory is an issue here (though hard to nail these types of things down).

File: pandas/_libs/src/parser/io.c (hunk 3 above)
Comment (gfyoung) [inline pandas/_libs/src/parser/io.c]: Yes, those would both be good to do here, if possible.

File: pandas/_libs/src/parser/io.c (hunk 2 above)
Comment (gfyoung) [inline pandas/_libs/src/parser/io.c]: Yes, it can be on some architectures.  We should protect against that.

File: pandas/_libs/src/parser/io.c (hunk 4 above)
Comment (gfyoung) [inline pandas/_libs/src/parser/io.c]: Yeah, you can just return `NULL` here IINM.,

**Comment by dgwynne** [comment]
hi guys, sorry im late to the party.

i am surprised by this, i thought that EOF was supposed to be represented outside the allowed set of characters you can have in a file, but after discussing this with a few people i get the impression that windows is special. as suggested by bug 5500, EOF on windows is 0x1a or 27, which can definitely end up in a file. on unix-like systems EOF tends to map to -1 which is supposed to outside what a char can represent.

one of the people i talked to pointed out that i dropped the binary flag when moving from fopen() ("b" in the mode string) to open(). in unix-like systems, the b flag is meaningless, but not on windows.

from what i can tell, ORing O_BINARY into the flags to open() might be enough to fix the problem. because O_BINARY may not be provided on other platforms, a common pattern for handling that is to put something like the following toward the top of the file:

```
#ifndef O_BINARY
#define O_BINARY 0
#endif /* O_BINARY */
```

**Comment by gfyoung** [comment]
@dgwynne : 

> windows is special

That's one way to put it. 😉 

> from what i can tell, ORing O_BINARY into the flags to open() might be enough to fix the problem

Hmm...interesting.  Feel free to give it a shot.  Then we can re-apply your PR with that patch if it works.

File: pandas/_libs/src/parser/io.c (hunk 1 above)
Comment (dgwynne) [inline pandas/_libs/src/parser/io.c]: no, `fread()` will put up to sizeof(char) * nbytes into the buffer at src->buffer. if nbytes is greater than fs->size, then this will overflow. the rest of pandas may limit nbytes to fs->size before passing it to `buffer_file_bytes()`, but id argue that makes reading or auditing this code harder.

**Comment by dgwynne** [comment]
i don't have a windows box with a toolchain i can test with. if i generate a change against head, would you (or someone) be willing to try it?

File: pandas/_libs/src/parser/io.c (hunk 1 above)
Comment (gfyoung) [inline pandas/_libs/src/parser/io.c]: I'm pretty sure we'll hit end-of-file, no?

**Comment by gfyoung** [comment]
We test the codebase against Appveyor, which runs Windows boxes.  You can create an account for free, hook it up to your GitHub account, and it will run those tests for you before you submit the PR (or you could just submit immediately and let the tests run).

File: pandas/_libs/src/parser/io.c (hunk 1 above)
Comment (dgwynne) [inline pandas/_libs/src/parser/io.c]: if the file or the remainder of the file is shorter than fs->size, yes. that isn't the only situation `buffer_file_bytes()` is called in though.

say you have a 1MB file, and `new_file_source()` is called with 1000 as the buffer_size argument, then fs->size will be 1000 bytes long. if `buffer_file_bytes()` is called with nbytes as 2000, then you will read 2000 bytes into a 1000 byte long buffer because there at least that much data available in the file.

**Comment by dgwynne** [comment]
is there a test case that will catch this problem now?

**Comment by gfyoung** [comment]
Yes, I added it in this PR.

File: pandas/_libs/src/parser/io.c (hunk 1 above)
Comment (gfyoung) [inline pandas/_libs/src/parser/io.c]: Okay, got it.  I'll add that to my follow-up PR then.

**Comment by dgwynne** [comment]
#16675 has been created. do i just wait now?
